%% =========================================================
% validate_online_kH60_FG.m
% ==========================================================

clc
clear

files = { ...
    'D:\two\two\tests\results_case_F.mat', ...
    'D:\two\two\tests\results_case_G.mat'};

names = { ...
    'F 低附加速', ...
    'G 低附减速'};

for ic = 1:2

    S = load(files{ic});
    E = S.E;

    updated = E.est_y_data(:,35) > 0.5;

    t = E.est_y_time(updated);
    Y = E.est_y_data(updated,:);

    vxTrue = interp1( ...
        E.Vx_true_time(:), ...
        E.Vx_true_data(:), ...
        t, ...
        'linear', ...
        NaN);

    if ic == 1

        windows = { ...
            [0.600 3.000], ...
            [3.000 5.778], ...
            [5.778 7.999], ...
            [7.999 10.000]};

        winNames = { ...
            '稳态', ...
            '锁定前', ...
            '锁定', ...
            '恢复'};

    else

        windows = { ...
            [0.600 3.000], ...
            [3.000 4.709], ...
            [4.709 9.175], ...
            [9.175 11.175]};

        winNames = { ...
            '稳态', ...
            '锁定前', ...
            '锁定', ...
            '恢复'};

    end

    fprintf('\n');
    fprintf('=====================================================\n');
    fprintf('%s - kH=60 在线验证\n',names{ic});
    fprintf('=====================================================\n');

    for iw = 1:4

        w = windows{iw};

        idx = ...
            t >= w(1) & ...
            t < w(2) & ...
            isfinite(vxTrue);

        xW = Y(:,3);
        xI = Y(:,5);
        vxF = Y(:,1);

        alphaW = Y(:,30);

        fprintf('\n--- %s %.3f~%.3f s ---\n', ...
            winNames{iw},w(1),w(2));

        fprintf('mean alphaW = %.6f\n', ...
            mean(alphaW(idx)));

        fprintf('P95 alphaW  = %.6f\n', ...
            prctile(alphaW(idx),95));

        fprintf('WSS RMSE   = %.6f m/s\n', ...
            sqrt(mean((xW(idx)-vxTrue(idx)).^2)));

        fprintf('IMU RMSE   = %.6f m/s\n', ...
            sqrt(mean((xI(idx)-vxTrue(idx)).^2)));

        fprintf('FUSED RMSE = %.6f m/s\n', ...
            sqrt(mean((vxF(idx)-vxTrue(idx)).^2)));

    end

end

fprintf('\n=====================================================\n');
fprintf('离线kH=60预测：\n');
fprintf('F lock alphaW ≈ 0.1236, RMSE ≈ 0.227789\n');
fprintf('G lock alphaW ≈ 0.1405, RMSE ≈ 0.088399\n');
fprintf('F/G recover alphaW ≈ 0.9756\n');
fprintf('=====================================================\n');