function D = compute_traditional_wss_vx(sourceFile,outDir)
%COMPUTE_TRADITIONAL_WSS_VX Derive an equal-mean kinematic WSS baseline.
% Uses an accepted formal raw result only; no simulation is invoked.
% Traditional WSS is exactly: four kinematic candidates -> arithmetic mean.

root=fileparts(fileparts(mfilename('fullpath')));
if nargin<1||isempty(sourceFile)
    sourceFile=fullfile(root,'results','vx_formal_validation','v3','runtime','VX_ND_formal_raw.mat');
end
if nargin<2||isempty(outDir)
    outDir=fullfile(root,'results','vx_formal_validation','v3b','final_acceptance','traditional_wss');
end
if ~isfolder(outDir),mkdir(outDir);end
S=load(sourceFile,'R');R=S.R;
assert(R.metadata.formalRuntime,'VX:TraditionalWSS:Evidence');
caseId=char(R.metadata.caseId);
switch caseId
    case 'VX-ND'
        assert(abs(R.configuration.muRoadConstant-0.80)<1e-12&&strcmp(R.configuration.referenceUnit,'km/h'), ...
            'VX:TraditionalWSS:NDConfiguration');
        assert(isequal(R.configuration.speedReference.speedTime_s(:),[0;3;7;9;13;16])&& ...
            isequal(R.configuration.speedReference.speed_kmh(:),[60;60;100;100;60;60]), ...
            'VX:TraditionalWSS:NDProfile');
        outputStem='VX_ND';referenceInitialKmh=60;muRoad=0.80;
        speedTime=[0;3;7;9;13;16];speedKmh=[60;60;100;100;60;60];
    case 'VX-CS40'
        assert(strcmp(R.metadata.verdict,'VX_CS40_V4C_FORMAL_PASS')&& ...
            R.metadata.initialStateGatePass&&R.metadata.driveGatePass&& ...
            R.metadata.brakeGatePass&&R.metadata.estimatorFiniteGatePass, ...
            'VX:TraditionalWSS:V4CFormalGate');
        assert(abs(R.configuration.muRoadConstant-0.30)<1e-12&& ...
            strcmp(R.configuration.referenceUnit,'km/h'),'VX:TraditionalWSS:V4CConfiguration');
        assert(isequal(R.configuration.speedTime_s(:),[0;3;6;9;11.5;16])&& ...
            isequal(R.configuration.speed_kmh(:),[40;40;70;70;40;40]), ...
            'VX:TraditionalWSS:V4CProfile');
        outputStem='VX_CS40';referenceInitialKmh=40;muRoad=0.30;
        speedTime=[0;3;6;9;11.5;16];speedKmh=[40;40;70;70;40;40];
    case 'VX-ND60'
        assert(strcmp(R.metadata.verdict,'VX_ND60_FORMAL_PASS')&& ...
            R.metadata.initialStateGatePass&&R.metadata.estimatorFiniteGatePass, ...
            'VX:TraditionalWSS:ND60FormalGate');
        assert(abs(R.configuration.muRoadConstant-0.80)<1e-12&& ...
            strcmp(R.configuration.referenceUnit,'km/h'),'VX:TraditionalWSS:ND60Configuration');
        assert(isequal(R.configuration.speedTime_s(:),[0;3;7;9;13;16])&& ...
            isequal(R.configuration.speed_kmh(:),[60;60;100;100;60;60]), ...
            'VX:TraditionalWSS:ND60Profile');
        outputStem='VX_ND60';referenceInitialKmh=60;muRoad=0.80;
        speedTime=[0;3;7;9;13;16];speedKmh=[60;60;100;100;60;60];
    otherwise
        error('VX:TraditionalWSS:UnsupportedCase','Unsupported formal case %s.',caseId);
end

t=double(R.time(:));vxTrue=double(R.vxTrue(:));U=double(R.estU);Y=double(R.estY);
assert(size(U,1)==numel(t)&&size(U,2)==18&&size(Y,1)==numel(t)&&size(Y,2)==38, ...
    'VX:TraditionalWSS:Interface');
omega=U(:,1:4);delta=U(:,5:8);yawRate=U(:,14);
Rw=0.393;a=1.18;b=1.77;d=1.575;vyPrior=0;
xWheel=[a;a;-b;-b];yWheel=[d/2;-d/2;d/2;-d/2];
vxWheel=nan(numel(t),4);
for i=1:4
    vxWheel(:,i)=yawRate.*yWheel(i)+(Rw.*omega(:,i)- ...
        (vyPrior+yawRate.*xWheel(i)).*sin(delta(:,i)))./cos(delta(:,i));
end
vxTraditional=mean(vxWheel,2);
vxFusion=Y(:,1);
evaluationWindow_s=[0.6 16];
evaluationMask=t>=evaluationWindow_s(1)&t<=evaluationWindow_s(2)& ...
    isfinite(vxTrue)&isfinite(vxTraditional)&isfinite(vxFusion);
if strcmp(caseId,'VX-ND'),evaluationMask=evaluationMask&Y(:,35)>0.5;end
assert(any(evaluationMask),'VX:TraditionalWSS:EmptyWindow');
eTraditional=vxTraditional-vxTrue;eFusion=vxFusion-vxTrue;
traditional=metrics(eTraditional(evaluationMask));fusion=metrics(eFusion(evaluationMask));
firstFinite=find(isfinite(vxTrue),1,'first');assert(~isempty(firstFinite),'VX:TraditionalWSS:NoTruth');

M=struct('REFERENCE_INITIAL_SPEED_KMH',referenceInitialKmh, ...
    'ACTUAL_CARSIM_INITIAL_VX_MPS',vxTrue(firstFinite), ...
    'ACTUAL_CARSIM_INITIAL_VX_KMH',3.6*vxTrue(firstFinite), ...
    'TraditionalWSS_RMSE',traditional.RMSE, ...
    'TraditionalWSS_MAE',traditional.MAE, ...
    'TraditionalWSS_MaxAbs',traditional.MaxAbs, ...
    'Fusion_RMSE',fusion.RMSE,'Fusion_MAE',fusion.MAE, ...
    'Fusion_MaxAbs',fusion.MaxAbs, ...
    'TraditionalMinusFusion_RMSE',traditional.RMSE-fusion.RMSE);
D=struct('stage','VX-ND-THESIS-DERIVED-BASELINE','sourceFormalRaw',sourceFile, ...
    'sourceFormalRawSha256',sha256_file(sourceFile),'caseId',caseId, ...
    'muRoadConstant',muRoad,'referenceUnit','km/h', ...
    'speedTime_s',speedTime,'speed_kmh',speedKmh, ...
    'evaluationWindow_s',evaluationWindow_s,'evaluationMask',evaluationMask, ...
    'time',t,'vxTrue',vxTrue,'omega',omega,'delta',delta,'yawRate',yawRate, ...
    'geometry',struct('Rw',Rw,'a',a,'b',b,'d',d,'vyPrior',vyPrior, ...
    'xWheel',xWheel,'yWheel',yWheel), ...
    'vxWheel',vxWheel,'vxTraditional',vxTraditional,'vxFusion',vxFusion, ...
    'eTraditional',eTraditional,'eFusion',eFusion,'metrics',M);
if strcmp(caseId,'VX-CS40')
    D.stage='VX-V4C-CS40-THESIS-DERIVED-BASELINE';
    driveMask=t>=3&t<7&isfinite(eTraditional)&isfinite(eFusion);
    brakeMask=t>=9&t<12&isfinite(eTraditional)&isfinite(eFusion);
    assert(any(driveMask)&&any(brakeMask),'VX:TraditionalWSS:PhaseWindow');
    dt=metrics(eTraditional(driveMask));df=metrics(eFusion(driveMask));
    bt=metrics(eTraditional(brakeMask));bf=metrics(eFusion(brakeMask));
    D.phaseMetrics=struct('drive',struct('window_s',[3 7],'traditional',dt,'fusion',df, ...
        'TraditionalMinusFusion_RMSE',dt.RMSE-df.RMSE), ...
        'brake',struct('window_s',[9 12],'traditional',bt,'fusion',bf, ...
        'TraditionalMinusFusion_RMSE',bt.RMSE-bf.RMSE));
    perf=table(["Traditional WSS";"Fusion";"Traditional minus Fusion"], ...
        [traditional.RMSE;fusion.RMSE;traditional.RMSE-fusion.RMSE], ...
        [traditional.MAE;fusion.MAE;NaN],[traditional.MaxAbs;fusion.MaxAbs;NaN], ...
        'VariableNames',{'Estimator','RMSE_mps','MAE_mps','MaxAbs_mps'});
    phase=table(["DRIVE";"BRAKE"],[3;9],[7;12],[dt.RMSE;bt.RMSE], ...
        [df.RMSE;bf.RMSE],[dt.RMSE-df.RMSE;bt.RMSE-bf.RMSE], ...
        'VariableNames',{'Phase','WindowStart_s','WindowEnd_s','TraditionalWSS_RMSE_mps', ...
        'Fusion_RMSE_mps','TraditionalMinusFusion_RMSE_mps'});
    writetable(perf,fullfile(outDir,'VX_CS40_performance_metrics.csv'));
    writetable(phase,fullfile(outDir,'VX_CS40_phase_metrics.csv'));
elseif strcmp(caseId,'VX-ND60')
    D.stage='VX-V4-ND60-THESIS-DERIVED-BASELINE';
    perf=table(["Traditional WSS";"Fusion";"Traditional minus Fusion"], ...
        [traditional.RMSE;fusion.RMSE;traditional.RMSE-fusion.RMSE], ...
        [traditional.MAE;fusion.MAE;NaN],[traditional.MaxAbs;fusion.MaxAbs;NaN], ...
        'VariableNames',{'Estimator','RMSE_mps','MAE_mps','MaxAbs_mps'});
    writetable(perf,fullfile(outDir,'VX_ND60_performance_metrics.csv'));
else
    writetable(struct2table(M),fullfile(outDir,'VX_ND_traditional_wss_metrics.csv'));
end
save(fullfile(outDir,[outputStem '_traditional_wss.mat']),'D','-v7.3');
fprintf('%s_TRADITIONAL_WSS|rmse=%.9g|fusion=%.9g|improvement=%.9g|actual0=%.9g\n', ...
    outputStem, ...
    traditional.RMSE,fusion.RMSE,M.TraditionalMinusFusion_RMSE,vxTrue(firstFinite));
end

function m=metrics(e)
e=e(isfinite(e));assert(~isempty(e),'VX:TraditionalWSS:NoFiniteError');
m=struct('RMSE',sqrt(mean(e.^2)),'MAE',mean(abs(e)),'MaxAbs',max(abs(e)));
end
function hash=sha256_file(file)
d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));
q=java.security.DigestInputStream(s,d);c=onCleanup(@()q.close());while q.read()~=-1,end
hash=upper(reshape(dec2hex(typecast(d.digest(),'uint8'),2).',1,[]));clear c
end
