function [simIn,cfg] = configure_vx_formal_case_v3b(caseId)
%CONFIGURE_VX_FORMAL_CASE_V3B Recreate the frozen VX-CS validation copy.
% This function only supports VX-CS and never calls sim().

arguments
    caseId (1,1) string = "VX-CS"
end
caseId=upper(strrep(strtrim(caseId),'_','-'));
assert(caseId=="VX-CS",'VX:V3B:Case','Only VX-CS is supported.');
root=fileparts(fileparts(mfilename('fullpath')));
freezeFile=fullfile(root,'results','vx_formal_validation','v3b','frozen_physical_excitation.json');
assert(isfile(freezeFile),'VX:V3B:FreezeMissing','Frozen excitation is required.');
freeze=jsondecode(fileread(freezeFile));
assert(strcmp(freeze.PHYSICAL_EXCITATION_FROZEN,'YES')&& ...
    strcmp(freeze.caseId,'VX-CS'),'VX:V3B:FreezeInvalid');
assert(strcmp(freeze.selectedTier,'TIER1_REFERENCE_ONLY'), ...
    'VX:V3B:Tier','This execution layer currently supports the passing Tier-1 route.');

source=struct( ...
    'model',fullfile(root,'model','vx.slx'), ...
    'estimator',fullfile(root,'model','longitudinal_velocity_estimator.m'), ...
    'parameter',fullfile(root,'model','estimator_default_params.m'), ...
    'wrapper',fullfile(root,'model','longitudinal_velocity_estimator_simulink.m'));
names=fieldnames(source);
for k=1:numel(names)
    assert(strcmp(sha256_file(source.(names{k})),freeze.sourceHashes.(names{k})), ...
        'VX:V3B:SourceHash','Frozen source hash changed: %s.',names{k});
end

calRoot=fullfile(root,'results','vx_formal_validation','v3b','configured', ...
    'calibration',freeze.selectedCandidate);
calCfgFile=fullfile(calRoot,'case_configuration.mat');
assert(isfile(calCfgFile),'VX:V3B:CalibrationConfigMissing');
S=load(calCfgFile,'cfg');cal=S.cfg;
assert(isequal(double(cal.speedTime_s(:)),double(freeze.speedTime_s(:)))&& ...
    isequal(double(cal.speed_kmh(:)),double(freeze.speed_kmh(:))), ...
    'VX:V3B:ProfileMismatch','Calibration configuration differs from freeze.');
assert(strcmp(sha256_file(cal.generatedModel),freeze.generatedHashes.model)&& ...
    strcmp(sha256_file(cal.simfile),freeze.generatedHashes.simfile)&& ...
    strcmp(sha256_file(cal.runAll),freeze.generatedHashes.runAll), ...
    'VX:V3B:GeneratedHash','Frozen calibration assets changed.');

formalRoot=fullfile(root,'results','vx_formal_validation','v3b','configured','formal','VX_CS');
modelDir=fullfile(formalRoot,'model');controlDir=fullfile(formalRoot,'carsim_control');
if ~isfolder(modelDir),mkdir(modelDir);end
if ~isfolder(controlDir),mkdir(controlDir);end
[~,modelName,ext]=fileparts(cal.generatedModel);
modelFile=fullfile(modelDir,[modelName ext]);
copyfile(cal.generatedModel,modelFile,'f');
copyfile(cal.simfile,fullfile(controlDir,'simfile.sim'),'f');
copyfile(cal.runAll,fullfile(controlDir,'Run_all.par'),'f');
assert(strcmp(sha256_file(modelFile),freeze.generatedHashes.model)&& ...
    strcmp(sha256_file(fullfile(controlDir,'simfile.sim')),freeze.generatedHashes.simfile)&& ...
    strcmp(sha256_file(fullfile(controlDir,'Run_all.par')),freeze.generatedHashes.runAll), ...
    'VX:V3B:FormalCopyHash','Formal copy is not byte-identical to frozen assets.');

if bdIsLoaded(modelName),close_system(modelName,0);end
load_system(modelFile);simIn=Simulink.SimulationInput(modelName);
simIn=simIn.setModelParameter('StopTime','16','ReturnWorkspaceOutputs','on');
close_system(modelName,0);
cfg=struct('stage','VX-V3B','caseId','VX-CS','formalRuntime',true, ...
    'speedReference',struct('speedTime_s',double(freeze.speedTime_s(:)), ...
    'speed_kmh',double(freeze.speed_kmh(:))),'referenceUnit','km/h', ...
    'brakeRampEnd_s',freeze.brakeRampEnd_s, ...
    'brakeAnalysisEnd_s',freeze.brakeAnalysisEnd_s, ...
    'muRoadConstant',freeze.muRoadConstant,'sourceModel',source.model, ...
    'generatedModel',modelFile,'runtimeWorkingDirectory',controlDir, ...
    'simfile',fullfile(controlDir,'simfile.sim'), ...
    'runAll',fullfile(controlDir,'Run_all.par'), ...
    'sourceHashes',freeze.sourceHashes,'generatedHashes',freeze.generatedHashes, ...
    'freezeFile',freezeFile,'freezeFileSha256',sha256_file(freezeFile), ...
    'selectedTier',freeze.selectedTier,'selectedCandidate',freeze.selectedCandidate);
save(fullfile(formalRoot,'case_configuration.mat'),'cfg');
end

function hash=sha256_file(file)
d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));
q=java.security.DigestInputStream(s,d);c=onCleanup(@()q.close());while q.read()~=-1,end
hash=upper(reshape(dec2hex(typecast(d.digest(),'uint8'),2).',1,[]));clear c
end
