function tests = test_estimator_default_params
%TEST_ESTIMATOR_DEFAULT_PARAMS
% Unit tests for Stage 3A default estimator parameters.
%
% Covers:
%   TEST 1 - required parameter fields exist
%   TEST 2 - fixed Stage-3A nominal parameter values
%   TEST 3 - timing consistency
%   TEST 4 - vehicle geometry validity
%   TEST 5 - slip-confidence parameter validity
%   TEST 6 - KF covariance/process-noise validity
%   TEST 7 - IMU-only fallback parameter validity
%
% MATLAB execution state: READY TO RUN
% VALIDATION state: PENDING MATLAB VALIDATION
%
% Run:
%   r = runtests('tests/test_estimator_default_params.m');
%   table(r)

tests = functiontests(localfunctions);

end


%% ========================================================================
% Setup
% ========================================================================

function setupOnce(testCase)
% Allow this test file to run independently.

testDir = fileparts(mfilename('fullpath'));
matlabDir = fullfile(testDir, '..', 'matlab');

testCase.verifyTrue( ...
    isfolder(matlabDir), ...
    'Cannot find ../matlab source directory.');

testCase.applyFixture( ...
    matlab.unittest.fixtures.PathFixture(matlabDir));

end


%% ========================================================================
% TEST 1
% ========================================================================

function test_required_fields_exist(testCase)
% TEST 1:
% All Stage-3A required parameter fields must exist.

p = estimator_default_params();

requiredFields = { ...
    'Ts_est', ...
    'Twindow', ...
    'Nwindow', ...
    'TimuOnlyMax', ...
    'Rw', ...
    'a', ...
    'b', ...
    'd', ...
    'e_low', ...
    'e_high', ...
    'eAbs_low', ...
    'eAbs_high', ...
    'eDelta_recover', ...
    'eAbs_recover', ...
    'Nrecover', ...
    'rho_hard', ...
    'R0', ...
    'R_min', ...
    'R_max', ...
    'cos_delta_min', ...
    'v_low', ...
    'QW', ...
    'QI', ...
    'PW0', ...
    'PI0', ...
    'PWI0' ...
};

for i = 1:numel(requiredFields)

    fieldName = requiredFields{i};

    testCase.verifyTrue( ...
        isfield(p, fieldName), ...
        sprintf( ...
            'TEST1: Missing parameter field: %s', ...
            fieldName));

end

end


%% ========================================================================
% TEST 2
% ========================================================================

function test_nominal_stage3a_values(testCase)
% TEST 2:
% Verify fixed Stage-3A nominal values.
%
% These checks intentionally lock the current baseline configuration.
% If the vehicle or estimator design parameters are deliberately changed,
% this test should be updated together with the documented baseline.

p = estimator_default_params();

tol = 1e-12;


%% Estimator timing

testCase.verifyEqual( ...
    p.Ts_est, ...
    0.01, ...
    'AbsTol', tol, ...
    'TEST2: Ts_est should be 0.01 s.');

testCase.verifyEqual( ...
    p.Twindow, ...
    0.5, ...
    'AbsTol', tol, ...
    'TEST2: Twindow should be 0.5 s.');

testCase.verifyEqual( ...
    p.Nwindow, ...
    50, ...
    'TEST2: Nwindow should be 50 samples.');

%% Absolute consistency parameters

testCase.verifyEqual( ...
    p.eAbs_low, ...
    0.15, ...
    'AbsTol', 1e-12, ...
    'TEST2: eAbs_low should be fixed at 0.15 m/s.');

testCase.verifyEqual( ...
    p.eAbs_high, ...
    0.50, ...
    'AbsTol', 1e-12, ...
    'TEST2: eAbs_high should be fixed at 0.50 m/s.');

testCase.verifyEqual( ...
    p.eDelta_recover, ...
    0.12, ...
    'AbsTol', 1e-12, ...
    'TEST2: eDelta_recover should be fixed at 0.12.');

testCase.verifyEqual( ...
    p.eAbs_recover, ...
    0.12, ...
    'AbsTol', 1e-12, ...
    'TEST2: eAbs_recover should be fixed at 0.12.');

testCase.verifyEqual( ...
    p.Nrecover, ...
    30, ...
    'AbsTol', 1e-12, ...
    'TEST2: Nrecover should be fixed at 30.');
%% Wheel radius

testCase.verifyEqual( ...
    p.Rw, ...
    0.393, ...
    'AbsTol', tol, ...
    'TEST2: Rw should be 0.393 m.');


%% Vehicle geometry

testCase.verifyEqual( ...
    p.a, ...
    1.18, ...
    'AbsTol', tol, ...
    'TEST2: a should be 1.18 m.');

testCase.verifyEqual( ...
    p.b, ...
    1.77, ...
    'AbsTol', tol, ...
    'TEST2: b should be 1.77 m.');

testCase.verifyEqual( ...
    p.d, ...
    1.575, ...
    'AbsTol', tol, ...
    'TEST2: track width d should be 1.575 m.');

end


%% ========================================================================
% TEST 3
% ========================================================================

function test_timing_consistency(testCase)
% TEST 3:
% Estimator timing parameters must be positive and internally consistent.

p = estimator_default_params();


%% Positive sampling interval

testCase.verifyGreaterThan( ...
    p.Ts_est, ...
    0, ...
    'TEST3: Ts_est must be positive.');


%% Positive window duration

testCase.verifyGreaterThan( ...
    p.Twindow, ...
    0, ...
    'TEST3: Twindow must be positive.');


%% Positive integer window length

testCase.verifyGreaterThan( ...
    p.Nwindow, ...
    0, ...
    'TEST3: Nwindow must be positive.');

testCase.verifyEqual( ...
    p.Nwindow, ...
    round(p.Nwindow), ...
    'TEST3: Nwindow must be integer-valued.');


%% Twindow / Ts_est consistency

expectedNwindow = ...
    round(p.Twindow / p.Ts_est);

testCase.verifyEqual( ...
    p.Nwindow, ...
    expectedNwindow, ...
    ['TEST3: Nwindow must equal ', ...
     'round(Twindow/Ts_est).']);


%% Explicit duration reconstruction

testCase.verifyEqual( ...
    p.Nwindow * p.Ts_est, ...
    p.Twindow, ...
    'AbsTol', 1e-12, ...
    ['TEST3: Nwindow*Ts_est should ', ...
     'reconstruct Twindow.']);

end


%% ========================================================================
% TEST 4
% ========================================================================

function test_vehicle_geometry_parameters(testCase)
% TEST 4:
% Vehicle geometry parameters used by four-wheel kinematics
% must remain physically meaningful.

p = estimator_default_params();


%% Wheel radius

testCase.verifyGreaterThan( ...
    p.Rw, ...
    0, ...
    'TEST4: wheel radius Rw must be positive.');


%% CG-to-axle distances

testCase.verifyGreaterThan( ...
    p.a, ...
    0, ...
    'TEST4: front CG distance a must be positive.');

testCase.verifyGreaterThan( ...
    p.b, ...
    0, ...
    'TEST4: rear CG distance b must be positive.');


%% Track width

testCase.verifyGreaterThan( ...
    p.d, ...
    0, ...
    'TEST4: track width d must be positive.');


%% Steering cosine guard

testCase.verifyGreaterThanOrEqual( ...
    p.cos_delta_min, ...
    0, ...
    'TEST4: cos_delta_min must be >= 0.');

testCase.verifyLessThanOrEqual( ...
    p.cos_delta_min, ...
    1, ...
    'TEST4: cos_delta_min must be <= 1.');


%% Low-speed guard

testCase.verifyGreaterThan( ...
    p.v_low, ...
    0, ...
    'TEST4: v_low must be positive.');

end


%% ========================================================================
% TEST 5
% ========================================================================

function test_slip_confidence_parameters(testCase)
% TEST 5:
% Validate slip-confidence thresholds and covariance bounds.

p = estimator_default_params();


%% Slip thresholds

testCase.verifyGreaterThanOrEqual( ...
    p.e_low, ...
    0, ...
    'TEST5: e_low must be non-negative.');

testCase.verifyGreaterThan( ...
    p.e_high, ...
    p.e_low, ...
    'TEST5: e_high must be greater than e_low.');


%% Hard confidence threshold

testCase.verifyGreaterThanOrEqual( ...
    p.rho_hard, ...
    0, ...
    'TEST5: rho_hard must be >= 0.');

testCase.verifyLessThanOrEqual( ...
    p.rho_hard, ...
    1, ...
    'TEST5: rho_hard must be <= 1.');


%% Nominal measurement covariance

testCase.verifyGreaterThan( ...
    p.R0, ...
    0, ...
    'TEST5: R0 must be positive.');


%% Covariance clipping bounds

testCase.verifyGreaterThan( ...
    p.R_min, ...
    0, ...
    'TEST5: R_min must be positive.');

testCase.verifyGreaterThanOrEqual( ...
    p.R_max, ...
    p.R_min, ...
    'TEST5: R_max must be >= R_min.');

end


%% ========================================================================
% TEST 6
% ========================================================================

function test_local_kf_parameters(testCase)
% TEST 6:
% Local WSS / IMU scalar-KF parameters must be valid.

p = estimator_default_params();


%% WSS process noise

testCase.verifyGreaterThan( ...
    p.QW, ...
    0, ...
    'TEST6: QW must be positive.');


%% IMU process noise

testCase.verifyGreaterThan( ...
    p.QI, ...
    0, ...
    'TEST6: QI must be positive.');


%% WSS initial covariance

testCase.verifyGreaterThan( ...
    p.PW0, ...
    0, ...
    'TEST6: PW0 must be positive.');


%% IMU initial covariance

testCase.verifyGreaterThan( ...
    p.PI0, ...
    0, ...
    'TEST6: PI0 must be positive.');


%% Cross-covariance initial value

testCase.verifyGreaterThanOrEqual( ...
    p.PWI0, ...
    0, ...
    'TEST6: PWI0 must be non-negative.');


%% All KF parameters must be finite

kfValues = [ ...
    p.QW, ...
    p.QI, ...
    p.PW0, ...
    p.PI0, ...
    p.PWI0 ...
];

testCase.verifyTrue( ...
    all(isfinite(kfValues)), ...
    'TEST6: KF parameters must all be finite.');

end


%% ========================================================================
% TEST 7
% ========================================================================

function test_imu_only_fallback_parameter(testCase)
% TEST 7:
% Maximum allowed IMU-only duration must be finite and positive.

p = estimator_default_params();


%% Positive

testCase.verifyGreaterThan( ...
    p.TimuOnlyMax, ...
    0, ...
    'TEST7: TimuOnlyMax must be positive.');


%% Finite

testCase.verifyTrue( ...
    isfinite(p.TimuOnlyMax), ...
    'TEST7: TimuOnlyMax must be finite.');


%% Should represent at least one estimator step

testCase.verifyGreaterThanOrEqual( ...
    p.TimuOnlyMax, ...
    p.Ts_est, ...
    ['TEST7: TimuOnlyMax should allow at least ', ...
     'one estimator sample.']);

end
