function tests = test_correlated_two_track_fusion
%TEST_CORRELATED_TWO_TRACK_FUSION
% Stage 3D2B unit tests for correlated_two_track_fusion.
%
% Covers:
%   TEST 1  - PWI prediction
%   TEST 2  - PWI two-sided update
%   TEST 3  - KW=0, KI=0
%   TEST 4  - KW=0, KI~=0
%   TEST 5  - KW~=0, KI=0
%   TEST 6  - correlated fusion numerical formula
%   TEST 7  - difference from independent inverse-variance fusion
%   TEST 8  - negative fusion weights are allowed
%   TEST 9  - single-channel degradation
%   TEST 10 - both channels invalid
%   TEST 11 - PWI physical bound protection
%   TEST 12 - Phi near-singular behavior
%   TEST 13 - illegal variance input protection
%   TEST 14 - Pfused formula sanity
%   TEST 15 - condPhi behavior
%   TEST 16 - local KF + correlated fusion composition
%
% MATLAB execution state: READY TO RUN
% VALIDATION state: PENDING MATLAB VALIDATION
%
% Run:
%   r = runtests('tests/test_correlated_two_track_fusion.m');
%   table(r)

tests = functiontests(localfunctions);

end


%% ========================================================================
% Setup
% ========================================================================

function setupOnce(testCase)
% Allow independent execution of this test file.

testDir = fileparts(mfilename('fullpath'));
matlabDir = fullfile(testDir, '..', 'matlab');

testCase.verifyTrue( ...
    isfolder(matlabDir), ...
    'Cannot find ../matlab source directory.');

testCase.applyFixture( ...
    matlab.unittest.fixtures.PathFixture(matlabDir));

end


%% ========================================================================
% TEST 1
% PWI prediction
% ========================================================================

function test_pwi_prediction(testCase)

p = make_fusion_params();

pTest = p;
pTest.QW = 4e-4;
pTest.QI = 2e-4;

PWI_prev = 0.37;

PW = 1.2;
PI = 2.2;

KW = 0.40;
KI = 0.10;

[~, ~, ~, ~, PWI_minus, PWI_plus] = ...
    correlated_two_track_fusion( ...
        0, PW, KW, ...
        0, PI, KI, ...
        PWI_prev, ...
        true, true, ...
        pTest);

expectedPwiMinus = ...
    PWI_prev + ...
    (pTest.QW + pTest.QI) / 2;

testCase.verifyEqual( ...
    PWI_minus, ...
    expectedPwiMinus, ...
    'AbsTol', 1e-12, ...
    'TEST1: PWI_minus prediction formula mismatch.');

testCase.verifyTrue( ...
    isfinite(PWI_plus), ...
    'TEST1: PWI_plus must remain finite.');

end


%% ========================================================================
% TEST 2
% PWI two-sided posterior update
% ========================================================================

function test_pwi_two_sided_update(testCase)

pZero = make_zero_process_params();

PWI_prev = 2.4;

PW = 1.5;
PI = 1.8;

KW = 0.25;
KI = 0.40;

[~, ~, ~, ~, ~, PWI_plus] = ...
    correlated_two_track_fusion( ...
        0, PW, KW, ...
        0, PI, KI, ...
        PWI_prev, ...
        true, true, ...
        pZero);

expectedPwiPlus = ...
    (1 - KW) * ...
    PWI_prev * ...
    (1 - KI);


%% Correct two-sided update

testCase.verifyEqual( ...
    PWI_plus, ...
    expectedPwiPlus, ...
    'AbsTol', 1e-12, ...
    'TEST2: PWI_plus two-sided update mismatch.');


%% Must not accidentally use one-sided WSS update

wrongWssOnly = ...
    (1 - KW) * PWI_prev;

testCase.verifyGreaterThanOrEqual( ...
    abs(PWI_plus - wrongWssOnly), ...
    1e-3, ...
    'TEST2: PWI update incorrectly matches WSS-only form.');


%% Must not accidentally use one-sided IMU update

wrongImuOnly = ...
    PWI_prev * (1 - KI);

testCase.verifyGreaterThanOrEqual( ...
    abs(PWI_plus - wrongImuOnly), ...
    1e-3, ...
    'TEST2: PWI update incorrectly matches IMU-only form.');


%% Must not use additive mistaken expression

wrongAdditive = ...
    (1 - KW) * PWI_prev + ...
    (1 - KI);

testCase.verifyGreaterThanOrEqual( ...
    abs(PWI_plus - wrongAdditive), ...
    1e-3, ...
    'TEST2: PWI update incorrectly matches additive form.');

end


%% ========================================================================
% TEST 3
% KW = 0, KI = 0
% ========================================================================

function test_zero_gains_preserve_pwi(testCase)

pZero = make_zero_process_params();

PWI_prev = 0.91;

[~, ~, ~, ~, PWI_minus, PWI_plus] = ...
    correlated_two_track_fusion( ...
        -1, 1.0, 0, ...
         2, 1.2, 0, ...
        PWI_prev, ...
        true, true, ...
        pZero);

testCase.verifyEqual( ...
    PWI_plus, ...
    PWI_minus, ...
    'AbsTol', 1e-12, ...
    ['TEST3: with KW=0 and KI=0, ', ...
     'PWI_plus must equal PWI_minus.']);

end


%% ========================================================================
% TEST 4
% KW = 0, KI ~= 0
% ========================================================================

function test_kw_zero_ki_nonzero(testCase)

pZero = make_zero_process_params();

KW = 0;
KI = 0.33;

PWI_prev = 1.5;

[~, ~, ~, ~, PWI_minus, PWI_plus] = ...
    correlated_two_track_fusion( ...
        -1, 1.0, KW, ...
         2, 2.5, KI, ...
        PWI_prev, ...
        true, true, ...
        pZero);

expected = ...
    PWI_minus * (1 - KI);

testCase.verifyEqual( ...
    PWI_plus, ...
    expected, ...
    'AbsTol', 1e-12, ...
    ['TEST4: KW=0 should leave only ', ...
     'the (1-KI) multiplication.']);

end


%% ========================================================================
% TEST 5
% KW ~= 0, KI = 0
% ========================================================================

function test_kw_nonzero_ki_zero(testCase)

pZero = make_zero_process_params();

KW = 0.4;
KI = 0;

PWI_prev = 1.5;

[~, ~, ~, ~, PWI_minus, PWI_plus] = ...
    correlated_two_track_fusion( ...
        -1, 1.0, KW, ...
         2, 2.5, KI, ...
        PWI_prev, ...
        true, true, ...
        pZero);

expected = ...
    (1 - KW) * PWI_minus;

testCase.verifyEqual( ...
    PWI_plus, ...
    expected, ...
    'AbsTol', 1e-12, ...
    ['TEST5: KI=0 should leave only ', ...
     'the (1-KW) multiplication.']);

end


%% ========================================================================
% TEST 6
% Correlated fusion numerical formula
% ========================================================================

function test_correlated_fusion_numeric(testCase)

pZero = make_zero_process_params();

PW = 4.0;
PI = 9.0;

PWI_prev = 1.5;

xW = 10.0;
xI = 2.0;

[vxFused, Pfused, alphaW, alphaI, ...
    PWI_minus, PWI_plus, Phi, condPhi, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0, ...
        xI, PI, 0, ...
        PWI_prev, ...
        true, true, ...
        pZero);


%% Expected correlated weights

expectedDen = ...
    PW + PI - ...
    2 * PWI_prev;

expectedAlphaW = ...
    (PI - PWI_prev) / expectedDen;

expectedAlphaI = ...
    (PW - PWI_prev) / expectedDen;

expectedVxFused = ...
    expectedAlphaW * xW + ...
    expectedAlphaI * xI;

expectedPfused = ...
    expectedAlphaW^2 * PW + ...
    2 * expectedAlphaW * expectedAlphaI * PWI_prev + ...
    expectedAlphaI^2 * PI;


%% Fusion validity

testCase.verifyTrue( ...
    fusionValid, ...
    'TEST6: normal correlated fusion should be valid.');


%% PWI

testCase.verifyEqual( ...
    PWI_minus, ...
    PWI_prev, ...
    'AbsTol', 1e-12);

testCase.verifyEqual( ...
    PWI_plus, ...
    PWI_prev, ...
    'AbsTol', 1e-12);


%% Weight sum

testCase.verifyEqual( ...
    alphaW + alphaI, ...
    1, ...
    'AbsTol', 1e-12, ...
    'TEST6: fusion weights must sum to one.');


%% Individual weights

testCase.verifyEqual( ...
    alphaW, ...
    expectedAlphaW, ...
    'AbsTol', 1e-12);

testCase.verifyEqual( ...
    alphaI, ...
    expectedAlphaI, ...
    'AbsTol', 1e-12);


%% Fused estimate

testCase.verifyEqual( ...
    vxFused, ...
    expectedVxFused, ...
    'AbsTol', 1e-12);


%% Fused covariance

testCase.verifyEqual( ...
    Pfused, ...
    expectedPfused, ...
    'AbsTol', 1e-12);


%% Matrix/conditioning safety

testCase.verifyTrue( ...
    all(isfinite(Phi(:))), ...
    'TEST6: Phi must remain finite.');

testCase.verifyTrue( ...
    isfinite(condPhi), ...
    'TEST6: condPhi must remain finite.');

end


%% ========================================================================
% TEST 7
% Correlated fusion differs from independent fusion
% ========================================================================

function test_correlated_differs_from_independent(testCase)

pZero = make_zero_process_params();

PW = 4.0;
PI = 9.0;

PWI_prev = 2.2;

xW = 12.0;
xI = -3.0;


%% Correlated fusion

[vxCorr, PfusedCorr, alphaWCorr, alphaICorr, ...
    ~, PWI_plus, Phi, ~, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0, ...
        xI, PI, 0, ...
        PWI_prev, ...
        true, true, ...
        pZero);


%% Independent inverse-variance fusion

alphaWInd = ...
    (1 / PW) / ...
    (1 / PW + 1 / PI);

alphaIInd = ...
    (1 / PI) / ...
    (1 / PW + 1 / PI);

vxInd = ...
    alphaWInd * xW + ...
    alphaIInd * xI;

PfusedInd = ...
    alphaWInd^2 * PW + ...
    alphaIInd^2 * PI;


%% Expected correlated solution

expectedDen = ...
    PW + PI - ...
    2 * PWI_prev;

expectedAlphaW = ...
    (PI - PWI_prev) / expectedDen;

expectedAlphaI = ...
    (PW - PWI_prev) / expectedDen;

expectedVx = ...
    expectedAlphaW * xW + ...
    expectedAlphaI * xI;

expectedPfused = ...
    expectedAlphaW^2 * PW + ...
    2 * expectedAlphaW * expectedAlphaI * PWI_prev + ...
    expectedAlphaI^2 * PI;


%% Verify correlated result

testCase.verifyTrue(fusionValid);

testCase.verifyEqual( ...
    alphaWCorr, expectedAlphaW, ...
    'AbsTol', 1e-12);

testCase.verifyEqual( ...
    alphaICorr, expectedAlphaI, ...
    'AbsTol', 1e-12);

testCase.verifyEqual( ...
    vxCorr, expectedVx, ...
    'AbsTol', 1e-12);

testCase.verifyEqual( ...
    PfusedCorr, expectedPfused, ...
    'AbsTol', 1e-12);


%% Must differ from independent fusion

testCase.verifyGreaterThanOrEqual( ...
    abs(vxCorr - vxInd), ...
    1e-3, ...
    ['TEST7: correlated fusion should differ ', ...
     'from independent fusion.']);

testCase.verifyGreaterThanOrEqual( ...
    abs(PfusedCorr - PfusedInd), ...
    1e-3);

testCase.verifyGreaterThanOrEqual( ...
    abs(alphaWCorr - alphaWInd), ...
    1e-3);


%% Numerical checks

testCase.verifyTrue(isfinite(PWI_plus));

testCase.verifyTrue(all(isfinite(Phi(:))));

end


%% ========================================================================
% TEST 8
% Negative weight allowed
% ========================================================================

function test_negative_weight_allowed(testCase)

pZero = make_zero_process_params();

PW = 1.0;
PI = 4.0;

PWI_prev = 1.6;

xW = 3.0;
xI = 10.0;

[vxFused, ~, alphaW, alphaI, ...
    ~, PWI_plus, ~, ~, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0, ...
        xI, PI, 0, ...
        PWI_prev, ...
        true, true, ...
        pZero);


%% Expected correlated solution

expectedDen = ...
    PW + PI - ...
    2 * PWI_prev;

expectedAlphaW = ...
    (PI - PWI_prev) / expectedDen;

expectedAlphaI = ...
    (PW - PWI_prev) / expectedDen;

expectedVx = ...
    expectedAlphaW * xW + ...
    expectedAlphaI * xI;


%% Valid correlated solution

testCase.verifyTrue(fusionValid);


%% Negative / greater-than-one weights are intentionally allowed

testCase.verifyLessThan( ...
    alphaI, ...
    0, ...
    'TEST8: alphaI should be negative.');

testCase.verifyGreaterThan( ...
    alphaW, ...
    1, ...
    'TEST8: alphaW should exceed one.');


%% No update to PWI with zero gains/process noise

testCase.verifyEqual( ...
    PWI_plus, ...
    PWI_prev, ...
    'AbsTol', 1e-12);


%% Weight sum

testCase.verifyEqual( ...
    alphaW + alphaI, ...
    1, ...
    'AbsTol', 1e-12);


%% Fused value

testCase.verifyEqual( ...
    vxFused, ...
    expectedVx, ...
    'AbsTol', 1e-12);


%% Explicitly ensure weights were not clipped

testCase.verifyTrue( ...
    abs(alphaI) > 1e-3 || ...
    abs(alphaW - 1) > 1e-3, ...
    'TEST8: correlated weights appear clipped to [0,1].');

end


%% ========================================================================
% TEST 9
% Single-channel degradation
% ========================================================================

function test_single_channel_degradation(testCase)

pZero = make_zero_process_params();

PW = 2.0;
PI = 1.5;

PWI_prev = 0.05;

xW = 8.0;
xI = -2.0;


%% ------------------------------------------------------------------------
% WSS invalid, IMU valid
% -------------------------------------------------------------------------

[vxFused, Pfused, alphaW, alphaI, ...
    ~, ~, ~, ~, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0.2, ...
        xI, PI, 0.8, ...
        PWI_prev, ...
        false, true, ...
        pZero);

testCase.verifyTrue( ...
    fusionValid, ...
    'TEST9: IMU-only fusion should remain valid.');

testCase.verifyEqual(alphaW, 0, 'AbsTol', 1e-12);

testCase.verifyEqual(alphaI, 1, 'AbsTol', 1e-12);

testCase.verifyEqual(vxFused, xI, 'AbsTol', 1e-12);

testCase.verifyEqual(Pfused, PI, 'AbsTol', 1e-12);


%% ------------------------------------------------------------------------
% WSS valid, IMU invalid
% -------------------------------------------------------------------------

[vxFused, Pfused, alphaW, alphaI, ...
    ~, ~, ~, ~, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0.2, ...
        xI, PI, 0.8, ...
        PWI_prev, ...
        true, false, ...
        pZero);

testCase.verifyTrue( ...
    fusionValid, ...
    'TEST9: WSS-only fusion should remain valid.');

testCase.verifyEqual(alphaW, 1, 'AbsTol', 1e-12);

testCase.verifyEqual(alphaI, 0, 'AbsTol', 1e-12);

testCase.verifyEqual(vxFused, xW, 'AbsTol', 1e-12);

testCase.verifyEqual(Pfused, PW, 'AbsTol', 1e-12);

end


%% ========================================================================
% TEST 10
% Both channels invalid
% ========================================================================

function test_dual_invalid(testCase)

pZero = make_zero_process_params();

PW = 2.0;
PI = 1.5;

PWI_prev = 0.05;

xW = 8.0;
xI = -2.0;

[vxFused, Pfused, alphaW, alphaI, ...
    ~, ~, ~, ~, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0.2, ...
        xI, PI, 0.8, ...
        PWI_prev, ...
        false, false, ...
        pZero);


%% Fusion itself is invalid

testCase.verifyFalse( ...
    fusionValid, ...
    'TEST10: dual-invalid fusion must be invalid.');


%% Top-level estimator will handle fallback later

testCase.verifyTrue( ...
    isnan(vxFused), ...
    'TEST10: vxFused should be NaN when both tracks are invalid.');

testCase.verifyTrue( ...
    isnan(Pfused), ...
    'TEST10: Pfused should be NaN when both tracks are invalid.');


%% Alpha outputs should still be numerically safe

testCase.verifyTrue( ...
    isfinite(alphaW) && isfinite(alphaI), ...
    'TEST10: alpha outputs should remain finite.');

end


%% ========================================================================
% TEST 11
% PWI physical bound
% ========================================================================

function test_pwi_physical_bound(testCase)

pZero = make_zero_process_params();

PW = 1.0;
PI = 4.0;

physicalBound = ...
    sqrt(PW * PI);


%% ------------------------------------------------------------------------
% Positive out-of-bound PWI
% -------------------------------------------------------------------------

PWI_prev = 10.0;

[~, ~, ~, ~, ~, PWI_positive] = ...
    correlated_two_track_fusion( ...
        1, PW, 0, ...
        3, PI, 0, ...
        PWI_prev, ...
        true, true, ...
        pZero);

testCase.verifyLessThanOrEqual( ...
    abs(PWI_positive), ...
    physicalBound + 1e-12, ...
    'TEST11: positive PWI must be clipped to physical bound.');


%% ------------------------------------------------------------------------
% Negative out-of-bound PWI
% -------------------------------------------------------------------------

PWI_prev = -10.0;

[~, ~, ~, ~, ~, PWI_negative] = ...
    correlated_two_track_fusion( ...
        1, PW, 0, ...
        3, PI, 0, ...
        PWI_prev, ...
        true, true, ...
        pZero);

testCase.verifyLessThanOrEqual( ...
    abs(PWI_negative), ...
    physicalBound + 1e-12, ...
    'TEST11: negative PWI must be clipped to physical bound.');


%% Negative sign should be preserved

testCase.verifyEqual( ...
    sign(PWI_negative), ...
    sign(PWI_prev), ...
    'TEST11: negative PWI sign should be preserved.');

end


%% ========================================================================
% TEST 12
% Near-singular Phi behavior
% ========================================================================

function test_phi_near_singular(testCase)

pZero = make_zero_process_params();


%% ------------------------------------------------------------------------
% Near singular, but denominator still above eps_den
% -------------------------------------------------------------------------

PW = 1.0;
PI = 1.0;

PWI_prev = ...
    1.0 - 1e-6;

[vxFused, Pfused, alphaW, alphaI, ...
    ~, PWI_plus, Phi, condPhi, fusionValid] = ...
    correlated_two_track_fusion( ...
        2.0, PW, 0.0, ...
        4.0, PI, 0.0, ...
        PWI_prev, ...
        true, true, ...
        pZero);


%% Condition number should be large but finite

testCase.verifyTrue( ...
    isfinite(condPhi), ...
    'TEST12: condPhi must remain finite.');

testCase.verifyGreaterThan( ...
    condPhi, ...
    1e4, ...
    'TEST12: near-singular Phi should have large condition number.');


%% Correlated path remains active

testCase.verifyTrue( ...
    fusionValid, ...
    'TEST12: near-singular case should remain fused.');

testCase.verifyEqual( ...
    alphaW + alphaI, ...
    1, ...
    'AbsTol', 1e-12, ...
    'TEST12: weights must still sum to one.');


%% Outputs remain finite

testCase.verifyTrue(isfinite(vxFused));

testCase.verifyTrue(isfinite(Pfused));

testCase.verifyTrue(isfinite(PWI_plus));

testCase.verifyTrue(all(isfinite(Phi(:))));


%% ------------------------------------------------------------------------
% Boundary around eps_den protected path
% -------------------------------------------------------------------------

PW = 1.0;
PI = 1.0;

PWI_prev = ...
    1.0 - 5e-13;

[~, Pfused, alphaW, alphaI, ...
    ~, PWI_plus, ~, condPhi, fusionValid] = ...
    correlated_two_track_fusion( ...
        2.0, PW, 0.0, ...
        4.0, PI, 0.0, ...
        PWI_prev, ...
        true, true, ...
        pZero);


%% Protected result should remain finite

testCase.verifyTrue(isfinite(condPhi));

testCase.verifyTrue(fusionValid);

testCase.verifyGreaterThanOrEqual( ...
    condPhi, ...
    1e12, ...
    'TEST12: boundary Phi should be extremely ill-conditioned.');

testCase.verifyTrue( ...
    isfinite(Pfused), ...
    'TEST12: Pfused must not become NaN/Inf.');


%% PWI physical constraint

testCase.verifyLessThanOrEqual( ...
    abs(PWI_plus), ...
    sqrt(PW * PI) + 1e-12);


%% Symmetric case should retain positive weights

testCase.verifyGreaterThan(alphaW, 0);

testCase.verifyGreaterThan(alphaI, 0);

testCase.verifyEqual( ...
    alphaW + alphaI, ...
    1, ...
    'AbsTol', 1e-12);

end


%% ========================================================================
% TEST 13
% Illegal variance inputs
% ========================================================================

function test_illegal_variances_guarded(testCase)

pZero = make_zero_process_params();


%% ------------------------------------------------------------------------
% Illegal PW
% -------------------------------------------------------------------------

badPW = [NaN, Inf, -1.0];

for ii = 1:numel(badPW)

    PW = badPW(ii);

    [vxFused, Pfused, alphaW, alphaI, ...
        ~, PWI_plus, Phi, condPhi, fusionValid] = ...
        correlated_two_track_fusion( ...
            1.0, PW, 0.2, ...
            2.0, 2.0, 0.3, ...
            0.1, ...
            true, true, ...
            pZero);

    testCase.verifyTrue( ...
        fusionValid, ...
        ['TEST13: illegal PW case ', num2str(ii), ...
         ' should be protected.']);

    testCase.verifyTrue( ...
        isfinite(vxFused) && isfinite(Pfused));

    testCase.verifyTrue( ...
        isfinite(alphaW) && isfinite(alphaI));

    testCase.verifyGreaterThanOrEqual( ...
        Phi(1,1), ...
        pZero.P_min);

    testCase.verifyGreaterThanOrEqual( ...
        Pfused, ...
        pZero.Pfused_min - 1e-12);

    testCase.verifyTrue(isfinite(PWI_plus));

    testCase.verifyTrue(isfinite(condPhi));

end


%% ------------------------------------------------------------------------
% Illegal PI
% -------------------------------------------------------------------------

badPI = [NaN, Inf, -1.0];

for ii = 1:numel(badPI)

    PI = badPI(ii);

    [vxFused, Pfused, alphaW, alphaI, ...
        ~, PWI_plus, Phi, condPhi, fusionValid] = ...
        correlated_two_track_fusion( ...
            1.0, 2.0, 0.2, ...
            2.0, PI, 0.3, ...
            0.1, ...
            true, true, ...
            pZero);

    testCase.verifyTrue( ...
        fusionValid, ...
        ['TEST13: illegal PI case ', num2str(ii), ...
         ' should be protected.']);

    testCase.verifyTrue( ...
        isfinite(vxFused) && isfinite(Pfused));

    testCase.verifyTrue( ...
        isfinite(alphaW) && isfinite(alphaI));

    testCase.verifyGreaterThanOrEqual( ...
        Phi(2,2), ...
        pZero.P_min);

    testCase.verifyGreaterThanOrEqual( ...
        Pfused, ...
        pZero.Pfused_min - 1e-12);

    testCase.verifyTrue(isfinite(PWI_plus));

    testCase.verifyTrue(isfinite(condPhi));

end


%% ------------------------------------------------------------------------
% Illegal PWI
% -------------------------------------------------------------------------

badPWI = [NaN, Inf];

for ii = 1:numel(badPWI)

    PWI_prev = badPWI(ii);

    [~, ~, ~, ~, ~, PWI_plus] = ...
        correlated_two_track_fusion( ...
            1.0, 2.0, 0.2, ...
            2.0, 3.0, 0.3, ...
            PWI_prev, ...
            true, true, ...
            pZero);

    testCase.verifyTrue( ...
        isfinite(PWI_plus), ...
        ['TEST13: illegal PWI case ', num2str(ii), ...
         ' should be converted to finite value.']);

    testCase.verifyLessThanOrEqual( ...
        abs(PWI_plus), ...
        sqrt(2.0 * 3.0) + 1e-12, ...
        'TEST13: protected PWI exceeds physical bound.');

end

end


%% ========================================================================
% TEST 14
% Pfused formula
% ========================================================================

function test_pfused_sanity(testCase)

pZero = make_zero_process_params();

PW = 4.0;
PI = 9.0;

PWI_prev = 1.2;

xW = 1.0;
xI = 5.0;

[vxFused, Pfused, alphaW, alphaI, ...
    ~, PWI_plus, Phi, condPhi, fusionValid] = ...
    correlated_two_track_fusion( ...
        xW, PW, 0.35, ...
        xI, PI, 0.15, ...
        PWI_prev, ...
        true, true, ...
        pZero);


%% Expected covariance from returned posterior covariance matrix

expectedPfused = ...
    alphaW^2 * Phi(1,1) + ...
    2 * alphaW * alphaI * PWI_plus + ...
    alphaI^2 * Phi(2,2);


%% Numerical sanity

testCase.verifyTrue( ...
    isfinite(Pfused), ...
    'TEST14: Pfused must be finite.');

testCase.verifyGreaterThanOrEqual( ...
    Pfused, ...
    -1e-12, ...
    'TEST14: Pfused should not be negative.');

testCase.verifyEqual( ...
    Pfused, ...
    expectedPfused, ...
    'AbsTol', 1e-12, ...
    'TEST14: Pfused formula mismatch.');

testCase.verifyTrue( ...
    fusionValid, ...
    'TEST14: normal fusion should be valid.');

testCase.verifyTrue( ...
    isfinite(vxFused));

testCase.verifyTrue( ...
    isfinite(condPhi));

end


%% ========================================================================
% TEST 15
% condPhi behavior
% ========================================================================

function test_condphi_behavior(testCase)

pZero = make_zero_process_params();


%% ------------------------------------------------------------------------
% Normal covariance matrix
% -------------------------------------------------------------------------

PW = 2.0;
PI = 1.5;

PWI_prev = 0.2;

[~, ~, ~, ~, ~, ~, ~, ...
    condPhiNormal, fusionValidNormal] = ...
    correlated_two_track_fusion( ...
        1.0, PW, 0.3, ...
        2.0, PI, 0.2, ...
        PWI_prev, ...
        true, true, ...
        pZero);

testCase.verifyTrue( ...
    isfinite(condPhiNormal));

testCase.verifyLessThan( ...
    condPhiNormal, ...
    1e4, ...
    'TEST15: normal Phi should not be severely ill-conditioned.');

testCase.verifyTrue( ...
    fusionValidNormal);


%% ------------------------------------------------------------------------
% More highly correlated case
% -------------------------------------------------------------------------

PW = 1.0;
PI = 1.0;

PWI_prev = ...
    1.0 - 1e-5;

[~, ~, alphaW, alphaI, ~, ~, ~, ...
    condPhiSing, fusionValidSing] = ...
    correlated_two_track_fusion( ...
        1.0, PW, 0.1, ...
        2.0, PI, 0.1, ...
        PWI_prev, ...
        true, true, ...
        pZero);

testCase.verifyTrue( ...
    isfinite(condPhiSing));

testCase.verifyGreaterThan( ...
    condPhiSing, ...
    condPhiNormal, ...
    ['TEST15: stronger correlation should ', ...
     'increase condPhi.']);

testCase.verifyEqual( ...
    alphaW + alphaI, ...
    1, ...
    'AbsTol', 1e-12, ...
    ['TEST15: correlated fusion weights ', ...
     'should sum to one.']);

testCase.verifyTrue( ...
    fusionValidSing);

end


%% ========================================================================
% TEST 16
% Local scalar KF + correlated fusion
% ========================================================================

function test_local_kf_plus_correlated_fusion(testCase)

pDefault = estimator_default_params();

pFuse = make_zero_process_params();

pFuse.QW = pDefault.QW;
pFuse.QI = pDefault.QI;


%% Explicit numerical guard for local scalar KF

pLocal = struct( ...
    'denomEps', 1e-12);


%% ------------------------------------------------------------------------
% WSS local KF
% -------------------------------------------------------------------------

xWPrev = 0.5;
PWPrev = 0.2;

Rw = 0.4;

zW = 1.8;

[xWPlus, PWPlus, ~, ~, KW] = ...
    local_scalar_kf_step( ...
        xWPrev, ...
        PWPrev, ...
        zW, ...
        Rw, ...
        pDefault.QW, ...
        true, ...
        pLocal);


%% ------------------------------------------------------------------------
% IMU local KF
% -------------------------------------------------------------------------

xIPrev = -0.2;
PIPrev = 0.3;

RI = 0.6;

zI = 1.1;

[xIPlus, PIPlus, ~, ~, KI] = ...
    local_scalar_kf_step( ...
        xIPrev, ...
        PIPrev, ...
        zI, ...
        RI, ...
        pDefault.QI, ...
        true, ...
        pLocal);


%% ------------------------------------------------------------------------
% Correlated two-track fusion
% -------------------------------------------------------------------------

[vxFused, Pfused, alphaW, alphaI, ...
    PWI_minus, PWI_plus, Phi, ...
    condPhi, fusionValid] = ...
    correlated_two_track_fusion( ...
        xWPlus, ...
        PWPlus, ...
        KW, ...
        xIPlus, ...
        PIPlus, ...
        KI, ...
        pDefault.PWI0, ...
        true, ...
        true, ...
        pFuse);


%% ------------------------------------------------------------------------
% Expected PWI prediction/update
% -------------------------------------------------------------------------

expectedPwiMinus = ...
    pDefault.PWI0 + ...
    (pFuse.QW + pFuse.QI) / 2;

expectedPwiPlus = ...
    (1 - KW) * ...
    expectedPwiMinus * ...
    (1 - KI);


%% ------------------------------------------------------------------------
% Expected correlated weights
% -------------------------------------------------------------------------

expectedDen = ...
    PWPlus + ...
    PIPlus - ...
    2 * expectedPwiPlus;

expectedAlphaW = ...
    (PIPlus - expectedPwiPlus) / ...
    expectedDen;

expectedAlphaI = ...
    (PWPlus - expectedPwiPlus) / ...
    expectedDen;


%% Explicit normalization used by fusion implementation

weightSum = ...
    expectedAlphaW + ...
    expectedAlphaI;

expectedAlphaW = ...
    expectedAlphaW / weightSum;

expectedAlphaI = ...
    expectedAlphaI / weightSum;


%% Expected fused state

expectedVxFused = ...
    expectedAlphaW * xWPlus + ...
    expectedAlphaI * xIPlus;


%% ------------------------------------------------------------------------
% Verify composition
% -------------------------------------------------------------------------

testCase.verifyTrue( ...
    fusionValid, ...
    'TEST16: composed local-KF/fusion path should be valid.');


%% State result

testCase.verifyEqual( ...
    vxFused, ...
    expectedVxFused, ...
    'AbsTol', 1e-12, ...
    'TEST16: composed fused velocity mismatch.');


%% PWI prediction

testCase.verifyEqual( ...
    PWI_minus, ...
    expectedPwiMinus, ...
    'AbsTol', 1e-12, ...
    'TEST16: composed PWI_minus mismatch.');


%% PWI posterior

testCase.verifyEqual( ...
    PWI_plus, ...
    expectedPwiPlus, ...
    'AbsTol', 1e-12, ...
    'TEST16: composed PWI_plus mismatch.');


%% Fusion weight sum

testCase.verifyEqual( ...
    alphaW + alphaI, ...
    1, ...
    'AbsTol', 1e-12);


%% Individual fusion weights

testCase.verifyEqual( ...
    alphaW, ...
    expectedAlphaW, ...
    'AbsTol', 1e-12);

testCase.verifyEqual( ...
    alphaI, ...
    expectedAlphaI, ...
    'AbsTol', 1e-12);


%% All core outputs finite

testCase.verifyTrue( ...
    isfinite(vxFused));

testCase.verifyTrue( ...
    isfinite(Pfused) && Pfused >= 0);

testCase.verifyTrue( ...
    isfinite(xWPlus) && isfinite(xIPlus));

testCase.verifyTrue( ...
    all(isfinite(Phi(:))));

testCase.verifyTrue( ...
    isfinite(condPhi));

end


%% ========================================================================
% Helper: standard fusion parameters
% ========================================================================

function p = make_fusion_params()

pDefault = estimator_default_params();

p = struct( ...
    'QW', pDefault.QW, ...
    'QI', pDefault.QI, ...
    'P_min', 1e-12, ...
    'Pfused_min', 1e-12, ...
    'eps_den', 1e-12, ...
    'pwi_epsilon', 1e-12);

end


%% ========================================================================
% Helper: zero process-noise fusion parameters
% ========================================================================

function p = make_zero_process_params()

p = make_fusion_params();

p.QW = 0;
p.QI = 0;

end