function [analysis,dataset] = analyze_vy_fixed_fusion_v2_5g2_remaining_calibration(varargin)
%ANALYZE_VY_FIXED_FUSION_V2_5G2_REMAINING_CALIBRATION No-simulation analyzer.
% (report, registryRow) performs in-memory integrity analysis before the
% immutable MAT save. (runId) reads that MAT, emits CSV evidence, and never
% writes the MAT.

root=fileparts(fileparts(mfilename('fullpath')));
registryFile=fullfile(root,'results','vy_fixed_fusion_v2_5f_run_registry.csv');
remediationFile=fullfile(root,'results','vy_fixed_fusion_v2_5g2_C02_presim_remediation_registry.csv');
registry=readtable(registryFile,'TextType','string','VariableNamingRule','preserve','Delimiter',',');
allowed=["FWCAL_C02";"FWCAL_C03";"FWCAL_C04";"FWCAL_C05"];

if nargin==2
    report=varargin{1};reg=varargin{2};runId=string(report.runId);
    assert(any(runId==allowed)&&height(reg)==1&&reg.run_id==runId,'V25G2:Analyzer','Run/registry mismatch.');
    [analysis,dataset]=analyze_vy_fixed_fusion_v2_5g1d_C01R1(report,reg);
    analysis.stage='V2.5-G2';analysis.runId=char(runId);
    analysis.performanceBasedSelectionPerformed=false;analysis.weightSelectionPerformed=false;
    analysis.alpha_D='UNSELECTED';analysis.alpha_K='UNSELECTED';analysis.alpha_F='UNSELECTED';
    vals=cell2mat(struct2cell(analysis.gates));analysis.gateCount=numel(vals);
    analysis.gatesTrue=sum(vals);analysis.eligibleForCalibration=all(vals);analysis.passed=all(vals);
    dataset.run_id=char(runId);dataset.role='CALIBRATION_ONLY';dataset.replaces_run_id='NONE';
    dataset.replacement_generation=0;dataset.preregisteredManeuver=table2struct(reg);
    dataset.formalCalibrationEligibility=analysis.eligibleForCalibration;
    dataset.alphaStatus='UNSELECTED';dataset.P_FW_Generated=false;
    return
elseif nargin~=1
    error('V25G2:Usage','Use (report,registryRow) or one run ID.');
end

runId=upper(string(varargin{1}));
assert(isscalar(runId)&&any(runId==allowed),'V25G2:RunId','Run ID must be FWCAL_C02..C05.');
reg=registry(registry.run_id==runId,:);assert(height(reg)==1,'V25G2:Registry','Run row missing.');
resultFile=formal_result_path(root,reg,remediationFile);
if runId=="FWCAL_C02"
    oldFailure=fullfile(root,strrep(char(reg.result_path_reserved),'/',filesep));
    assert(isfile(oldFailure)&&strcmpi(sha256(oldFailure), ...
        'F78B76F1D63CB465B98401BF033E842A6BC440D88237F625AD11E8FF1D9A484F'), ...
        'V25G2:Evidence','Preserved C02 pre-sim failure evidence changed.');
    assert(~strcmpi(oldFailure,resultFile),'V25G2:Evidence', ...
        'Analyzer must exclude the pre-sim failure MAT from formal calibration.');
end
assert(isfile(resultFile),'V25G2:Evidence','Immutable runtime MAT is missing.');
hashBefore=sha256(resultFile);info=dir(resultFile);
S=load(resultFile,'report','dataset');report=S.report;dataset=S.dataset;analysis=report.analysis;
assert(strcmp(string(report.runId),runId)&&report.simCalled&&report.simCallCount==1&& ...
    report.simulationCompleted&&report.carSimRun&&analysis.passed&& ...
    dataset.formalCalibrationEligibility,'V25G2:Evidence','Runtime evidence is incomplete/ineligible.');

acqFile=fullfile(root,'results',sprintf('vy_fixed_fusion_v2_5g2_%s_acquisition_record.csv',runId));
gateFile=fullfile(root,'results',sprintf('vy_fixed_fusion_v2_5g2_%s_integrity_gates.csv',runId));
write_acquisition(acqFile,report,analysis,reg,resultFile,hashBefore,info);
write_gates(gateFile,report,analysis,reg,resultFile,hashBefore);
hashAfter=sha256(resultFile);infoAfter=dir(resultFile);
assert(strcmpi(hashBefore,hashAfter)&&info.bytes==infoAfter.bytes&&info.datenum==infoAfter.datenum, ...
    'V25G2:Immutability','Runtime MAT changed during analyzer-only evidence generation.');

fprintf(['G2_POST_ANALYSIS|id=%s|gates=%d/%d|N=[%d %d %d %d]|t=[%.17g %.17g]|' ...
    'dt=[%.17g %.17g %.17g]|timeDiff=[%.17g %.17g %.17g]|Ay=%d/%d|' ...
    'Kinputs=[%d %d %d]|feedback=%d|replayD=[%.17g %.17g %.17g]|' ...
    'replayK=[%.17g %.17g %.17g]|replayF=[%.17g %.17g %.17g]|fusion=%.17g|' ...
    'truth=%s|truthN=[%d %d]|evalN=%d|steer=[%.17g %.17g %.17g %.17g]|' ...
    'Vx=[%.17g %.17g %.17g]|hash=%s|bytes=%d|eligible=%d|sim=0\n'], ...
    report.runId,analysis.gatesTrue,analysis.gateCount, ...
    analysis.timestamps.D.sampleCount,analysis.timestamps.K.sampleCount, ...
    analysis.timestamps.F.sampleCount,analysis.timestamps.fusion.sampleCount, ...
    analysis.timestamps.fusion.tStart,analysis.timestamps.fusion.tEnd, ...
    analysis.timestamps.fusion.dtMin,analysis.timestamps.fusion.dtMean,analysis.timestamps.fusion.dtMax, ...
    analysis.timestamps.DvsKMaxDiff,analysis.timestamps.DvsFMaxDiff,analysis.timestamps.DvsFusionMaxDiff, ...
    analysis.D.AyUpdate.count,analysis.D.AyUpdate.expectedCount, ...
    analysis.K.processInputs.AxCount,analysis.K.processInputs.AyCount,analysis.K.processInputs.AVzCount, ...
    analysis.F.feedbackAppliedOneCount,analysis.DReplay.maxStateDiff,analysis.DReplay.maxPDiff, ...
    analysis.DReplay.maxDiagDiff,analysis.KReplay.maxStateDiff,analysis.KReplay.maxPDiff, ...
    analysis.KReplay.maxDiagDiff,analysis.FReplay.maxVyDiff,analysis.FReplay.maxPDiff, ...
    analysis.FReplay.maxDiagDiff,analysis.fusionReplay.maxAbsFusionReplayDiff, ...
    analysis.truth.VyAlignment.mode,analysis.truth.VyAlignment.truthOriginalSampleCount, ...
    analysis.truth.VyAlignment.truthAlignedSampleCount,analysis.evaluation.sampleCount, ...
    analysis.steering.commandMaxAbs,analysis.steering.frequencyHz, ...
    analysis.steering.RLMaxAbsRad,analysis.steering.RRMaxAbsRad, ...
    analysis.truth.VxStats.min,analysis.truth.VxStats.mean,analysis.truth.VxStats.max, ...
    hashAfter,info.bytes,analysis.eligibleForCalibration);
fprintf(['G2_COVARIANCE|id=%s|D_asym=%.17g|D_mineig=%.17g|' ...
    'K_asym=%.17g|K_mineig=%.17g|F_minP=%.17g|F_finite=%d\n'],report.runId, ...
    analysis.D.covariance.maxAsymmetry,analysis.D.covariance.minimumEigenvalue, ...
    analysis.K.covariance.maxAsymmetry,analysis.K.covariance.minimumEigenvalue, ...
    analysis.F.minimumP,analysis.F.PFinite);
fprintf('%s ACQUISITION PASS\n',report.runId);
end

function write_acquisition(file,report,a,reg,resultFile,resultHash,info)
T=table(string(report.runId),"CALIBRATION_ONLY",string(report.registryRowIndex),"NONE", ...
    string(reg.planned_steer_amplitude_rad),string(report.runCard.commandedAmplitudeRad), ...
    string(reg.planned_steer_frequency_Hz),string(report.runCard.commandedFrequencyHz), ...
    string(reg.planned_duration_s),string(report.stopTimeActualS), ...
    string(reg.planned_sample_rate_Hz),string(1/a.timestamps.fusion.dtMean), ...
    "CONSUMED","YES",string(report.simCallCount),"YES","EXIT_0_RUNTIME_AND_POST_ANALYSIS_OK", ...
    "PASS","PASS",string(report.carSim.solverActual),string(report.carSim.mexActual), ...
    string(report.matlabPrefdir.activeValue),empty_as_unset(report.matlabPrefdir.environmentValue), ...
    bool_text(report.matlabPrefdir.userEnvironmentUnset,"UNSET","SET"), ...
    bool_text(report.matlabPrefdir.machineEnvironmentUnset,"UNSET","SET"), ...
    string(report.postQuarantine.classification),string(report.postQuarantine.q04OriginalPath), ...
    string(report.postQuarantine.q04OriginalSHA256),string(report.postQuarantine.activeQ04Path), ...
    string(report.postQuarantine.activeQ04SHA256),string(report.postQuarantine.set2OriginalPath), ...
    string(report.postQuarantine.set2OriginalSHA256), ...
    bool_text(report.postQuarantine.activeSet2SourceAbsent,"YES","NO"), ...
    bool_text(~report.postQuarantine.restorePerformed&&~report.postQuarantine.additionalQuarantinePerformed,"NO","YES"), ...
    bool_text(report.immediatePreSim.postLoadSet2.exists,"YES","NO"), ...
    string(report.immediatePreSim.postLoadSet2.sha256), ...
    string(report.immediatePreSim.postLoadSet2.bytes), ...
    string(report.immediatePreSim.postLoadSet2.creationTimeUTC), ...
    string(report.immediatePreSim.postLoadSet2.mtimeUTC), ...
    bool_text(report.immediatePreSim.postLoadSet2.provenanceAccepted,"PASS","FAIL"), ...
    string(resultFile),string(resultHash), ...
    string(info.bytes),string(info.date),string(a.timestamps.D.sampleCount), ...
    string(a.timestamps.K.sampleCount),string(a.timestamps.F.sampleCount), ...
    string(a.timestamps.fusion.sampleCount),"EXACT_SAME_INDEX_MAX_DIFF_0", ...
    string(a.D.AyUpdate.count),string(a.K.processInputs.AxCount), ...
    string(a.K.processInputs.AyCount),string(a.K.processInputs.AVzCount), ...
    string(a.F.feedbackAppliedOneCount),replay_text(a.DReplay),replay_text(a.KReplay), ...
    replay_text(a.FReplay),"PASS_MAX_DIFF_"+string(a.fusionReplay.maxAbsFusionReplayDiff), ...
    "YES",string(a.truth.VyAlignment.mode)+"_PASS", ...
    "FULL_[0_"+string(report.runCard.plannedDurationS)+"]_"+string(a.evaluation.sampleCount)+"_SAMPLES_PASS", ...
    "ELIGIBLE_CALIBRATION_DATA", ...
    "NO_PERFORMANCE_SELECTION|NO_ALPHA|TEST_ONLY_FUSION_WEIGHTS|TRUE_VY_OFFLINE_ONLY|F_STANDALONE", ...
    'VariableNames',{'run_id','role','original_registry_row_index','replaces_run_id', ...
    'planned_amplitude_rad','actual_amplitude_rad','planned_frequency_hz','actual_frequency_hz', ...
    'planned_duration_s','actual_duration_s','planned_rate_hz','actual_rate_hz', ...
    'runtime_authorization_status','sim_called','sim_call_count','runtime_completed', ...
    'MATLAB_exit_runtime_status','CarSim_initialization_status','CarSim_completion_status', ...
    'solver_path','vs_sf_path','active_prefdir','MATLAB_PREFDIR_process','MATLAB_PREFDIR_user', ...
    'MATLAB_PREFDIR_machine','post_quarantine_classification','R3_Q04_quarantine_path', ...
    'R3_Q04_quarantine_sha256','active_regenerated_Q04_path','active_regenerated_Q04_sha256', ...
    'R4_SET2_quarantine_path','R4_SET2_quarantine_sha256','active_SET2_absent_at_runner_entry', ...
    'quarantine_restore_or_additional_quarantine','postload_SET2_exists','postload_SET2_sha256', ...
    'postload_SET2_bytes','postload_SET2_ctime_utc','postload_SET2_mtime_utc', ...
    'postload_SET2_provenance','result_path','result_sha256','result_bytes', ...
    'result_mtime','sample_count_D','sample_count_K','sample_count_F','sample_count_fusion', ...
    'timestamp_alignment_status','D_Ay_update_count','K_Ax_hit_count','K_Ay_hit_count', ...
    'K_AVz_hit_count','F_feedbackApplied_count','D_replay_status','K_replay_status', ...
    'F_replay_status','fusion_replay_status','truth_available','truth_alignment_status', ...
    'evaluation_window_compliance','formal_calibration_eligibility','notes'});
writetable(T,file);
end

function write_gates(file,r,a,reg,resultFile,resultHash)
desc=["run ID exact";"role exact";"original registry row/order recorded"; ...
    "preregistered amplitude exact";"preregistered frequency exact";"preregistered duration exact"; ...
    "waveform exact";"front steering policy exact";"rear steering policy exact"; ...
    "speed scope respected";"result path absent pre-run";"prelaunch live MATLAB count"; ...
    "MATLAB_PREFDIR process policy";"active PREFDIR exact"; ...
    "MATLAB_PREFDIR user policy";"MATLAB_PREFDIR machine policy"; ...
    "post-quarantine classification";"R3 Q04 quarantine hash"; ...
    "active regenerated Q04 exists";"R4 SET-2 quarantine hash"; ...
    "active SET-2 absent at runner entry";"no restore or additional quarantine"; ...
    "post-load SET-2 provenance"; ...
    "cwd exact model directory"; ...
    "active simfile exact";"D drive solver exact";"D drive vs_sf exact";"G request"; ...
    "target hash exact and unchanged";"all frozen hashes unchanged";"history and registry unchanged"; ...
    "sim called exactly once";"runtime completed";"D sample count";"K sample count"; ...
    "F sample count";"fusion sample count";"D versus K timestamp max diff"; ...
    "D versus F timestamp max diff";"D versus fusion timestamp max diff";"mean dt"; ...
    "D Ay scheduler semantics";"K Ax Ay AVz semantics";"F feedbackApplied count"; ...
    "D covariance integrity";"K covariance integrity";"F P integrity";"D frozen replay"; ...
    "K frozen replay";"F frozen replay";"fusion exact replay";"true Vy available and finite"; ...
    "truth alignment";"evaluation window";"no online true Vy path";"no P_FW"; ...
    "no covariance fusion";"no feedback closure";"no alpha calculation"; ...
    "runtime MAT hash registered";"formal calibration eligibility"];
expected=[string(r.runId);"CALIBRATION_ONLY";string(r.registryRowIndex); ...
    string(reg.planned_steer_amplitude_rad)+" rad";string(reg.planned_steer_frequency_Hz)+" Hz"; ...
    string(reg.planned_duration_s)+" s";"SINE_FRONT_EQUAL_REAR_ZERO";"FL_FR_SAME_PHASE"; ...
    "RL_RR_ZERO";"CURRENT_CARSIM_20_MPS_CLASS_NOT_RUNNER_PARAMETERIZED";"absent";"0"; ...
    "UNSET";"R4 fresh default";"User MATLAB_PREFDIR UNSET";"Machine MATLAB_PREFDIR UNSET"; ...
    "POST_QUARANTINE_STARTUP_STABILITY_CONFIRMED";"95464B5E...E65B";"active regenerated Q04 exists"; ...
    "30677E24...C996E";"active SET-2 source absent";"no restore/additional quarantine"; ...
    "absent or current-session regenerated"; ...
    "D:\\UsersData\\桌面\\two\\model";"model/simfile.sim"; ...
    "D: carsim_64.dll";"matching D: vs_sf";"NO";r.runCard.targetSHA256;"unchanged";"unchanged"; ...
    "1";"normal completion";string(a.timestamps.D.sampleCount);string(a.timestamps.K.sampleCount); ...
    string(a.timestamps.F.sampleCount);string(a.timestamps.fusion.sampleCount);"0";"0";"0";"0.01 s"; ...
    string(a.D.AyUpdate.expectedCount);string(a.timestamps.K.sampleCount)+" each";"0"; ...
    "finite symmetric positive definite";"finite symmetric positive definite";"finite nonnegative"; ...
    "<=1e-12";"<=1e-12";"<=1e-12";"<=1e-12";"YES finite"; ...
    string(reg.truth_alignment_rule);string(reg.evaluation_window_s);"NO online use";"NO"; ...
    "NO";"F standalone";"UNSELECTED";"immutable SHA-256";"ELIGIBLE"];
actual=[string(r.runId);string(r.role);string(r.registryRowIndex); ...
    string(r.runCard.commandedAmplitudeRad)+" rad";string(r.runCard.commandedFrequencyHz)+" Hz"; ...
    string(r.stopTimeActualS)+" s";string(r.runCard.waveform);string(r.runCard.frontSteeringPolicy); ...
    string(r.runCard.rearSteeringPolicy);"Vx min/mean/max="+string(a.truth.VxStats.min)+"/"+ ...
    string(a.truth.VxStats.mean)+"/"+string(a.truth.VxStats.max);string(r.resultPathPreRunAbsent);"0"; ...
    empty_as_unset(r.matlabPrefdir.environmentValue);string(r.matlabPrefdir.activeValue); ...
    bool_text(r.matlabPrefdir.userEnvironmentUnset,"UNSET","SET"); ...
    bool_text(r.matlabPrefdir.machineEnvironmentUnset,"UNSET","SET"); ...
    string(r.postQuarantine.classification);string(r.postQuarantine.q04OriginalSHA256); ...
    bool_text(r.postQuarantine.activeQ04Exists,"active regenerated Q04 exists","missing"); ...
    string(r.postQuarantine.set2OriginalSHA256); ...
    bool_text(r.postQuarantine.activeSet2SourceAbsent,"active SET-2 source absent","EXISTS"); ...
    bool_text(~r.postQuarantine.restorePerformed&&~r.postQuarantine.additionalQuarantinePerformed, ...
    "no restore/additional quarantine","state changed"); ...
    bool_text(r.immediatePreSim.postLoadSet2.provenanceAccepted, ...
    "absent or current-session regenerated","FAIL"); ...
    string(r.carSim.pwd);string(r.carSim.activeSimfile);string(r.carSim.solverActual); ...
    string(r.carSim.mexActual);bool_text(~r.carSim.gRequestBefore&&~r.carSim.gRequestConsole,"NO","YES"); ...
    string(r.targetHashAfter);bool_text(r.allFrozenHashesUnchanged,"unchanged","mismatch"); ...
    bool_text(r.historyUnchanged,"unchanged","mismatch");string(r.simCallCount); ...
    bool_text(r.simulationCompleted&&r.carSimRun,"normal completion","failed"); ...
    string(a.timestamps.D.sampleCount);string(a.timestamps.K.sampleCount);string(a.timestamps.F.sampleCount); ...
    string(a.timestamps.fusion.sampleCount);string(a.timestamps.DvsKMaxDiff); ...
    string(a.timestamps.DvsFMaxDiff);string(a.timestamps.DvsFusionMaxDiff); ...
    string(a.timestamps.fusion.dtMean)+" s";string(a.D.AyUpdate.count); ...
    string(a.K.processInputs.AxCount)+"/"+string(a.K.processInputs.AyCount)+"/"+ ...
    string(a.K.processInputs.AVzCount);string(a.F.feedbackAppliedOneCount); ...
    "asym="+string(a.D.covariance.maxAsymmetry)+" minEig="+string(a.D.covariance.minimumEigenvalue); ...
    "asym="+string(a.K.covariance.maxAsymmetry)+" minEig="+string(a.K.covariance.minimumEigenvalue); ...
    "minP="+string(a.F.minimumP);replay_text(a.DReplay);replay_text(a.KReplay);replay_text(a.FReplay); ...
    string(a.fusionReplay.maxAbsFusionReplayDiff);bool_text(a.truth.pass,"YES finite","FAIL"); ...
    string(a.truth.VyAlignment.mode);"["+string(a.evaluation.startTime)+" "+ ...
    string(a.evaluation.endTime)+"] N="+string(a.evaluation.sampleCount); ...
    bool_text(r.static.noOnlineTrueVy,"NO online use","FAIL");bool_text(r.static.noP_FW,"NO","YES"); ...
    bool_text(r.static.noCovarianceFusion,"NO","YES");bool_text(r.static.noFeedbackClosure,"F standalone","FAIL"); ...
    "alpha_D/K/F UNSELECTED";string(resultHash); ...
    bool_text(a.eligibleForCalibration,"ELIGIBLE","NOT_ELIGIBLE")];
pass=[string(r.runId)==reg.run_id;r.role=="CALIBRATION_ONLY";r.registryRowIndex>0; ...
    r.runCard.commandedAmplitudeRad==asnum(reg.planned_steer_amplitude_rad); ...
    r.runCard.commandedFrequencyHz==asnum(reg.planned_steer_frequency_Hz); ...
    r.stopTimeActualS==asnum(reg.planned_duration_s);a.steering.pass;a.steering.FLFRMaxDiffRad<=1e-12; ...
    a.steering.RLMaxAbsRad<=1e-12&&a.steering.RRMaxAbsRad<=1e-12; ...
    a.truth.VxStats.min>19&&a.truth.VxStats.max<=21;r.resultPathPreRunAbsent;true; ...
    r.matlabPrefdir.environmentUnset;r.matlabPrefdir.activeExact; ...
    r.matlabPrefdir.userEnvironmentUnset;r.matlabPrefdir.machineEnvironmentUnset; ...
    r.postQuarantine.classification=="POST_QUARANTINE_STARTUP_STABILITY_CONFIRMED"; ...
    strcmpi(r.postQuarantine.q04OriginalSHA256,'95464B5EEE5B786BB6A910F2765B15DB11A79644DC0F7F12BC6724149E8AE65B'); ...
    r.postQuarantine.activeQ04Exists; ...
    strcmpi(r.postQuarantine.set2OriginalSHA256,'30677E244B75BB3469E1937848E92D4F1C850988B453AFB93F4510DBD59C996E'); ...
    r.postQuarantine.activeSet2SourceAbsent; ...
    ~r.postQuarantine.restorePerformed&&~r.postQuarantine.additionalQuarantinePerformed; ...
    r.immediatePreSim.postLoadSet2.provenanceAccepted; ...
    strcmpi(r.carSim.pwd,fileparts(r.runCard.targetPath)); ...
    strcmpi(r.carSim.activeSimfile,fullfile(fileparts(r.runCard.targetPath),'simfile.sim')); ...
    strcmpi(r.carSim.solverActual,r.carSim.solverExpected);strcmpi(r.carSim.mexActual,r.carSim.mexExpected); ...
    ~r.carSim.gRequestBefore&&~r.carSim.gRequestConsole;r.targetHashUnchanged; ...
    r.allFrozenHashesUnchanged;r.historyUnchanged;r.simCallCount==1; ...
    r.simulationCompleted&&r.carSimRun;a.timestamps.D.pass;a.timestamps.K.pass; ...
    a.timestamps.F.pass;a.timestamps.fusion.pass;a.timestamps.DvsKMaxDiff==0; ...
    a.timestamps.DvsFMaxDiff==0;a.timestamps.DvsFusionMaxDiff==0; ...
    abs(a.timestamps.fusion.dtMean-0.01)<=1e-12;a.D.AyUpdate.pass;a.K.processInputs.pass; ...
    a.F.feedbackAppliedOneCount==0;a.D.covariance.valid;a.K.covariance.valid; ...
    a.F.PFinite&&a.F.PNonnegative;a.DReplay.pass;a.KReplay.pass;a.FReplay.pass; ...
    a.fusionReplay.pass;a.truth.pass;a.truth.VyAlignment.pass;a.evaluation.pass; ...
    r.static.noOnlineTrueVy;r.static.noP_FW;r.static.noCovarianceFusion; ...
    r.static.noFeedbackClosure;~a.weightSelectionPerformed;strlength(string(resultHash))==64; ...
    a.eligibleForCalibration];
assert(numel(desc)==numel(expected)&&numel(desc)==numel(actual)&&numel(desc)==numel(pass));
gateId="G"+compose('%02d',(1:numel(desc)).');passFail=repmat("FAIL",numel(desc),1);passFail(pass)="PASS";
T=table(gateId,desc,expected,actual,passFail,'VariableNames', ...
    {'gate_id','description','expected','actual','PASS_FAIL'});writetable(T,file);
assert(all(pass),'V25G2:Gates','Post-acquisition integrity gate failed.');
end

function s=replay_text(x)
if isfield(x,'maxStateDiff'),s="PASS_MAX_DIFF_"+string(x.maxStateDiff)+"_"+string(x.maxPDiff)+"_"+string(x.maxDiagDiff);
elseif isfield(x,'maxVyDiff'),s="PASS_MAX_DIFF_"+string(x.maxVyDiff)+"_"+string(x.maxPDiff)+"_"+string(x.maxDiagDiff);
else,s="UNKNOWN";end
end
function s=empty_as_unset(x),if isempty(x),s="UNSET";else,s=string(x);end,end
function s=bool_text(tf,a,b),if tf,s=string(a);else,s=string(b);end,end
function v=asnum(x),if isnumeric(x),v=double(x);else,v=str2double(string(x));end;assert(isscalar(v));end
function file=formal_result_path(root,reg,remediationFile)
if string(reg.run_id)=="FWCAL_C02"
    rem=readtable(remediationFile,'TextType','string','VariableNamingRule','preserve','Delimiter',',');
    rem=rem(rem.run_id=="FWCAL_C02",:);assert(height(rem)==1,'V25G2:Remediation','C02 remediation row missing.');
    file=fullfile(root,strrep(char(rem.new_formal_runtime_path),'/',filesep));
else
    file=fullfile(root,strrep(char(reg.result_path_reserved),'/',filesep));
end
end
function h=sha256(file),d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());while ds.read()~=-1,end;b=typecast(d.digest(),'uint8');h=upper(reshape(dec2hex(b,2).',1,[]));clear c,end
