function analysis = analyze_vy_lifesig_fusion_v2_8a3_long_low_yaw()
%ANALYZE... Offline D/K long-low-yaw analysis. Never calls sim().
root=fileparts(fileparts(mfilename('fullpath')));
runtimeFile=fullfile(root,'results','vy_lifesig_v2_8a3_long_low_yaw_runtime.mat');
resultFile=fullfile(root,'results','vy_lifesig_v2_8a3_long_low_yaw_analysis.mat');
csvFile=fullfile(root,'results','vy_lifesig_v2_8a3_long_low_yaw_summary.csv');
S=load(runtimeFile,'runtime');r=S.runtime;
assert(r.simInvocationCount==1&&strcmp(r.authorization,'CONSUMED')&& ...
    r.simulationCompleted&&r.logsSaved&&r.durationComplete&&r.hashesUnchanged, ...
    'V28A3:RuntimeIneligible','A3 runtime evidence is not eligible.');

t=scalar_log(r.raw.rel_common_time_100hz_log);steer=scalar_log(r.raw.steer_cmd_rad);
yaw=scalar_log(r.raw.long_low_yaw_r_log);truth=scalar_log(r.raw.rel_vy_true_100hz_log);
vyD=scalar_log(r.raw.fusion_vy_d_log);vyK=scalar_log(r.raw.fusion_vy_k_log);
eD=scalar_log(r.raw.long_low_yaw_d_error_log);eK=scalar_log(r.raw.long_low_yaw_k_error_log);
N=numel(t);vectors={steer,yaw,truth,vyD,vyK,eD,eK};
aligned=all(cellfun(@(x)numel(x)==N,vectors));finite=all(isfinite(t))&& ...
    all(cellfun(@(x)all(isfinite(x)),vectors));dt=diff(t);
timeOK=N==2201&&abs(t(1))<1e-12&&abs(t(end)-22)<1e-9&&max(abs(dt-0.01))<1e-9;
replayD=max(abs(eD-(vyD-truth)));replayK=max(abs(eK-(vyK-truth)));
steerZero=max(abs(steer(t>=4.5)))<=1e-14;

thresholds=[0.005 0.01 0.02];after=t>=4.5;
parts=repmat(struct('threshold',0,'sampleCount',0,'fraction',0,'totalDuration',0, ...
    'longestDuration',0,'longestStart',NaN,'longestEnd',NaN),3,1);
for i=1:3
    mask=after&abs(yaw)<thresholds(i);[total,longest,s,e]=durations(t,mask);
    parts(i)=struct('threshold',thresholds(i),'sampleCount',sum(mask), ...
        'fraction',sum(mask)/sum(after),'totalDuration',total, ...
        'longestDuration',longest,'longestStart',s,'longestEnd',e);
end
primary=parts(2);mask=after&abs(yaw)<0.01;
[~,~,s,e]=durations(t,mask);window=mask&t>=s-1e-12&t<=e+1e-12;

analysis=struct();analysis.stage='V2.8-A3';analysis.sampleCount=N;
analysis.time=struct('start',t(1),'end',t(end),'dtMin',min(dt),'dtMean',mean(dt),'dtMax',max(dt));
analysis.aligned=aligned;analysis.finite=finite;analysis.timeOK=timeOK;
analysis.steerAfter4p5ExactZero=steerZero;analysis.errorReplay=struct('D',replayD,'K',replayK);
analysis.partitions=parts;analysis.primaryWindow=struct('threshold',0.01,'start',s, ...
    'end',e,'duration',primary.longestDuration,'sampleCount',sum(window));
analysis.D=metrics(t(window),eD(window));analysis.K=metrics(t(window),eK(window));
analysis.yaw=struct('meanAbs',mean(abs(yaw(window))),'medianAbs',median(abs(yaw(window))), ...
    'maxAbs',max(abs(yaw(window))));
analysis.relative=struct('KoverD_RMSE',analysis.K.RMSE/analysis.D.RMSE, ...
    'KoverD_MAE',analysis.K.MAE/analysis.D.MAE,'KoverD_MaxAbs',analysis.K.MaxAbs/analysis.D.MaxAbs, ...
    'KoverD_AbsSlope',abs(analysis.K.slope)/max(abs(analysis.D.slope),eps));
analysis.lowYawSufficient=primary.longestDuration>=10;
analysis.passed=aligned&&finite&&timeOK&&steerZero&&replayD<=1e-12&&replayK<=1e-12&& ...
    analysis.lowYawSufficient;
save(resultFile,'analysis','-v7');write_csv(csvFile,analysis);
fprintf(['V28_A3_ANALYSIS|passed=%d|N=%d|window=[%.17g %.17g]|duration=%.17g|' ...
    'K_RMSE=%.17g|K_MAE=%.17g|K_MAX=%.17g|K_BIAS=%.17g|' ...
    'D_RMSE=%.17g|D_MAE=%.17g|D_MAX=%.17g|D_BIAS=%.17g\n'], ...
    analysis.passed,N,s,e,primary.longestDuration,analysis.K.RMSE,analysis.K.MAE, ...
    analysis.K.MaxAbs,analysis.K.Bias,analysis.D.RMSE,analysis.D.MAE, ...
    analysis.D.MaxAbs,analysis.D.Bias);
fprintf(['V28_A3_DRIFT|K_start=%.17g|K_end=%.17g|K_drift=%.17g|K_slope=%.17g|' ...
    'K_startMean1s=%.17g|K_endMean1s=%.17g|K_meanDrift=%.17g|' ...
    'D_start=%.17g|D_end=%.17g|D_drift=%.17g|D_slope=%.17g|' ...
    'D_startMean1s=%.17g|D_endMean1s=%.17g|D_meanDrift=%.17g\n'], ...
    analysis.K.start,analysis.K.end,analysis.K.drift,analysis.K.slope, ...
    analysis.K.startMean1s,analysis.K.endMean1s,analysis.K.meanDrift, ...
    analysis.D.start,analysis.D.end,analysis.D.drift,analysis.D.slope, ...
    analysis.D.startMean1s,analysis.D.endMean1s,analysis.D.meanDrift);
for i=1:3,p=parts(i);fprintf(['V28_A3_PARTITION|threshold=%.17g|samples=%d|' ...
        'fraction=%.17g|total=%.17g|longest=%.17g|start=%.17g|end=%.17g\n'], ...
        p.threshold,p.sampleCount,p.fraction,p.totalDuration,p.longestDuration, ...
        p.longestStart,p.longestEnd);end
assert(analysis.passed,'V28A3:AnalysisFailed','A3 runtime/low-yaw analysis gate failed.');
end

function x=scalar_log(r)
d=double(r.data);N=r.sampleCount;
if isvector(d)&&numel(d)==N,x=d(:);
elseif size(d,1)==N&&size(d,2)==1,x=d;
elseif size(d,2)==N&&size(d,1)==1,x=d(:);
else,error('V28A3:LogShape','Expected scalar log, got %s.',mat2str(size(d)));end
end
function [total,longest,startTime,endTime]=durations(t,mask)
mask=logical(mask(:));t=t(:);total=sum(diff(t).*double(mask(1:end-1)));
edges=diff([false;mask;false]);starts=find(edges==1);ends=find(edges==-1)-1;
if isempty(starts),longest=0;startTime=NaN;endTime=NaN;return,end
span=t(ends)-t(starts);[longest,i]=max(span);startTime=t(starts(i));endTime=t(ends(i));
end
function m=metrics(t,e)
m=struct('RMSE',sqrt(mean(e.^2)),'MAE',mean(abs(e)),'MaxAbs',max(abs(e)), ...
    'Bias',mean(e),'start',e(1),'end',e(end),'drift',e(end)-e(1), ...
    'absGrowth',abs(e(end))-abs(e(1)));
p=polyfit(t-t(1),e,1);m.slope=p(1);span=min(1,t(end)-t(1));
m.startMean1s=mean(e(t<=t(1)+span+1e-12));m.endMean1s=mean(e(t>=t(end)-span-1e-12));
m.meanDrift=m.endMean1s-m.startMean1s;
end
function write_csv(path,a)
fid=fopen(path,'wt');assert(fid>0,'Cannot open A3 summary CSV.');c=onCleanup(@()fclose(fid));
fprintf(fid,'section,metric,value\n');fprintf(fid,'integrity,passed,%d\n',a.passed);
fprintf(fid,'primary,start,%.17g\n',a.primaryWindow.start);fprintf(fid,'primary,end,%.17g\n',a.primaryWindow.end);
fprintf(fid,'primary,duration,%.17g\n',a.primaryWindow.duration);
for i=1:3,p=a.partitions(i);tag=sprintf('r_lt_%.3f',p.threshold); ...
        fprintf(fid,'%s,totalDuration,%.17g\n',tag,p.totalDuration); ...
        fprintf(fid,'%s,longestDuration,%.17g\n',tag,p.longestDuration); ...
        fprintf(fid,'%s,longestStart,%.17g\n',tag,p.longestStart); ...
        fprintf(fid,'%s,longestEnd,%.17g\n',tag,p.longestEnd);end
for name={'D','K'},m=a.(name{1});fields=fieldnames(m);for k=1:numel(fields), ...
        fprintf(fid,'%s,%s,%.17g\n',name{1},fields{k},m.(fields{k}));end,end
clear c
end
