function report = analyze_vy_dkekf_v2_2c2_preflight()
%ANALYZE_VY_DKEKF_V2_2C2_PREFLIGHT Analyze saved runtime; never simulates.

root=fileparts(fileparts(mfilename('fullpath')));
resultFile=fullfile(root,'results','vy_dkekf_v2_2c2_preflight.mat');
s=load(resultFile,'report');report=s.report;
assert(report.simulationCompleted&&report.simCalled&&report.carSimRun, ...
    'The unique C2 runtime did not complete successfully.');
r=report.raw;
names={'dkekf_u_log1','dkekf_x_log1','dkekf_P_log1','dkekf_diag_log1'};
times=cellfun(@(n)r.(n).time(:),names,'UniformOutput',false);
counts=cellfun(@numel,times);
outputsAligned=isequal(times{2},times{3},times{4});
assert(outputsAligned,'DK-EKF x/P/diag logs do not share exact timestamps.');
t=times{2};n=numel(t);dt=diff(t);

[u,inputAlignment]=input_rows_at_hits(r.dkekf_u_log1.data,times{1},t,10);
assert(inputAlignment.allHitsResolved&&~inputAlignment.ambiguousDuplicate, ...
    'Runtime input log cannot be resolved exactly at every DK-EKF hit.');
x=sample_rows(r.dkekf_x_log1.data,n,3);
P=covariance_pages(r.dkekf_P_log1.data,n);
d=sample_rows(r.dkekf_diag_log1.data,n,7);

timing=struct('sampleCounts',counts,'outputLogsAligned',outputsAligned, ...
    'inputAlignment',inputAlignment, ...
    'sampleCount',n,'tStart',t(1),'tEnd',t(end), ...
    'dtMin',min(dt),'dtMean',mean(dt),'dtMax',max(dt), ...
    'duplicateTimestamp',any(dt<=0),'missing100HzHit', ...
    any(abs(dt-0.01)>1e-12)||n~=round((t(end)-t(1))/0.01)+1, ...
    'actual100Hz',all(abs(dt-0.01)<=1e-12));

reset=u(:,6)>0.5;resetTimes=t(reset);
resetGate=struct('highCount',nnz(reset),'highTimestamps',resetTimes, ...
    'onceAtZero',nnz(reset)==1&&abs(resetTimes(1))<=1e-12, ...
    'initialStatePrior',[u(1,4);0;0], ...
    'initialCovariancePrior',diag([0.1 0.1 0.1]), ...
    'trueVyUsedForInitialization',false);

doAy=u(:,5)>0.5;ayApplied=d(:,4)>0.5;
ay=struct('doAyHighCount',nnz(doAy),'doAyHighTimestamps',t(doAy), ...
    'appliedCount',nnz(ayApplied),'appliedTimestamps',t(ayApplied), ...
    'appliedOnlyWhenEnabled',~any(ayApplied&~doAy), ...
    'sequenceExact',isequal(doAy,ayApplied));

finite=struct('x',all(isfinite(x(:))),'P',all(isfinite(P(:))), ...
    'diag',all(isfinite(d(:))));
maxAsym=0;minEig=inf;pDiag=zeros(n,3);
for k=1:n
    pk=P(:,:,k);maxAsym=max(maxAsym,max(abs(pk-pk.'),[],'all'));
    minEig=min(minEig,min(eig(0.5*(pk+pk.'))));
    pDiag(k,:)=diag(pk).';
end
covariance=struct('maxAsymmetry',maxAsym, ...
    'minimumEigenvalue',minEig,'p11MinMax',[min(pDiag(:,1)) max(pDiag(:,1))], ...
    'p22MinMax',[min(pDiag(:,2)) max(pDiag(:,2))], ...
    'p33MinMax',[min(pDiag(:,3)) max(pDiag(:,3))], ...
    'valid',finite.P&&maxAsym<=1e-12&&minEig>=-1e-12);

[rx,rp,rd,replayMeta]=exact_replay(u);
replay=struct('alignmentRule',[ ...
    'At each logged function-call timestamp, Outputs computes one candidate ' ...
    'from the currently committed DWork (or reset prior); the runtime logs ' ...
    'that candidate at the same timestamp, then Update commits it. Offline ' ...
    'replay therefore compares the single core result at hit k directly ' ...
    'with runtime sample k, with no shift.'], ...
    'maxAbsXDiff',max(abs(rx(:)-x(:))), ...
    'maxAbsPDiff',max(abs(rp(:)-P(:))), ...
    'maxAbsDiagDiff',max(abs(rd(:)-d(:))), ...
    'initialPrior',replayMeta.initialPrior, ...
    'initialP',replayMeta.initialP,'shiftApplied',false);
replay.within1e12=replay.maxAbsXDiff<=1e-12&& ...
    replay.maxAbsPDiff<=1e-12&&replay.maxAbsDiagDiff<=1e-12;

fairness=report.static.fairness;
fairness.pass=~fairness.trueVyOnline&&fairness.trueVxMeasurementOnly&& ...
    fairness.axPredictionInput&&fairness.avzMeasurementOnly&& ...
    fairness.ayMeasurementOnly&&fairness.sharedStateAndP&& ...
    ~fairness.outputFusion&&~fairness.lifeSig&&~fairness.adaptiveFusion;
oneHitOneAdvance=timing.actual100Hz&&~timing.duplicateTimestamp&& ...
    ~timing.missing100HzHit&&replay.within1e12;

gates=struct();
gates.simulationCompleted=report.simulationCompleted;
gates.carSimRan=report.carSimRun;
gates.logsAligned100Hz=timing.actual100Hz&&timing.outputLogsAligned&& ...
    timing.inputAlignment.allHitsResolved&& ...
    ~timing.inputAlignment.ambiguousDuplicate&& ...
    ~timing.duplicateTimestamp&&~timing.missing100HzHit;
gates.resetOnceAtZero=resetGate.onceAtZero;
gates.resetInitializationSemantics=~resetGate.trueVyUsedForInitialization&& ...
    isequal(resetGate.initialStatePrior,[u(1,4);0;0])&& ...
    isequal(resetGate.initialCovariancePrior,diag([0.1 0.1 0.1]));
gates.ay20HzRuntimeSequence=ay.sequenceExact&&ay.appliedOnlyWhenEnabled;
gates.outputDimensions=size(x,2)==3&&isequal(size(P),[3 3 n])&&size(d,2)==7;
gates.numericFinite=finite.x&&finite.P&&finite.diag;
gates.covarianceValid=covariance.valid;
gates.exactReplay=replay.within1e12;
gates.oneHitOneCommittedAdvance=oneHitOneAdvance;
gates.fairness=fairness.pass;
gates.hashIntegrity=report.frozenHashesUnchanged&&report.targetUnchanged&& ...
    report.simfileUnchanged;
values=struct2cell(gates);gateVector=cellfun(@logical,values);

report.analysis=struct('timing',timing,'reset',resetGate,'ay',ay, ...
    'finite',finite,'covariance',covariance,'replay',replay, ...
    'oneHitOneCommittedAdvance',oneHitOneAdvance,'fairness',fairness, ...
    'gates',gates,'gateCount',numel(gateVector), ...
    'gatesTrue',sum(gateVector),'passed',all(gateVector));
save(resultFile,'report','-v7.3');
fprintf(['V2_2C2_ANALYSIS|passed=%d|samples=%d|t=[%.17g %.17g]|' ...
    'dt=[%.17g %.17g %.17g]|reset=%d|Ay=%d/%d|' ...
    'finite=%d/%d/%d|PAsym=%.3g|minEig=%.17g|' ...
    'replay=[%.3g %.3g %.3g]|oneHit=%d|hash=%d\n'], ...
    report.analysis.passed,n,t(1),t(end),timing.dtMin,timing.dtMean, ...
    timing.dtMax,resetGate.highCount,ay.doAyHighCount,ay.appliedCount, ...
    finite.x,finite.P,finite.diag,covariance.maxAsymmetry, ...
    covariance.minimumEigenvalue,replay.maxAbsXDiff, ...
    replay.maxAbsPDiff,replay.maxAbsDiagDiff,oneHitOneAdvance, ...
    gates.hashIntegrity);
assert(report.analysis.passed,'One or more V2.2-C2 runtime gates failed.');
end

function [xReplay,pReplay,dReplay,meta]=exact_replay(u)
n=size(u,1);xReplay=zeros(n,3);pReplay=zeros(3,3,n);dReplay=zeros(n,7);
[par,cfg,Ts,P0]=baseline_configuration();initialized=false;
xState=zeros(3,1);PState=P0;
for k=1:n
    if ~initialized||u(k,6)>0.5
        xPrior=[u(k,4);0;0];PPrior=P0;
    else
        xPrior=xState;PPrior=PState;
    end
    if k==1,meta=struct('initialPrior',xPrior,'initialP',PPrior);end
    [xNew,PNew,info]=vy_dkekf_baseline_step(xPrior,PPrior,u(k,1), ...
        u(k,7:10).',u(k,4),u(k,3),u(k,2),u(k,5),Ts,par,cfg);
    nisAy=info.Ay.NIS;
    if ~info.Ay.updateApplied&&isnan(nisAy),nisAy=0;end
    diagNumeric=[info.Vx.NIS;info.r.NIS;nisAy; ...
        double(info.Ay.updateApplied);info.Vx.innovation; ...
        info.r.innovation;info.Ay.innovation];
    xReplay(k,:)=xNew.';pReplay(:,:,k)=PNew;dReplay(k,:)=diagNumeric.';
    xState=xNew;PState=PNew;initialized=true;
end
end

function [par,cfg,Ts,P0]=baseline_configuration()
par=struct('m',1860,'Iz',2687.1,'a',1.18,'b',1.77, ...
    'track',1.575,'Rw',0.393,'k_f',0.78181,'k_r',1.09186);
Ts=0.01;cfg=struct();cfg.Q_DK=diag([1e-4 1e-4 1e-4]);
cfg.R_Vx=1e-4;cfg.R_r=3.365172961808e-4;cfg.R_Ay=1e-2;
cfg.jacobianStep=1e-6;cfg.denomEps=1e-12;cfg.lambda=zeros(4,1);
P0=diag([0.1 0.1 0.1]);
end

function a=sample_rows(data,n,width)
a=double(data);s=size(a);
if ismatrix(a)
    if isequal(s,[n width]),return;end
    if isequal(s,[width n]),a=a.';return;end
end
if numel(a)==n*width
    a=reshape(a,width,n).';return
end
error('VY_DKEKF:LogShape','Cannot resolve %d-wide log with size %s.', ...
    width,mat2str(s));
end
function [hits,audit]=input_rows_at_hits(data,inputTime,hitTime,width)
inputTime=double(inputTime(:));rows=sample_rows(data,numel(inputTime),width);
hits=zeros(numel(hitTime),width);matchCount=zeros(numel(hitTime),1);
nearCoincidentCount=zeros(numel(hitTime),1);nearestDelta=zeros(numel(hitTime),1);
ambiguous=false;
for k=1:numel(hitTime)
    tol=32*eps(max(1,abs(hitTime(k))));
    delta=abs(inputTime-hitTime(k));nearestDelta(k)=min(delta);
    ix=find(delta==nearestDelta(k));
    matchCount(k)=numel(ix);
    nearCoincidentCount(k)=nnz(delta<=tol);
    if nearestDelta(k)>tol,continue;end
    candidate=rows(ix,:);
    if size(candidate,1)>1&&any(max(abs(candidate-candidate(end,:)),[],2)>1e-12)
        ambiguous=true;
    end
    hits(k,:)=candidate(end,:);
end
audit=struct('rawInputSampleCount',numel(inputTime), ...
    'hitSampleCount',numel(hitTime),'matchCountPerHit',matchCount, ...
    'nearCoincidentCountPerHit',nearCoincidentCount, ...
    'nearestTimeDelta',nearestDelta, ...
    'allHitsResolved',all(matchCount>=1)&&all(nearestDelta==0), ...
    'duplicateMatchCount',nnz(matchCount>1), ...
    'ambiguousDuplicate',ambiguous,'timestampShiftApplied',false);
end
function p=covariance_pages(data,n)
p=double(data);s=size(p);
if ndims(p)==3&&isequal(s,[3 3 n]),return;end
if ndims(p)==3&&isequal(s,[n 3 3]),p=permute(p,[2 3 1]);return;end
if ismatrix(p)&&isequal(s,[n 9])
    p=permute(reshape(p.',3,3,n),[1 2 3]);return
end
if numel(p)==9*n,p=reshape(p,3,3,n);return;end
error('VY_DKEKF:LogShape','Cannot resolve covariance log size %s.',mat2str(s));
end
