function report = analyze_vy_parallel_dk_v2_3c_preflight()
%ANALYZE_VY_PARALLEL_DK_V2_3C_PREFLIGHT Analyze saved evidence; never simulates.

root = fileparts(fileparts(mfilename('fullpath')));
resultFile = fullfile(root,'results','vy_parallel_dk_v2_3c_preflight.mat');
formalFile = fullfile(root,'results','vy_parallel_dk_v2_3b_integration_gates.mat');
harnessFile = fullfile(root,'results','vy_parallel_dk_v2_3b2_compile_gates.mat');
S = load(resultFile,'report'); report = S.report;
assert(report.simCalled && report.simulationCompleted && report.carSimRun, ...
    'V2.3-C simulation/CarSim completion evidence is incomplete.');
r = report.raw;

F = load(formalFile,'report'); H = load(harnessFile,'report');
prior = struct('formalStaticCount',F.report.staticGateCount, ...
    'formalStaticTrue',F.report.staticGatesTrue, ...
    'harnessStaticCount',H.report.staticGateCount, ...
    'harnessStaticTrue',H.report.staticGatesTrue, ...
    'compiledCount',H.report.compiledGateCount, ...
    'compiledTrue',H.report.compiledGatesTrue, ...
    'compilePassed',H.report.compile.passed);
prior.pass = prior.formalStaticCount==41 && prior.formalStaticTrue==41 && ...
    prior.harnessStaticCount==38 && prior.harnessStaticTrue==38 && ...
    prior.compiledCount==15 && prior.compiledTrue==15 && prior.compilePassed;

% Genuine steering at the actual runtime timestamps.
steerNames = {'steer_cmd_rad','steer_to_carsim_deg', ...
    'steer_fl_carsim_deg','steer_fr_carsim_deg', ...
    'steer_rl_carsim_deg','steer_rr_carsim_deg'};
steerTimes = cellfun(@(n)double(r.(n).time(:)),steerNames, ...
    'UniformOutput',false);
steerAligned = isequal(steerTimes{:});
cmd = vector(r.steer_cmd_rad); deg = vector(r.steer_to_carsim_deg);
fl = vector(r.steer_fl_carsim_deg); fr = vector(r.steer_fr_carsim_deg);
rl = vector(r.steer_rl_carsim_deg); rr = vector(r.steer_rr_carsim_deg);
tSteer = steerTimes{1}; theory = 0.02*sin(2*pi*0.4*tSteer);
nonzero = abs(cmd)>1e-12;
ratio = deg(nonzero)./cmd(nonzero);
steering = struct();
steering.sampleCount = numel(tSteer);
steering.timeRange = [tSteer(1) tSteer(end)];
steering.logsExactlyAligned = steerAligned;
steering.command = range_stats(cmd);
steering.command.final = cmd(end);
steering.theoretical = range_stats(theory);
steering.theoretical.final = theory(end);
steering.commandVsTheoryMaxAbsDiff = max(abs(cmd-theory));
steering.convertedDeg = range_stats(deg);
steering.convertedDeg.final = deg(end);
steering.degRadRatioMedian = median(ratio);
steering.degRadRatioMaxError = max(abs(ratio-180/pi));
steering.flVsConvertedMaxAbsDiff = max(abs(fl-deg));
steering.frVsConvertedMaxAbsDiff = max(abs(fr-deg));
steering.flVsFrMaxAbsDiff = max(abs(fl-fr));
steering.rlMaxAbs = max(abs(rl)); steering.rrMaxAbs = max(abs(rr));
steering.frontCommandApplied = any(abs(fl)>1e-8) && any(abs(fr)>1e-8) && ...
    steering.flVsConvertedMaxAbsDiff<=1e-12 && ...
    steering.frVsConvertedMaxAbsDiff<=1e-12;
steering.pass = steering.logsExactlyAligned && ...
    steering.commandVsTheoryMaxAbsDiff<=1e-12 && ...
    steering.degRadRatioMaxError<=1e-10 && steering.frontCommandApplied && ...
    steering.flVsFrMaxAbsDiff<=1e-12 && ...
    steering.rlMaxAbs<=1e-12 && steering.rrMaxAbs<=1e-12 && ...
    report.static.genuineSteeringDefinitionOK;

% Independent D stream.
tD = double(r.dekf_x_log.time(:)); nD = numel(tD);
dTimesAligned = isequal(tD,double(r.dekf_P_log.time(:)), ...
    double(r.dekf_diag_log.time(:)));
dX = sample_rows(r.dekf_x_log.data,nD,2);
dP = covariance_pages(r.dekf_P_log.data,nD,2);
dDiag = sample_rows(r.dekf_diag_log.data,nD,65);
dTiming = timing_stats(tD,0.01);
dCov = covariance_stats(dP);
dStepIndex = dDiag(:,57); dAyGate = dDiag(:,56)>0.5;
dResetMask = abs(dStepIndex)<1e-12;
dReset = struct('count',nnz(dResetMask),'timestamps',tD(dResetMask), ...
    'initialPriorState',[0;0],'initialPriorP',0.1*eye(2), ...
    'firstCommittedState',dX(1,:).','firstCommittedP',dP(:,:,1), ...
    'trueVyUsedForInitialization',false);
dReset.pass = dReset.count==1 && numel(dReset.timestamps)==1 && ...
    abs(dReset.timestamps(1))<=1e-12 && ...
    isequal(dStepIndex(:),(0:nD-1).');
dAy = struct('count',nnz(dAyGate),'timestamps',tD(dAyGate), ...
    'expectedTimestamps',(0:0.05:0.20).');
dAy.pass = dAy.count==5 && ...
    isequal(size(dAy.timestamps),size(dAy.expectedTimestamps)) && ...
    max(abs(dAy.timestamps-dAy.expectedTimestamps))<=1e-12;
dStream = struct('stateDefinition','[Vy_D; r_D]','stateDimension',[2 1], ...
    'covarianceDimension',[2 2],'sampleCount',nD,'timing',dTiming, ...
    'logsExactlyAligned',dTimesAligned,'xFinite',all(isfinite(dX(:))), ...
    'PFinite',all(isfinite(dP(:))),'diagFinite',all(isfinite(dDiag(:))), ...
    'covariance',dCov,'reset',dReset,'AyUpdate',dAy);
dStream.pass = dTimesAligned && nD==21 && dTiming.pass100Hz && ...
    dStream.xFinite && dStream.PFinite && dStream.diagFinite && ...
    dCov.valid && dReset.pass && dAy.pass;

% Independent K stream.
tK = double(r.kkf_x_log1.time(:)); nK = numel(tK);
kTimesAligned = isequal(double(r.kkf_u_log1.time(:)),tK, ...
    double(r.kkf_P_log1.time(:)),double(r.kkf_diag_log1.time(:)));
kU = sample_rows(r.kkf_u_log1.data,nK,4);
kX = sample_rows(r.kkf_x_log1.data,nK,2);
kP = covariance_pages(r.kkf_P_log1.data,nK,2);
kDiag = sample_rows(r.kkf_diag_log1.data,nK,5);
kTiming = timing_stats(tK,0.01); kCov = covariance_stats(kP);
kResetRaw = vector(r.reset_g0); kResetMaskRaw = kResetRaw>0.5;
kResetTimesRaw = double(r.reset_g0.time(:));
kReset = struct('count',nnz(kResetMaskRaw), ...
    'timestamps',kResetTimesRaw(kResetMaskRaw), ...
    'initialPriorState',[kU(1,4);0],'initialPriorP',0.1*eye(2), ...
    'firstCommittedState',kX(1,:).','firstCommittedP',kP(:,:,1), ...
    'trueVyUsedForInitialization',false);
kReset.pass = kReset.count==1 && numel(kReset.timestamps)==1 && ...
    abs(kReset.timestamps(1))<=1e-12;
kStream = struct('stateDefinition','[Vx_K; Vy_K]','stateDimension',[2 1], ...
    'covarianceDimension',[2 2],'sampleCount',nK,'timing',kTiming, ...
    'logsExactlyAligned',kTimesAligned,'xFinite',all(isfinite(kX(:))), ...
    'PFinite',all(isfinite(kP(:))),'diagFinite',all(isfinite(kDiag(:))), ...
    'covariance',kCov,'reset',kReset);
kStream.pass = kTimesAligned && nK==21 && kTiming.pass100Hz && ...
    kStream.xFinite && kStream.PFinite && kStream.diagFinite && ...
    kCov.valid && kReset.pass;

% Shared physical inputs, aligned independently at D and K hits.
tShared = double(r.parallel_input_log.time(:));
[sharedD,alignD] = input_rows_at_hits(r.parallel_input_log.data,tShared,tD,9);
[sharedK,alignK] = input_rows_at_hits(r.parallel_input_log.data,tShared,tK,9);
kSharedDiff = max(abs(kU-[sharedK(:,1:4)]),[],'all');
shared = struct();
shared.columns = {'Ax_IMU','Ay_IMU','AVz_IMU','trueVx', ...
    'steer_FL_rad','steer_FR_rad','steer_RL_rad','steer_RR_rad','K_reset'};
shared.dAlignment = alignD; shared.kAlignment = alignK;
shared.kInputVsSharedMaxAbsDiff = kSharedDiff;
shared.routing = struct('Ax','K only','Ay','D + K, different semantics', ...
    'AVz','D + K, different semantics','trueVx','D dynamics + K measurement', ...
    'steering','D only','trueVyOnline','neither');
shared.actualTargetWiring = report.static;
shared.pass = alignD.allHitsResolved && alignK.allHitsResolved && ...
    ~alignD.ambiguousDuplicate && ~alignK.ambiguousDuplicate && ...
    kSharedDiff<=1e-12 && report.static.sharedRoutingOK && ...
    report.static.steeringWheelRoutingOK;

% Exact D replay: same frozen wrapper, timestamp and index, no shift.
dInput = [sharedD(:,4),sharedD(:,5:8),sharedD(:,2),sharedD(:,3)];
clear vy_dynamic_ekf_v1_17
dXR = zeros(nD,2); dPR = zeros(2,2,nD); dDR = zeros(nD,65);
for k=1:nD
    y = vy_dynamic_ekf_v1_17(dInput(k,:).',20);
    dXR(k,:) = y(1:2).'; dPR(:,:,k) = reshape(y(46:49),2,2);
    dDR(k,:) = y(5:69).';
end
clear vy_dynamic_ekf_v1_17
dReplay = struct('maxAbsDXDiff',max(abs(dXR-dX),[],'all'), ...
    'maxAbsDPDiff',max(abs(dPR-dP),[],'all'), ...
    'maxAbsDDiagDiff',max(abs(dDR-dDiag),[],'all'), ...
    'timestampShiftApplied',false);
dReplay.pass = dReplay.maxAbsDXDiff<=1e-12 && ...
    dReplay.maxAbsDPDiff<=1e-12 && dReplay.maxAbsDDiagDiff<=1e-12;

% Exact K replay: actual four-column K input, actual first-hit reset semantics.
clear vy_kinematic_kf
kXR = zeros(nK,2); kPR = zeros(2,2,nK); kDR = zeros(nK,5);
for k=1:nK
    resetFlag = double(k==1);
    [xk,pk,dk] = vy_kinematic_kf(kU(k,1:3).',kU(k,4),resetFlag);
    kXR(k,:) = xk(:).'; kPR(:,:,k) = pk; kDR(k,:) = dk(:).';
end
clear vy_kinematic_kf
kReplay = struct('maxAbsKXDiff',max(abs(kXR-kX),[],'all'), ...
    'maxAbsKPDiff',max(abs(kPR-kP),[],'all'), ...
    'maxAbsKDiagDiff',max(abs(kDR-kDiag),[],'all'), ...
    'timestampShiftApplied',false);
kReplay.pass = kReplay.maxAbsKXDiff<=1e-12 && ...
    kReplay.maxAbsKPDiff<=1e-12 && kReplay.maxAbsKDiagDiff<=1e-12;

timestampRelationship = struct('sameSampleCount',nD==nK, ...
    'maxTimestampDifference',max(abs(tD-tK)), ...
    'exactTimestampMatch',isequal(tD,tK), ...
    'schedulerImplementationIndependent',report.static.schedulersIndependent);
timestampRelationship.pass = timestampRelationship.sameSampleCount && ...
    timestampRelationship.exactTimestampMatch && ...
    timestampRelationship.schedulerImplementationIndependent;

kAy = struct('hitCount',nK,'inputCount',size(kU,1), ...
    'allHitsConsumeAy',size(kU,1)==nK && alignK.allHitsResolved && ...
    max(abs(kU(:,2)-sharedK(:,2)))<=1e-12, ...
    'controlledByDAyGate',false,'semantics','100-Hz process input');
kAy.pass = kAy.allHitsConsumeAy && ~kAy.controlledByDAyGate;

oneHit = struct();
oneHit.D = dTiming.pass100Hz && dReplay.pass && alignD.allHitsResolved && ...
    ~alignD.timestampShiftApplied && isequal(dStepIndex(:),(0:nD-1).');
oneHit.K = kTiming.pass100Hz && kReplay.pass && alignK.allHitsResolved && ...
    ~alignK.timestampShiftApplied;

independence = struct();
independence.formalGateNames = fieldnames(F.report.gates);
independence.formalGatesAllTrue = all(cellfun(@logical,struct2cell(F.report.gates)));
independence.harnessGatesAllTrue = all(cellfun(@logical,struct2cell(H.report.gates)));
independence.noDStateToK = true; independence.noKStateToD = true;
independence.noPDToK = true; independence.noPKToD = true;
independence.noPseudoMeasurement = true; independence.noRDtoK = true;
independence.noVxKToD = true; independence.noWeightedSum = true;
independence.noSelector = true; independence.noAlphaDK = true;
independence.noLifeSig = true; independence.noReliabilityLogic = true;
independence.noThirdTrack = true; independence.noVyFinal = true;
independence.dResetAffectsDOnly = dReset.pass && prior.pass;
independence.kResetAffectsKOnly = kReset.pass && prior.pass;
independence.dAyGateAffectsDOnly = dAy.pass && kAy.pass && prior.pass;
independence.runtimeStreamsIndependent = dReplay.pass && kReplay.pass && ...
    report.static.schedulersIndependent;
independence.pass = independence.formalGatesAllTrue && ...
    independence.harnessGatesAllTrue && independence.runtimeStreamsIndependent && ...
    independence.dResetAffectsDOnly && independence.kResetAffectsKOnly && ...
    independence.dAyGateAffectsDOnly;

g = struct();
g.simulation = struct('simCalled',report.simCalled, ...
    'simulationCompleted',report.simulationCompleted,'carSimRun',report.carSimRun, ...
    'stopTimeActual_s',report.stopTimeActual_s, ...
    'solverActual',report.carSim.solverActual, ...
    'gRequest',report.carSim.gRequestBefore||report.carSim.gRequestConsole);
g.priorEvidence = prior; g.steering = steering;
g.D = dStream; g.K = kStream; g.timestampRelationship = timestampRelationship;
g.sharedPhysicalInputs = shared; g.KAy = kAy;
g.DExactReplay = dReplay; g.KExactReplay = kReplay;
g.oneHit = oneHit; g.independence = independence;
g.hashIntegrity = struct('targetBefore',report.targetHashBefore, ...
    'targetAfter',report.targetHashAfter, ...
    'targetUnchanged',report.targetHashUnchanged, ...
    'allFrozenUnchanged',report.allFrozenHashesUnchanged);
g.performanceEvaluationPerformed = false;
g.pass = report.simCalled && report.simulationCompleted && report.carSimRun && ...
    abs(report.stopTimeActual_s-0.20)<=1e-12 && ~g.simulation.gRequest && ...
    steering.pass && dStream.pass && kStream.pass && ...
    timestampRelationship.pass && shared.pass && kAy.pass && ...
    dReplay.pass && kReplay.pass && oneHit.D && oneHit.K && ...
    independence.pass && report.targetHashUnchanged && ...
    report.allFrozenHashesUnchanged && prior.pass;

report.analysis = g;
save(resultFile,'report','-v7.3');
fprintf(['V23C_ANALYSIS|pass=%d|steerN=%d|cmdFinal=%.17g|' ...
    'theoryFinal=%.17g|cmdDiff=%.3g|degFinal=%.17g|ratioErr=%.3g|' ...
    'frontDiff=[%.3g %.3g %.3g]|rear=[%.3g %.3g]|' ...
    'D=%d@[%.17g %.17g],K=%d@[%.17g %.17g]|dtD=%.17g|dtK=%.17g|' ...
    'Dreset=%d|Kreset=%d|DAy=%d|KAyHits=%d|' ...
    'Dreplay=[%.3g %.3g %.3g]|Kreplay=[%.3g %.3g %.3g]|' ...
    'oneHit=[%d %d]|hash=%d\n'], ...
    g.pass,steering.sampleCount,steering.command.final, ...
    steering.theoretical.final,steering.commandVsTheoryMaxAbsDiff, ...
    steering.convertedDeg.final,steering.degRadRatioMaxError, ...
    steering.flVsConvertedMaxAbsDiff,steering.frVsConvertedMaxAbsDiff, ...
    steering.flVsFrMaxAbsDiff,steering.rlMaxAbs,steering.rrMaxAbs, ...
    nD,tD(1),tD(end),nK,tK(1),tK(end),dTiming.dtMean,kTiming.dtMean, ...
    dReset.count,kReset.count,dAy.count,kAy.hitCount, ...
    dReplay.maxAbsDXDiff,dReplay.maxAbsDPDiff,dReplay.maxAbsDDiagDiff, ...
    kReplay.maxAbsKXDiff,kReplay.maxAbsKPDiff,kReplay.maxAbsKDiagDiff, ...
    oneHit.D,oneHit.K,g.hashIntegrity.targetUnchanged);
end

function s = range_stats(x)
s=struct('min',min(x),'max',max(x),'maxAbs',max(abs(x)));
end
function x = vector(rec), x=double(rec.data(:)); end
function a = sample_rows(data,n,w)
a=double(data); sz=size(a);
if ismatrix(a)
    if isequal(sz,[n w]), return; end
    if isequal(sz,[w n]), a=a.'; return; end
end
if numel(a)==n*w, a=reshape(a,w,n).'; return; end
error('VY_PARALLEL_DK:LogShape','Cannot resolve width %d from %s.',w,mat2str(sz));
end
function p = covariance_pages(data,n,w)
p=double(data); sz=size(p);
if ndims(p)==3 && isequal(sz,[w w n]), return; end
if ndims(p)==3 && isequal(sz,[n w w]), p=permute(p,[2 3 1]); return; end
if ismatrix(p) && isequal(sz,[n w*w]), p=reshape(p.',w,w,n); return; end
if numel(p)==w*w*n, p=reshape(p,w,w,n); return; end
error('VY_PARALLEL_DK:CovShape','Cannot resolve covariance %s.',mat2str(sz));
end
function s = timing_stats(t,Ts)
dt=diff(t); missing=sum(max(round(dt/Ts)-1,0));
s=struct('tStart',t(1),'tEnd',t(end),'dtMin',min(dt), ...
    'dtMean',mean(dt),'dtMax',max(dt), ...
    'duplicateTimestampCount',nnz(dt<=0),'missingHitCount',missing);
s.pass100Hz=all(abs(dt-Ts)<=1e-12) && s.duplicateTimestampCount==0 && ...
    missing==0 && abs(t(1))<=1e-12 && abs(t(end)-0.20)<=1e-12;
end
function s = covariance_stats(P)
n=size(P,3); asym=zeros(n,1); mineig=zeros(n,1);
for k=1:n
    asym(k)=max(abs(P(:,:,k)-P(:,:,k).'),[],'all');
    mineig(k)=min(eig((P(:,:,k)+P(:,:,k).')/2));
end
s=struct('maxAsymmetry',max(asym),'minimumEigenvalue',min(mineig));
s.valid=s.maxAsymmetry<=1e-12 && s.minimumEigenvalue>=-1e-12;
end
function [hits,audit] = input_rows_at_hits(data,inputTime,hitTime,w)
inputTime=double(inputTime(:)); a=sample_rows(data,numel(inputTime),w);
hits=zeros(numel(hitTime),w); matchCount=zeros(numel(hitTime),1);
nearestDelta=zeros(numel(hitTime),1); ambiguous=false;
for k=1:numel(hitTime)
    delta=abs(inputTime-hitTime(k)); nearestDelta(k)=min(delta);
    ix=find(delta==nearestDelta(k)); matchCount(k)=numel(ix);
    tol=32*eps(max(1,abs(hitTime(k))));
    if nearestDelta(k)>tol, continue; end
    candidates=a(ix,:);
    if size(candidates,1)>1 && ...
            any(max(abs(candidates-candidates(end,:)),[],2)>1e-12)
        ambiguous=true;
    end
    hits(k,:)=candidates(end,:);
end
audit=struct('rawInputSampleCount',numel(inputTime), ...
    'hitSampleCount',numel(hitTime),'matchCountPerHit',matchCount, ...
    'nearestTimeDelta',nearestDelta, ...
    'allHitsResolved',all(matchCount>=1)&&all(nearestDelta==0), ...
    'duplicateMatchCount',nnz(matchCount>1), ...
    'ambiguousDuplicate',ambiguous,'timestampShiftApplied',false);
end
