function report = run_vy_fixed_fusion_v2_5g_calibration(runId)
%RUN_VY_FIXED_FUSION_V2_5G_CALIBRATION Execute one preregistered calibration run.
% This function deliberately refuses holdout IDs, out-of-order acquisition,
% overwrites, and retries.  It performs exactly one sim() call for one ID.

root=fileparts(fileparts(mfilename('fullpath')));
md=fullfile(root,'model');
model='vx_vy_fixed_fusion_v2_5';
target=fullfile(md,[model '.slx']);
simFile=fullfile(md,'simfile.sim');
suiteFile=fullfile(root,'results','vy_fixed_fusion_v2_5f_suite_plan.csv');
registryFile=fullfile(root,'results','vy_fixed_fusion_v2_5f_run_registry.csv');
planFile=fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5F_CALIBRATION_HOLDOUT_PLAN.md');
targetExpected='801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE';
preregExpected={ ...
    '97E3D7C9C3F35853372702A8CC545FEB02D9C182CEC012D47BA177D19673F230'; ...
    'AA3784A3CFCDAF8D048D743109477A773267140B693D71FF141E2E1BD58C489E'; ...
    '92B052D8450F432510C31035CDBE5A38BFE8CD7614691E3BE305D4D45CB9CFBE'};
acquisitionOrder=["FWCAL_C01" "FWCAL_C03" "FWCAL_C04" "FWCAL_C02" "FWCAL_C05"];

runId=upper(string(runId));
assert(isscalar(runId)&&any(runId==acquisitionOrder), ...
    'V25G:UnauthorizedRunId','Only preregistered CALIBRATION_ONLY IDs are authorized.');

suite=readtable(suiteFile,'TextType','string');
registry=readtable(registryFile,'TextType','string');
row=suite(suite.run_id==runId,:); reg=registry(registry.run_id==runId,:);
assert(height(row)==1&&height(reg)==1,'V25G:Registry','Run ID must resolve exactly once.');
assert(row.role=="CALIBRATION_ONLY"&&reg.role=="CALIBRATION_ONLY"&& ...
    row.status=="PLANNED_NOT_RUN"&&reg.status=="PLANNED_NOT_RUN"&& ...
    reg.role_immutable=="TRUE"&&reg.data_generated=="FALSE"&& ...
    reg.data_viewed=="FALSE"&&reg.alpha_status=="UNSELECTED", ...
    'V25G:Registry','Run is not an untouched CALIBRATION_ONLY registration.');
assert(row.waveform=="SINE_FRONT_EQUAL_REAR_ZERO"&& ...
    reg.planned_waveform=="SINE_FRONT_EQUAL_REAR_ZERO", ...
    'V25G:Registry','Registered waveform is not the authorized sine/front-only form.');

idx=find(acquisitionOrder==runId,1);
for k=1:idx-1
    p=registered_result(root,registry,acquisitionOrder(k));
    assert(isfile(p),'V25G:Order','Prior preregistered run %s is missing.',acquisitionOrder(k));
    q=load(p,'report');
    assert(isfield(q.report,'analysis')&&q.report.analysis.eligibleForCalibration, ...
        'V25G:Order','Prior run %s has not passed integrity analysis.',acquisitionOrder(k));
end
for k=idx+1:numel(acquisitionOrder)
    assert(~isfile(registered_result(root,registry,acquisitionOrder(k))), ...
        'V25G:Order','A later preregistered result already exists: %s.',acquisitionOrder(k));
end

resultFile=registered_result(root,registry,runId);
assert(~isfile(resultFile),'V25G:NoRetry', ...
    'Result already exists; overwrite/retry is prohibited: %s',resultFile);

amplitude=asnum(row.steer_amplitude_rad);
frequency=asnum(row.steer_frequency_Hz);
duration=asnum(row.duration_s);
sampleRate=asnum(row.estimator_rate_Hz);
assert(all(isfinite([amplitude frequency duration sampleRate]))&& ...
    amplitude==asnum(reg.planned_steer_amplitude_rad)&& ...
    frequency==asnum(reg.planned_steer_frequency_Hz)&& ...
    duration==asnum(reg.planned_duration_s)&&sampleRate==100&&duration==16, ...
    'V25G:Registry','Suite and registry numeric fields differ.');
assert(asnum(row.evaluation_start_s)==0&&asnum(row.evaluation_end_s)==16&& ...
    reg.evaluation_window_s=="[0_16]",'V25G:Registry','Evaluation window differs.');

preregFiles={planFile;suiteFile;registryFile};
report=struct();
report.stage='V2.5-G fixed-weight calibration acquisition';
report.runId=char(runId); report.role='CALIBRATION_ONLY';
report.runCard=struct('runId',char(runId),'model',target,'simfile',simFile, ...
    'speedScope','CURRENT_CARSIM_20_MPS_CLASS_NOT_RUNNER_PARAMETERIZED', ...
    'testSpeedAssignedByRunner',false,'steerAmplitudeRad',amplitude, ...
    'steerFrequencyHz',frequency,'waveform','SINE_FRONT_EQUAL_REAR_ZERO', ...
    'durationS',duration,'estimatorRateHz',sampleRate, ...
    'evaluationWindowS',[0 duration],'truthAlignmentRule',char(reg.truth_alignment_rule));
report.simCalled=false; report.runtimeAuthorizationConsumed=false;
report.simulationCompleted=false; report.carSimRun=false;
report.runtimeError=struct('identifier','','message','','report','');
report.raw=struct(); report.consoleText='';
report.preregistrationBefore=hash_files(preregFiles);
assert(hashes_match(report.preregistrationBefore,preregExpected), ...
    'V25G:Preregistration','Preregistration hash mismatch before runtime.');

[frozenFiles,expectedHashes]=frozen_manifest(root);
report.frozenBefore=hash_files(frozenFiles);
assert(hashes_match(report.frozenBefore,expectedHashes), ...
    'V25G:Frozen','Frozen hash mismatch before runtime.');
report.targetHashBefore=sha256(target);
assert(strcmpi(report.targetHashBefore,targetExpected)&& ...
    strcmpi(reg.model_sha256,targetExpected),'V25G:Frozen','Formal target hash mismatch.');

oldPwd=pwd; oldPath=path;
cleanupObj=onCleanup(@()cleanup(model,oldPwd,oldPath));
console='';
try
    solverDir='D:\carsim\CarSim2021.0_Prog\Programs\solvers';
    solverSfDir=fullfile(solverDir,'Matlab84+');
    solverDll=fullfile(solverDir,'carsim_64.dll');
    solverLibrary=fullfile(solverSfDir,'Solver_SF.slx');
    assert(isfile(simFile)&&isfile(solverDll)&&isfile(solverLibrary), ...
        'V25G:CarSim','Required D: CarSim runtime file is missing.');
    simText=fileread(simFile);
    report.carSim=struct('pwd','','activeSimfile',simFile, ...
        'progDir',macro_value(simText,'PROGDIR'),'dataDir',macro_value(simText,'DATADIR'), ...
        'solverExpected',solverDll,'solverActual','','gRequestBefore', ...
        contains(lower(simText),'g:\carsim'),'gRequestConsole',false);
    assert(strcmpi(report.carSim.progDir,'D:\carsim\CarSim2021.0_Prog\')&& ...
        strcmpi(report.carSim.dataDir,'D:\carsim\CarSim2021.0_Data\')&& ...
        ~report.carSim.gRequestBefore,'V25G:CarSim', ...
        'model/simfile.sim is not the accepted D: CarSim configuration.');

    addpath(md); addpath(solverDir); addpath(solverSfDir);
    cacheTag=lower(char(runId));
    Simulink.fileGenControl('set','CacheFolder', ...
        fullfile(tempdir,['vy_fixed_fusion_v2_5g_' cacheTag '_cache']), ...
        'CodeGenFolder',fullfile(tempdir,['vy_fixed_fusion_v2_5g_' cacheTag '_codegen']), ...
        'createDir',true);
    cd(md); report.carSim.pwd=pwd; report.carSim.activeSimfile=fullfile(pwd,'simfile.sim');
    assert(strcmpi(report.carSim.activeSimfile,simFile),'V25G:CarSim', ...
        'MATLAB cwd does not select model/simfile.sim.');
    load_system('Solver_SF'); load_system(target);

    report.static=static_preflight(model,amplitude,frequency);
    assert(report.static.pass,'V25G:Static','Target static preflight failed before sim().');
    report.weights=report.static.weights; report.fParameters=report.static.fParameters;

    w=get_param(model,'ModelWorkspace');
    assignin(w,'test_steer_amplitude',amplitude);
    assignin(w,'test_steer_frequency',frequency);
    assignin(w,'vy_v17_mode_code',20);
    assignin('base','test_steer_amplitude',amplitude);
    assignin('base','test_steer_frequency',frequency);
    assignin('base','vy_v17_mode_code',20);
    clear vy_dynamic_ekf_v1_17 vy_kinematic_kf

    logVariables={'steer_cmd_rad','steer_to_carsim_deg', ...
        'steer_fl_carsim_deg','steer_fr_carsim_deg','steer_rl_carsim_deg', ...
        'steer_rr_carsim_deg','reset_g0','avz_imu_g0','kkf_u_log1', ...
        'kkf_x_log1','kkf_P_log1','kkf_diag_log1','dekf_x_log', ...
        'dekf_P_log','dekf_diag_log','parallel_input_log','fusion_vy_d_log', ...
        'fusion_vy_k_log','fusion_vy_f_log','fusion_f_P_log', ...
        'fusion_f_diag_log','fusion_vy_fw_log','vy_true_log1','Vx_true_log'};
    report.logVariables=logVariables;
    assert(all(cellfun(@(n)numel(find_system(model,'SearchDepth',1, ...
        'BlockType','ToWorkspace','VariableName',n))==1,logVariables)), ...
        'V25G:Logging','A required calibration runtime log boundary is missing.');

    fprintf(['V25G_RUN_CARD|id=%s|role=CALIBRATION_ONLY|A=%.17g|f=%.17g|' ...
        'duration=%.17g|rate=%.17g|speedScope=%s|result=%s\n'], ...
        runId,amplitude,frequency,duration,sampleRate, ...
        report.runCard.speedScope,resultFile);
    report.simCalled=true; report.runtimeAuthorizationConsumed=true;
    console=evalc("out=sim(model,'StopTime',sprintf('%.17g',duration),"+ ...
        "'ReturnWorkspaceOutputs','on','FastRestart','off');");
    fprintf('%s',console); report.consoleText=console;
    report.carSim.solverActual=solver_path_from_console(console);
    report.carSim.gRequestConsole=contains(lower(console),'g:\carsim');
    report.carSimRun=contains(console,'Termination at simulation time')&& ...
        strcmpi(report.carSim.solverActual,solverDll)&&~report.carSim.gRequestConsole;
    assert(report.carSimRun,'V25G:CarSim','Authorized CarSim completion evidence is missing.');
    for k=1:numel(logVariables)
        name=logVariables{k}; report.raw.(name)=record_timeseries(out.get(name));
    end
    report.stopTimeActualS=max([report.raw.fusion_vy_d_log.time(end), ...
        report.raw.fusion_vy_k_log.time(end),report.raw.fusion_vy_f_log.time(end), ...
        report.raw.fusion_vy_fw_log.time(end)]);
    report.simulationCompleted=true;
catch ME
    report.consoleText=console;
    report.runtimeError.identifier=ME.identifier;
    report.runtimeError.message=ME.message;
    report.runtimeError.report=getReport(ME,'extended','hyperlinks','off');
end

cleanup(model,oldPwd,oldPath); clear cleanupObj
report.targetHashAfter=sha256(target);
report.targetHashUnchanged=strcmpi(report.targetHashBefore,report.targetHashAfter);
report.frozenAfter=hash_files(frozenFiles);
report.allFrozenHashesUnchanged=hashes_match(report.frozenAfter,expectedHashes);
report.preregistrationAfter=hash_files(preregFiles);
report.preregistrationUnchanged=hashes_equal(report.preregistrationBefore,report.preregistrationAfter)&& ...
    hashes_match(report.preregistrationAfter,preregExpected);
save(resultFile,'report','-v7.3');
if ~report.simulationCompleted
    error('V25G:RuntimeFailed','V2.5-G %s failed; evidence saved to %s',runId,resultFile);
end
assert(report.targetHashUnchanged&&report.allFrozenHashesUnchanged&& ...
    report.preregistrationUnchanged,'V25G:Integrity','A frozen/preregistered file changed.');
fprintf(['V25G_RUNTIME_OK|id=%s|simCalled=%d|completed=%d|carSim=%d|' ...
    'stop=%.17g|solver=%s|targetUnchanged=%d|preregUnchanged=%d\n'], ...
    runId,report.simCalled,report.simulationCompleted,report.carSimRun, ...
    report.stopTimeActualS,report.carSim.solverActual, ...
    report.targetHashUnchanged,report.preregistrationUnchanged);
end

function p=registered_result(root,registry,id)
r=registry(registry.run_id==string(id),:);assert(height(r)==1,'Registry row missing.');
p=fullfile(root,strrep(char(r.result_path_reserved),'/',filesep));
end

function v=asnum(x)
if isnumeric(x),v=double(x);else,v=str2double(string(x));end
assert(isscalar(v),'Expected one numeric registration value.');
end

function audit=static_preflight(m,amplitude,frequency)
fusion=[m '/Fixed Weight D K F Fusion']; fSub=[m '/F-Track 100Hz'];
params=parse_expr_list(get_param(fusion,'Parameters'));
fParams=parse_expr_list(get_param([fSub '/F-Track Stateful Boundary'],'Parameters'));
cmd=[m '/G0 Steer Cmd Rad']; gain=[m '/Gain22']; sw=[m '/Manual Switch1'];
fp=get_param(fusion,'PortHandles'); fsp=get_param(fSub,'PortHandles');
audit=struct();
audit.weights=struct('values',params,'alpha_D',params(1),'alpha_K',params(2), ...
    'alpha_F',params(3),'sum',sum(params), ...
    'classification','TEST-ONLY / NOT SELECTED / NOT TUNED / NOT FROZEN');
audit.fParameters=struct('Ts',fParams(1),'Vy_F0',fParams(2), ...
    'P0_F',fParams(3),'Q_F',fParams(4),'classification','UNTUNED / UNFROZEN');
audit.steering=struct('source',cmd,'amplitudeExpression',get_param(cmd,'Amplitude'), ...
    'frequencyExpression',get_param(cmd,'Frequency'),'gain',get_param(gain,'Gain'), ...
    'manualSwitchSetting',get_param(sw,'CurrentSetting'), ...
    'commandedAmplitudeRad',amplitude,'commandedFrequencyHz',frequency);
audit.fValidSource=source_of_port(fsp.Inport(6));
audit.fValidZero=strcmp(audit.fValidSource,[m '/F Feedback Valid Disabled'])&& ...
    str2double(get_param(audit.fValidSource,'Value'))==0;
audit.schedulers={source_of_trigger([m '/Parallel D-EKF 100Hz']), ...
    source_of_trigger([m '/K-KF 100Hz']),source_of_trigger(fSub)};
audit.schedulersIndependent=numel(unique(audit.schedulers))==3;
audit.schedulers100Hz=all(cellfun(@scheduler100,audit.schedulers));
audit.fusionSources=arrayfun(@source_of_port,fp.Inport,'UniformOutput',false);
audit.fusionSourcesExact=isequal(audit.fusionSources(:), ...
    {[m '/Fusion D State Select Vy'];[m '/Fusion K State Select Vy'];fSub});
audit.pass=isequal(params,[1/3 1/3 1/3])&&abs(sum(params)-1)<=1e-12&& ...
    fParams(1)==0.01&&fParams(3)==0.5&&fParams(4)==0.0025&& ...
    strcmp(audit.steering.amplitudeExpression,'test_steer_amplitude')&& ...
    strcmp(audit.steering.frequencyExpression,'2*pi*test_steer_frequency')&& ...
    strcmp(strtrim(audit.steering.gain),'180/pi')&& ...
    strcmp(audit.steering.manualSwitchSetting,'0')&&audit.fValidZero&& ...
    audit.schedulersIndependent&&audit.schedulers100Hz&&audit.fusionSourcesExact;
end

function x=parse_expr_list(s)
p=strsplit(s,',');x=zeros(1,numel(p));for k=1:numel(p),x(k)=str2num(p{k});end %#ok<ST2NM>
end
function tf=scheduler100(p)
tf=strcmp(get_param(p,'MaskType'),'Function-Call Generator')&& ...
    abs(str2double(get_param(p,'sample_time'))-0.01)<1e-15;
end
function src=source_of_port(p)
l=get_param(p,'Line');assert(l>0,'Unconnected input.');src=getfullname(get_param(l,'SrcBlockHandle'));
end
function src=source_of_trigger(b)
p=get_param(b,'PortHandles');src=source_of_port(p.Trigger(1));
end
function r=record_timeseries(ts)
assert(isa(ts,'timeseries'),'Expected timeseries, got %s.',class(ts));
r=struct('time',double(ts.Time(:)),'data',double(ts.Data), ...
    'sampleCount',numel(ts.Time),'dataSize',size(ts.Data));
end
function value=macro_value(text,key)
token=regexp(text,['(?m)^' key '\s+([^\r\n]+)'],'tokens','once');
assert(~isempty(token),'CarSim config entry missing: %s',key);value=strtrim(token{1});
end
function p=solver_path_from_console(text)
token=regexp(text,'Use vehicle solver:\s*([^\r\n]+)','tokens','once');
if isempty(token),p='';else,p=strtrim(token{1});end
end
function cleanup(m,oldPwd,oldPath)
if bdIsLoaded(m),close_system(m,0);end
if bdIsLoaded('Solver_SF'),close_system('Solver_SF',0);end
cd(oldPwd);path(oldPath);
evalin('base','clear test_steer_amplitude test_steer_frequency vy_v17_mode_code');
end
function [files,hashes]=frozen_manifest(root)
files={fullfile(root,'model','vx_vy_fixed_fusion_v2_5.slx'); ...
 fullfile(root,'model','vy_fixed_weight_fusion_simulink_sfun.m'); ...
 fullfile(root,'model','vy_fixed_weight_fusion_step.m'); ...
 fullfile(root,'model','vx_vy_parallel_dk_v2_3.slx'); ...
 fullfile(root,'model','vx_vy_dekf_v1_17.slx');fullfile(root,'model','vy_dynamic_ekf_v1_17.m'); ...
 fullfile(root,'model','vy_dynamic_ekf_step_v17.m');fullfile(root,'model','vy_dynamic_ekf_step_v13.m'); ...
 fullfile(root,'model','vx_vy_kkf_v2_1.slx');fullfile(root,'model','vx_vy_kkf_v2_1g_steer.slx'); ...
 fullfile(root,'model','vy_kinematic_kf_step.m');fullfile(root,'model','vy_kinematic_kf.m'); ...
 fullfile(root,'model','vx_vy_dkekf_v2_2.slx');fullfile(root,'model','vy_dkekf_baseline_step.m'); ...
 fullfile(root,'model','vy_dkekf_baseline.m');fullfile(root,'model','vy_dkekf_baseline_simulink_sfun.m'); ...
 fullfile(root,'model','vy_feedback_propagation_step.m'); ...
 fullfile(root,'model','vy_feedback_propagation_simulink_sfun.m'); ...
 fullfile(root,'model','vx_vy_feedback_track_v2_4.slx')};
hashes={'801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE'; ...
 'B7185A2E26B2874D792266D6CBAEC26A8DED6FDFBDFC862ACC394DE01F94F30A'; ...
 '4DE407D651FD3366357BFFF181FDB8474273E769982A18EFB96426FC05CC254C'; ...
 '98461DB290723A5CCDF62398CE5063DE0C9B6C7586334D479B159A771EB128C0'; ...
 '108F819DCD1B71FD6D795D7148CBF32FE1A888AE9878908E894A07626ED003AE'; ...
 '5550D0389FC4D1DCF7F65B0E00B4C51A949F2B9ADD33C2D78D1122A31291A1A0'; ...
 '4010F6A4BD669AC048297C2F416F0B8826F729F4552D73445703184F052C4A4F'; ...
 '498A446E13E654387E3D36BF4694A336E75B2100E765DAC0414A01367531CDE4'; ...
 'B67A98A6080374304E2D3424F85589C913E6EC4DB25BC9912CBFD2BC441C2712'; ...
 '59B25C5E350140AB0EAFD8345D5A9145D6981B96481023537A3BD01A787F728E'; ...
 '3786646EE5163D231DD8964614A8875217DFA496EB593B455E4E029E26DA2244'; ...
 'F242CB75BA08D22CB1EED87731746CF80D54FD39C1899B45E9980A40576414D4'; ...
 'E768FB2AD33A6EEAABDE2FB7C40BE660B78F350A90C752327DC9B423F50F2E15'; ...
 '6475B9DBC93EB6E25C2BB9FAD81CA11B2E08C26E7F2AE6A33C50E35B2790B457'; ...
 '7E731D7DF0BB2CA4455E3AA16E7513114E04472D38C62F1F453B631056306973'; ...
 '12F0D82643D65AA5098ED20C0655234F3A2E7EF6D6F5E7DEE5B80BC1A201BDA1'; ...
 '80C21D2CDC74F23C964DC50EAC48F2C026AD27027B160BB851B491E301D0E5FF'; ...
 '2FF7E488CC60DD729EC4948066714A95DAC15BBDB08BA45004EF6A7C8E1234B0'; ...
 '951A0D6E454F9C4C8ECD90EB4AD0372270F7D5EDCC15203B68D877C2ED27BF84'};
end
function records=hash_files(files)
records=repmat(struct('path','','sha256',''),numel(files),1);
for k=1:numel(files),records(k)=struct('path',files{k},'sha256',sha256(files{k}));end
end
function ok=hashes_match(records,expected)
ok=numel(records)==numel(expected);
for k=1:numel(records),ok=ok&&strcmpi(records(k).sha256,expected{k});end
end
function ok=hashes_equal(a,b)
ok=numel(a)==numel(b);
for k=1:numel(a),ok=ok&&strcmpi(a(k).path,b(k).path)&&strcmpi(a(k).sha256,b(k).sha256);end
end
function h=sha256(file)
d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));
ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());while ds.read()~=-1,end
b=typecast(d.digest(),'uint8');h=upper(reshape(dec2hex(b,2).',1,[]));clear c
end
