function report = run_vy_fixed_fusion_v2_5g1d_C01R1()
%RUN_VY_FIXED_FUSION_V2_5G1D_C01R1 One authorized 16-s C01R1 runtime.

root=fileparts(fileparts(mfilename('fullpath')));md=fullfile(root,'model');
model='vx_vy_fixed_fusion_v2_5';target=fullfile(md,[model '.slx']);
simFile=fullfile(md,'simfile.sim');
remediationFile=fullfile(root,'results','vy_fixed_fusion_v2_5g1c_remediation_registry.csv');
originalRegistryFile=fullfile(root,'results','vy_fixed_fusion_v2_5f_run_registry.csv');
resultFile=fullfile(root,'results','vy_fixed_fusion_v2_5g_FWCAL_C01R1.mat');
targetExpected='801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE';
expectedFreshPrefdir='C:\Users\21180\AppData\Roaming\MathWorks\MATLAB\R2024a';

% Registry is the sole maneuver source; prompt values are cross-checks only.
remediation=readtable(remediationFile,'TextType','string','VariableNamingRule','preserve', ...
    'Delimiter',',');
reg=remediation(remediation.("run_id")=="FWCAL_C01R1",:);
original=readtable(originalRegistryFile,'TextType','string','VariableNamingRule','preserve', ...
    'Delimiter',',');
orig=original(original.("run_id")=="FWCAL_C01",:);
assert(height(reg)==1&&height(orig)==1,'V25G1D:Registry','C01R1/C01 lineage must resolve once.');
assert(reg.role=="CALIBRATION_ONLY"&&reg.status=="PLANNED_NOT_RUN"&& ...
    reg.future_sim_authorization_status=="NOT_YET_AUTHORIZED"&& ...
    reg.replaces_run_id=="FWCAL_C01"&&reg.replacement_generation==1&& ...
    reg.condition_changed_from_original=="NO"&& ...
    reg.performance_based_condition_change=="NO", ...
    'V25G1D:Registry','C01R1 preregistration state/lineage differs.');
amplitude=asnum(reg.planned_amplitude_rad);frequency=asnum(reg.planned_frequency_hz);
duration=asnum(reg.planned_duration_s);rate=asnum(reg.planned_estimator_rate_hz);
assert(amplitude==asnum(orig.planned_steer_amplitude_rad)&& ...
    frequency==asnum(orig.planned_steer_frequency_Hz)&& ...
    duration==asnum(orig.planned_duration_s)&&rate==asnum(orig.planned_sample_rate_Hz)&& ...
    amplitude==0.02&&frequency==0.30&&duration==16&&rate==100, ...
    'V25G1D:Registry','C01R1 numeric condition is not exact original C01.');
assert(reg.waveform=="sine"&&reg.front_steering_policy=="FL_FR_SAME_PHASE"&& ...
    reg.rear_steering_policy=="RL_RR_ZERO"&& ...
    reg.truth_alignment_rule==orig.truth_alignment_rule&& ...
    reg.evaluation_window_rule==orig.evaluation_window_s&& ...
    reg.model_sha256==targetExpected,'V25G1D:Registry','C01R1 inherited policy differs.');
registeredResult=fullfile(root,strrep(char(reg.result_path_reserved),'/',filesep));
assert(strcmpi(registeredResult,resultFile)&&~isfile(resultFile), ...
    'V25G1D:ResultPath','Reserved result path differs or already exists.');

% External live-process gate was measured immediately before this MATLAB start.
assert(evalin('base','exist(''g1d_prelaunch_live_matlab_count'',''var'')==1')&& ...
    evalin('base','g1d_prelaunch_live_matlab_count')==0, ...
    'V25G1D:ProcessGate','Prelaunch live MATLAB count gate is absent/nonzero.');

prefEnv=getenv('MATLAB_PREFDIR');activePref=prefdir;
report=struct();report.stage='V2.5-G1D FWCAL_C01R1 acquisition';
report.runId='FWCAL_C01R1';report.role='CALIBRATION_ONLY';
report.replacesRunId='FWCAL_C01';report.replacementGeneration=1;
report.resultPath=resultFile;report.resultPathPreRunAbsent=true;
report.matlabStartup=struct('version',version,'startupGateReached',true);
report.matlabPrefdir=struct('environmentValue',prefEnv,'activeValue',activePref, ...
    'expectedFreshValue',expectedFreshPrefdir,'environmentUnset',isempty(prefEnv), ...
    'activeExact',strcmpi(activePref,expectedFreshPrefdir));
assert(report.matlabPrefdir.environmentUnset&&report.matlabPrefdir.activeExact, ...
    'V25G1D:PREFDIR','Fresh default PREFDIR policy failed.');
report.runCard=struct('runId','FWCAL_C01R1','role','CALIBRATION_ONLY', ...
    'replacesRunId','FWCAL_C01','plannedAmplitudeRad',amplitude, ...
    'commandedAmplitudeRad',amplitude,'plannedFrequencyHz',frequency, ...
    'commandedFrequencyHz',frequency,'plannedDurationS',duration, ...
    'stopTimeS',duration,'plannedEstimatorRateHz',rate, ...
    'waveform',char(reg.waveform),'frontSteeringPolicy',char(reg.front_steering_policy), ...
    'rearSteeringPolicy',char(reg.rear_steering_policy),'speedScope',char(reg.speed_scope), ...
    'truthAlignmentRule',char(reg.truth_alignment_rule), ...
    'evaluationWindowRule',char(reg.evaluation_window_rule),'targetPath',target, ...
    'targetSHA256',targetExpected,'activePREFDIR',activePref,'resultPath',resultFile, ...
    'testSpeedAssignedByRunner',false);
report.simCalled=false;report.simCallCount=0;report.runtimeAuthorizationConsumed=false;
report.simulationCompleted=false;report.carSimRun=false;report.raw=struct();
report.consoleText='';report.runtimeError=struct('identifier','','message','','report','');

% Immutable preregistration/history evidence.
preregFiles={fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5F_CALIBRATION_HOLDOUT_PLAN.md'); ...
 fullfile(root,'results','vy_fixed_fusion_v2_5f_suite_plan.csv');originalRegistryFile; ...
 fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G_STATUS.md');remediationFile; ...
 fullfile(root,'results','vy_fixed_fusion_v2_5g1c_preregistration_gates.csv'); ...
 fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1C_C01_REPLACEMENT_PREREGISTRATION.md'); ...
 fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1B_R4_STATUS.md'); ...
 fullfile(root,'results','vy_fixed_fusion_v2_5g1b_recovery_diagnostic.mat'); ...
 fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1B_RECOVERY_DIAGNOSTIC_STATUS.md')};
preregHashes={'97E3D7C9C3F35853372702A8CC545FEB02D9C182CEC012D47BA177D19673F230'; ...
 'AA3784A3CFCDAF8D048D743109477A773267140B693D71FF141E2E1BD58C489E'; ...
 '92B052D8450F432510C31035CDBE5A38BFE8CD7614691E3BE305D4D45CB9CFBE'; ...
 '371A6961A63742B75A34A1DD6F9715D610BA3C5DA422B86F1AD125D0ED9062F9'; ...
 'C112249565DB5DCBAFE0A04D27FA7593E6F427DB26072CD3803D7E9E70D4E7A7'; ...
 '40676D452D47483644EA87FFE61ADFDBC942ECBD052D631875F368307DA18CAB'; ...
 '29442D6A5194C799198C3ED8BC97520154EB02774DAED8671A471D5C6B19746C'; ...
 'A91D13C0B59227DE85085D22767BEA9B1FDA411EB83BF3302B27881B2BE0CD2A'; ...
 '030CE3FDE238641D046D9DC9DABF07AFE75BB00F38CB12E0181F6755C4A7CC12'; ...
 '4C3EA774732CDB163B32BC39A7AE93D1BE38F922C69E7BD8DBC557EBB2CAA6C7'};
report.preregistrationBefore=hash_files(preregFiles);
assert(hashes_match(report.preregistrationBefore,preregHashes), ...
    'V25G1D:Preregistration','Historical/preregistration hash mismatch.');
[frozenFiles,frozenHashes]=frozen_manifest(root);report.frozenBefore=hash_files(frozenFiles);
assert(hashes_match(report.frozenBefore,frozenHashes),'V25G1D:Frozen','Frozen hash mismatch.');
report.targetHashBefore=sha256(target);
assert(strcmpi(report.targetHashBefore,targetExpected),'V25G1D:Frozen','Target hash mismatch.');

oldPwd=pwd;oldPath=path;cleanupObj=onCleanup(@()cleanup(model,oldPwd,oldPath));
console='';
try
    solverDir='D:\carsim\CarSim2021.0_Prog\Programs\solvers';
    solverSfDir=fullfile(solverDir,'Matlab84+');solverDll=fullfile(solverDir,'carsim_64.dll');
    solverMex=fullfile(solverSfDir,'vs_sf.mexw64');solverLibrary=fullfile(solverSfDir,'Solver_SF.slx');
    assert(isfile(simFile)&&isfile(solverDll)&&isfile(solverMex)&&isfile(solverLibrary), ...
        'V25G1D:CarSim','Required D: CarSim file missing.');
    simText=fileread(simFile);report.carSim=struct('pwd','','activeSimfile',simFile, ...
        'simfileSHA256',sha256(simFile),'progDir',macro_value(simText,'PROGDIR'), ...
        'dataDir',macro_value(simText,'DATADIR'),'solverExpected',solverDll,'solverActual','', ...
        'mexExpected',solverMex,'mexActual','','gRequestBefore',contains(lower(simText),'g:\carsim'), ...
        'gRequestConsole',false);
    assert(strcmpi(report.carSim.simfileSHA256, ...
        'A50912CE50F59B216A4CF939228E63A0F27B9818C52A2ABE493345C53FA7A2EA')&& ...
        strcmpi(report.carSim.progDir,'D:\carsim\CarSim2021.0_Prog\')&& ...
        strcmpi(report.carSim.dataDir,'D:\carsim\CarSim2021.0_Data\')&& ...
        ~report.carSim.gRequestBefore,'V25G1D:CarSim','simfile policy mismatch.');
    addpath(md);addpath(solverDir);addpath(solverSfDir);
    Simulink.fileGenControl('set','CacheFolder',fullfile(tempdir,'vy_fixed_fusion_v2_5d_cache'), ...
        'CodeGenFolder',fullfile(tempdir,'vy_fixed_fusion_v2_5d_codegen'),'createDir',true);
    cd(md);report.carSim.pwd=pwd;report.carSim.activeSimfile=fullfile(pwd,'simfile.sim');
    report.carSim.mexActual=which('vs_sf');
    assert(strcmpi(pwd,md)&&strcmpi(report.carSim.activeSimfile,simFile)&& ...
        strcmpi(report.carSim.mexActual,solverMex),'V25G1D:Environment','cwd/simfile/MEX gate failed.');
    load_system('Solver_SF');load_system(target);
    report.static=static_preflight(model);assert(report.static.pass,'V25G1D:Static','Static gate failed.');
    report.weights=report.static.weights;report.fParameters=report.static.fParameters;
    w=get_param(model,'ModelWorkspace');
    assignin(w,'test_steer_amplitude',amplitude);assignin(w,'test_steer_frequency',frequency);
    assignin(w,'vy_v17_mode_code',20);assignin('base','test_steer_amplitude',amplitude);
    assignin('base','test_steer_frequency',frequency);assignin('base','vy_v17_mode_code',20);
    clear vy_dynamic_ekf_v1_17 vy_kinematic_kf
    logs={'steer_cmd_rad','steer_to_carsim_deg','steer_fl_carsim_deg', ...
        'steer_fr_carsim_deg','steer_rl_carsim_deg','steer_rr_carsim_deg', ...
        'reset_g0','avz_imu_g0','kkf_u_log1','kkf_x_log1','kkf_P_log1', ...
        'kkf_diag_log1','dekf_x_log','dekf_P_log','dekf_diag_log','parallel_input_log', ...
        'fusion_vy_d_log','fusion_vy_k_log','fusion_vy_f_log','fusion_f_P_log', ...
        'fusion_f_diag_log','fusion_vy_fw_log','vy_true_log1','Vx_true_log'};
    report.logVariables=logs;
    assert(all(cellfun(@(n)numel(find_system(model,'SearchDepth',1,'BlockType','ToWorkspace', ...
        'VariableName',n))==1,logs)),'V25G1D:Logging','Required log boundary missing.');
    report.immediatePreSim=struct('pwd',pwd,'activeSimfile',report.carSim.activeSimfile, ...
        'simfileSHA256',sha256(report.carSim.activeSimfile),'progDir',report.carSim.progDir, ...
        'dataDir',report.carSim.dataDir,'solver',solverDll,'mex',which('vs_sf'), ...
        'activePREFDIR',prefdir,'MATLAB_PREFDIR',getenv('MATLAB_PREFDIR'), ...
        'plannedAmplitude',amplitude,'commandedAmplitude',amplitude, ...
        'plannedFrequency',frequency,'commandedFrequency',frequency, ...
        'plannedDuration',duration,'StopTime',duration,'plannedRate',rate);
    assert(strcmpi(report.immediatePreSim.pwd,md)&& ...
        strcmpi(report.immediatePreSim.activeSimfile,simFile)&& ...
        strcmpi(report.immediatePreSim.solver,solverDll)&&strcmpi(report.immediatePreSim.mex,solverMex)&& ...
        strcmpi(report.immediatePreSim.activePREFDIR,expectedFreshPrefdir)&& ...
        isempty(report.immediatePreSim.MATLAB_PREFDIR)&& ...
        report.immediatePreSim.plannedAmplitude==report.immediatePreSim.commandedAmplitude&& ...
        report.immediatePreSim.plannedFrequency==report.immediatePreSim.commandedFrequency&& ...
        report.immediatePreSim.plannedDuration==report.immediatePreSim.StopTime, ...
        'V25G1D:ImmediatePreSim','Immediate pre-sim gate failed.');
    fprintf(['G1D_RUN_CARD|run_id=%s|role=%s|replaces=%s|plannedA=%.17g|commandedA=%.17g|' ...
        'plannedF=%.17g|commandedF=%.17g|plannedDuration=%.17g|StopTime=%.17g|' ...
        'rate=%.17g|waveform=%s|front=%s|rear=%s|speed=%s|targetHash=%s|' ...
        'prefdir=%s|cwd=%s|simfile=%s|solver=%s|mex=%s|result=%s\n'], ...
        report.runId,report.role,report.replacesRunId,amplitude,amplitude,frequency,frequency, ...
        duration,duration,rate,report.runCard.waveform,report.runCard.frontSteeringPolicy, ...
        report.runCard.rearSteeringPolicy,report.runCard.speedScope,targetExpected,activePref, ...
        pwd,report.carSim.activeSimfile,solverDll,solverMex,resultFile);

    report.simCalled=true;report.simCallCount=1;report.runtimeAuthorizationConsumed=true;
    console=evalc("out=sim(model,'StopTime',sprintf('%.17g',duration),"+ ...
        "'ReturnWorkspaceOutputs','on','FastRestart','off');");
    fprintf('%s',console);report.consoleText=console;
    report.carSim.solverActual=solver_path_from_console(console);
    report.carSim.gRequestConsole=contains(lower(console),'g:\carsim');
    report.carSimRun=contains(console,'Termination at simulation time')&& ...
        strcmpi(report.carSim.solverActual,solverDll)&&~report.carSim.gRequestConsole;
    assert(report.carSimRun,'V25G1D:CarSim','CarSim completion evidence missing.');
    for k=1:numel(logs),name=logs{k};report.raw.(name)=record_timeseries(out.get(name));end
    report.stopTimeActualS=max([report.raw.fusion_vy_d_log.time(end), ...
        report.raw.fusion_vy_k_log.time(end),report.raw.fusion_vy_f_log.time(end), ...
        report.raw.fusion_vy_fw_log.time(end)]);
    report.simulationCompleted=true;
catch ME
    report.consoleText=console;report.runtimeError.identifier=ME.identifier;
    report.runtimeError.message=ME.message;report.runtimeError.report=getReport(ME,'extended','hyperlinks','off');
end

cleanup(model,oldPwd,oldPath);clear cleanupObj
report.targetHashAfter=sha256(target);report.targetHashUnchanged=strcmpi(report.targetHashBefore,report.targetHashAfter);
report.frozenAfter=hash_files(frozenFiles);report.allFrozenHashesUnchanged=hashes_match(report.frozenAfter,frozenHashes);
report.preregistrationAfter=hash_files(preregFiles);
report.preregistrationUnchanged=hashes_equal(report.preregistrationBefore,report.preregistrationAfter)&& ...
    hashes_match(report.preregistrationAfter,preregHashes);
if report.simulationCompleted
    [analysis,dataset]=analyze_vy_fixed_fusion_v2_5g1d_C01R1(report,reg);
    report.analysis=analysis;
    save(resultFile,'report','dataset','-v7.3');
else
    save(resultFile,'report','-v7.3');
end
resultHash=sha256(resultFile);info=dir(resultFile);
fprintf(['G1D_RUNTIME_EVIDENCE|id=%s|simCalled=%d|simCount=%d|completed=%d|carSim=%d|' ...
    'stop=%.17g|solver=%s|targetUnchanged=%d|preregUnchanged=%d|' ...
    'resultHash=%s|bytes=%d\n'],report.runId,report.simCalled,report.simCallCount, ...
    report.simulationCompleted,report.carSimRun,getfield_default(report,'stopTimeActualS',NaN), ...
    getfield_default(report.carSim,'solverActual',''),report.targetHashUnchanged, ...
    report.preregistrationUnchanged,resultHash,info.bytes);
if ~report.simulationCompleted
    error('V25G1D:RuntimeFailed','C01R1 runtime failed after authorization consumption: %s', ...
        report.runtimeError.message);
end
assert(report.analysis.passed&&report.targetHashUnchanged&&report.allFrozenHashesUnchanged&& ...
    report.preregistrationUnchanged,'V25G1D:Integrity','Runtime/data-integrity gate failed.');
fprintf('G1D_RUNTIME_OK|id=%s|eligible=%d|sim=1\n',report.runId,report.analysis.eligibleForCalibration);
end

function audit=static_preflight(m)
fusion=[m '/Fixed Weight D K F Fusion'];fSub=[m '/F-Track 100Hz'];
fp=get_param(fusion,'PortHandles');fsp=get_param(fSub,'PortHandles');
params=parse_expr_list(get_param(fusion,'Parameters'));
fParams=parse_expr_list(get_param([fSub '/F-Track Stateful Boundary'],'Parameters'));
audit=struct();audit.weights=struct('values',params,'alpha_D',params(1),'alpha_K',params(2), ...
    'alpha_F',params(3),'classification','TEST-ONLY / UNSELECTED');
audit.fParameters=struct('Ts',fParams(1),'Vy_F0',fParams(2),'P0_F',fParams(3),'Q_F',fParams(4));
audit.fusionSources=arrayfun(@source_of_port,fp.Inport,'UniformOutput',false);
audit.fusionSourcesExact=isequal(audit.fusionSources(:), ...
    {[m '/Fusion D State Select Vy'];[m '/Fusion K State Select Vy'];fSub});
audit.fValidSource=source_of_port(fsp.Inport(6));
audit.fValidZero=strcmp(audit.fValidSource,[m '/F Feedback Valid Disabled'])&& ...
    str2double(get_param(audit.fValidSource,'Value'))==0;
audit.schedulers={source_of_trigger([m '/Parallel D-EKF 100Hz']), ...
    source_of_trigger([m '/K-KF 100Hz']),source_of_trigger(fSub)};
audit.schedulers100Hz=all(cellfun(@scheduler100,audit.schedulers));
audit.schedulersIndependent=numel(unique(audit.schedulers))==3;
cmd=[m '/G0 Steer Cmd Rad'];gain=[m '/Gain22'];sw=[m '/Manual Switch1'];
audit.steering=struct('amplitude',get_param(cmd,'Amplitude'),'frequency',get_param(cmd,'Frequency'), ...
    'gain',get_param(gain,'Gain'),'switch',get_param(sw,'CurrentSetting'));
audit.noOnlineTrueVy=audit.fusionSourcesExact;
audit.noP_FW=numel(fp.Outport)==1&&isempty(find_system(m,'SearchDepth',1,'BlockType','ToWorkspace','VariableName','P_FW'));
audit.noCovarianceFusion=numel(fp.Inport)==3&&audit.fusionSourcesExact;
audit.noFeedbackClosure=audit.fValidZero;
audit.pass=isequal(params,[1/3 1/3 1/3])&&fParams(1)==0.01&&fParams(3)==0.5&& ...
    fParams(4)==0.0025&&audit.fusionSourcesExact&&audit.fValidZero&& ...
    audit.schedulers100Hz&&audit.schedulersIndependent&& ...
    strcmp(audit.steering.amplitude,'test_steer_amplitude')&& ...
    strcmp(audit.steering.frequency,'2*pi*test_steer_frequency')&& ...
    strcmp(strtrim(audit.steering.gain),'180/pi')&&strcmp(audit.steering.switch,'0')&& ...
    audit.noOnlineTrueVy&&audit.noP_FW&&audit.noCovarianceFusion&&audit.noFeedbackClosure;
end
function x=parse_expr_list(s)
p=strsplit(s,',');x=zeros(1,numel(p));for k=1:numel(p),x(k)=str2num(p{k});end %#ok<ST2NM>
end
function tf=scheduler100(p)
tf=strcmp(get_param(p,'MaskType'),'Function-Call Generator')&&abs(str2double(get_param(p,'sample_time'))-0.01)<1e-15;
end
function src=source_of_port(p)
l=get_param(p,'Line');assert(l>0,'Unconnected input.');src=getfullname(get_param(l,'SrcBlockHandle'));
end
function src=source_of_trigger(b),p=get_param(b,'PortHandles');src=source_of_port(p.Trigger(1));end
function r=record_timeseries(ts)
assert(isa(ts,'timeseries'),'Expected timeseries.');r=struct('time',double(ts.Time(:)), ...
    'data',double(ts.Data),'sampleCount',numel(ts.Time),'dataSize',size(ts.Data));
end
function value=macro_value(text,key)
t=regexp(text,['(?m)^' key '\s+([^\r\n]+)'],'tokens','once');assert(~isempty(t),'Missing %s',key);value=strtrim(t{1});
end
function p=solver_path_from_console(text)
t=regexp(text,'Use vehicle solver:\s*([^\r\n]+)','tokens','once');if isempty(t),p='';else,p=strtrim(t{1});end
end
function cleanup(m,oldPwd,oldPath)
if bdIsLoaded(m),close_system(m,0);end;if bdIsLoaded('Solver_SF'),close_system('Solver_SF',0);end
cd(oldPwd);path(oldPath);evalin('base','clear test_steer_amplitude test_steer_frequency vy_v17_mode_code');
end
function v=asnum(x),if isnumeric(x),v=double(x);else,v=str2double(string(x));end;assert(isscalar(v));end
function v=getfield_default(s,f,d),if isfield(s,f),v=s.(f);else,v=d;end,end
function [files,hashes]=frozen_manifest(root)
files={fullfile(root,'model','vx_vy_fixed_fusion_v2_5.slx'); ...
 fullfile(root,'model','vy_fixed_weight_fusion_simulink_sfun.m');fullfile(root,'model','vy_fixed_weight_fusion_step.m'); ...
 fullfile(root,'model','vx_vy_parallel_dk_v2_3.slx');fullfile(root,'model','vx_vy_dekf_v1_17.slx'); ...
 fullfile(root,'model','vy_dynamic_ekf_v1_17.m');fullfile(root,'model','vy_dynamic_ekf_step_v17.m'); ...
 fullfile(root,'model','vy_dynamic_ekf_step_v13.m');fullfile(root,'model','vx_vy_kkf_v2_1.slx'); ...
 fullfile(root,'model','vx_vy_kkf_v2_1g_steer.slx');fullfile(root,'model','vy_kinematic_kf_step.m'); ...
 fullfile(root,'model','vy_kinematic_kf.m');fullfile(root,'model','vx_vy_dkekf_v2_2.slx'); ...
 fullfile(root,'model','vy_dkekf_baseline_step.m');fullfile(root,'model','vy_dkekf_baseline.m'); ...
 fullfile(root,'model','vy_dkekf_baseline_simulink_sfun.m');fullfile(root,'model','vy_feedback_propagation_step.m'); ...
 fullfile(root,'model','vy_feedback_propagation_simulink_sfun.m');fullfile(root,'model','vx_vy_feedback_track_v2_4.slx')};
hashes={'801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE'; ...
 'B7185A2E26B2874D792266D6CBAEC26A8DED6FDFBDFC862ACC394DE01F94F30A'; ...
 '4DE407D651FD3366357BFFF181FDB8474273E769982A18EFB96426FC05CC254C'; ...
 '98461DB290723A5CCDF62398CE5063DE0C9B6C7586334D479B159A771EB128C0'; ...
 '108F819DCD1B71FD6D795D7148CBF32FE1A888AE9878908E894A07626ED003AE'; ...
 '5550D0389FC4D1DCF7F65B0E00B4C51A949F2B9ADD33C2D78D1122A31291A1A0'; ...
 '4010F6A4BD669AC048297C2F416F0B8826F729F4552D73445703184F052C4A4F'; ...
 '498A446E13E654387E3D36BF4694A336E75B2100E765DAC0414A01367531CDE4'; ...
 'B67A98A6080374304E2D3424F85589C913E6EC4DB25BC9912CBFD2BC441C2712'; ...
 '59B25C5E350140AB0EAFD8345D5A9145D6981B96481023537A3BD01A787F728E'; ...
 '3786646EE5163D231DD8964614A8875217DFA496EB593B455E4E029E26DA2244'; ...
 'F242CB75BA08D22CB1EED87731746CF80D54FD39C1899B45E9980A40576414D4'; ...
 'E768FB2AD33A6EEAABDE2FB7C40BE660B78F350A90C752327DC9B423F50F2E15'; ...
 '6475B9DBC93EB6E25C2BB9FAD81CA11B2E08C26E7F2AE6A33C50E35B2790B457'; ...
 '7E731D7DF0BB2CA4455E3AA16E7513114E04472D38C62F1F453B631056306973'; ...
 '12F0D82643D65AA5098ED20C0655234F3A2E7EF6D6F5E7DEE5B80BC1A201BDA1'; ...
 '80C21D2CDC74F23C964DC50EAC48F2C026AD27027B160BB851B491E301D0E5FF'; ...
 '2FF7E488CC60DD729EC4948066714A95DAC15BBDB08BA45004EF6A7C8E1234B0'; ...
 '951A0D6E454F9C4C8ECD90EB4AD0372270F7D5EDCC15203B68D877C2ED27BF84'};
end
function r=hash_files(files)
r=repmat(struct('path','','sha256',''),numel(files),1);for k=1:numel(files),r(k)=struct('path',files{k},'sha256',sha256(files{k}));end
end
function ok=hashes_match(r,e),ok=numel(r)==numel(e);for k=1:numel(r),ok=ok&&strcmpi(r(k).sha256,e{k});end,end
function ok=hashes_equal(a,b),ok=numel(a)==numel(b);for k=1:numel(a),ok=ok&&strcmpi(a(k).path,b(k).path)&&strcmpi(a(k).sha256,b(k).sha256);end,end
function h=sha256(file)
d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));
ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());while ds.read()~=-1,end
b=typecast(d.digest(),'uint8');h=upper(reshape(dec2hex(b,2).',1,[]));clear c
end
