function report = run_vy_fixed_fusion_v2_5g2_remaining_calibration(runId)
%RUN_VY_FIXED_FUSION_V2_5G2_REMAINING_CALIBRATION Run one registered G2 case.
% One invocation accepts exactly one of FWCAL_C02..C05 and contains exactly
% one sim() call site.  The caller must start a new MATLAB process only after
% the preceding registered case has produced eligible immutable evidence.

runId=upper(string(runId));
allowed=["FWCAL_C02";"FWCAL_C03";"FWCAL_C04";"FWCAL_C05"];
assert(isscalar(runId)&&any(runId==allowed),'V25G2:RunId','Run ID must be FWCAL_C02..C05.');
root=fileparts(fileparts(mfilename('fullpath')));md=fullfile(root,'model');
model='vx_vy_fixed_fusion_v2_5';target=fullfile(md,[model '.slx']);
simFile=fullfile(md,'simfile.sim');
suiteFile=fullfile(root,'results','vy_fixed_fusion_v2_5f_suite_plan.csv');
registryFile=fullfile(root,'results','vy_fixed_fusion_v2_5f_run_registry.csv');
targetExpected='801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE';
expectedFreshPrefdir='C:\Users\21180\AppData\Roaming\MathWorks\MATLAB\R2024a';
q04Quarantine='D:\SystemMigration\Temp\V25G2_R3_TARGETED_PREFDIR_QUARANTINE_SET1_20260829T012500Z\epfwk_cache-24.1.0.2537033-7203099541395556032.json';
q04Expected='95464B5EEE5B786BB6A910F2765B15DB11A79644DC0F7F12BC6724149E8AE65B';
set2Quarantine='D:\SystemMigration\Temp\V25G2_R4_TARGETED_PREFDIR_QUARANTINE_SET2_20260829T024814Z\ddux\schemas\SL_PERFORMANCE_STARTUP.jsonrsa';
set2Expected='30677E244B75BB3469E1937848E92D4F1C850988B453AFB93F4510DBD59C996E';
activeQ04=fullfile(expectedFreshPrefdir,'epfwk_cache-24.1.0.2537033-7203099541395556032.json');
activeSet2=fullfile(expectedFreshPrefdir,'ddux','schemas','SL_PERFORMANCE_STARTUP.jsonrsa');
remediationFile=fullfile(root,'results','vy_fixed_fusion_v2_5g2_C02_presim_remediation_registry.csv');

% Original V2.5-F registry is the only condition source.
registry=readtable(registryFile,'TextType','string','VariableNamingRule','preserve','Delimiter',',');
suite=readtable(suiteFile,'TextType','string','VariableNamingRule','preserve','Delimiter',','); %#ok<NASGU>
remaining=registry(registry.role=="CALIBRATION_ONLY"&registry.status=="PLANNED_NOT_RUN"& ...
    ismember(registry.run_id,allowed),:);
assert(height(remaining)==4&&isequal(remaining.run_id(:),allowed), ...
    'V25G2:Registry','Remaining unrun calibration IDs/order must be C02,C03,C04,C05.');
rowIndex=find(registry.run_id==runId);
assert(isscalar(rowIndex),'V25G2:Registry','Requested run must resolve to one original row.');
reg=registry(rowIndex,:);
assert(reg.role=="CALIBRATION_ONLY"&&reg.role_immutable=="TRUE"&& ...
    reg.status=="PLANNED_NOT_RUN"&&reg.data_generated=="FALSE"&& ...
    reg.data_viewed=="FALSE"&&reg.alpha_status=="UNSELECTED", ...
    'V25G2:Registry','Requested row is not pristine CALIBRATION_ONLY preregistration.');

amplitude=asnum(reg.planned_steer_amplitude_rad);
frequency=asnum(reg.planned_steer_frequency_Hz);
duration=asnum(reg.planned_duration_s);rate=asnum(reg.planned_sample_rate_Hz);
assert(amplitude>0&&frequency>0&&duration>0&&rate==100&& ...
    reg.planned_waveform=="SINE_FRONT_EQUAL_REAR_ZERO"&& ...
    reg.vx_control_mode=="CURRENT_CARSIM_20_MPS_CLASS_NOT_RUNNER_PARAMETERIZED"&& ...
    reg.truth_alignment_rule=="TRUTH_TO_COMMON_100HZ_GRID_LINEAR_NO_EXTRAPOLATION_NO_SHIFT", ...
    'V25G2:Registry','Requested preregistered maneuver/policy is unsupported or altered.');
originalReservedFile=fullfile(root,strrep(char(reg.result_path_reserved),'/',filesep));
resultFile=formal_result_path(root,reg,remediationFile);
if runId=="FWCAL_C02"
    remediation=readtable(remediationFile,'TextType','string','VariableNamingRule','preserve','Delimiter',',');
    rem=remediation(remediation.run_id==runId,:);
    assert(height(rem)==1&&rem.original_preregistered_run_id==runId&& ...
        rem.maneuver_changed=="NO"&&rem.sim_called_before_remediation=="NO"&& ...
        rem.runtime_authorization_status=="UNCONSUMED"&&rem.run_id_changed=="NO"&& ...
        rem.replacement_run_created=="NO"&& ...
        rem.original_artifact_role=="PRE_SIM_FAILURE_EVIDENCE"&& ...
        rem.original_artifact_usable_for_calibration=="NO"&& ...
        rem.SET2_prelaunch_policy=="MUST_BE_ABSENT"&& ...
        rem.SET2_poststartup_regeneration_policy=="ALLOWED_WITH_PROVENANCE", ...
        'V25G2:Remediation','C02 append-only remediation registration is missing or altered.');
    assert(isfile(originalReservedFile)&&strcmpi(sha256(originalReservedFile), ...
        char(rem.original_artifact_sha256)),'V25G2:Remediation', ...
        'Preserved C02 pre-sim failure evidence is missing or changed.');
end
assert(~isfile(resultFile),'V25G2:ResultPath','Formal runtime result path already exists: %s',resultFile);

% External process gate is measured before launching this MATLAB process.
assert(evalin('base','exist(''g2_prelaunch_live_matlab_count'',''var'')==1')&& ...
    evalin('base','g2_prelaunch_live_matlab_count')==0, ...
    'V25G2:ProcessGate','Prelaunch live MATLAB count gate is absent/nonzero.');
assert(evalin('base','exist(''g2_prefdir_user_unset'',''var'')==1')&& ...
    evalin('base','exist(''g2_prefdir_machine_unset'',''var'')==1')&& ...
    evalin('base','g2_prefdir_user_unset')&&evalin('base','g2_prefdir_machine_unset'), ...
    'V25G2:PREFDIR','Prelaunch User/Machine MATLAB_PREFDIR gate is absent or failed.');
assert(evalin('base','exist(''g2_prelaunch_set2_absent'',''var'')==1')&& ...
    evalin('base','g2_prelaunch_set2_absent')&&~isfile(activeSet2), ...
    'V25G2:SET2Prelaunch','SET-2 must be absent before MATLAB launch and at runner entry.');
assert(evalin('base','exist(''g2_prelaunch_utc'',''var'')==1'), ...
    'V25G2:SET2Prelaunch','Prelaunch UTC provenance marker is missing.');

% C01R1 and all earlier G2 results must be immutable/eligible; later results absent.
c01r1=fullfile(root,'results','vy_fixed_fusion_v2_5g_FWCAL_C01R1.mat');
assert(isfile(c01r1)&&strcmpi(sha256(c01r1), ...
    '0AD814FFB9637A9DFBFB498E3AF36CEC4F8E6E27DEB4F1EB130BE338304870F4'), ...
    'V25G2:Lineage','C01R1 immutable evidence is missing or changed.');
currentOrdinal=find(allowed==runId);
for k=1:currentOrdinal-1
    priorRow=registry(registry.run_id==allowed(k),:);
    priorFile=formal_result_path(root,priorRow,remediationFile);
    assert(isfile(priorFile),'V25G2:Sequence','Prior run %s evidence is missing.',allowed(k));
    prior=load(priorFile,'report','dataset');
    assert(strcmp(string(prior.report.runId),allowed(k))&&prior.report.simCallCount==1&& ...
        prior.report.simulationCompleted&&prior.dataset.formalCalibrationEligibility, ...
        'V25G2:Sequence','Prior run %s is not completed/eligible.',allowed(k));
end
for k=currentOrdinal+1:numel(allowed)
    laterRow=registry(registry.run_id==allowed(k),:);
    laterFile=fullfile(root,strrep(char(laterRow.result_path_reserved),'/',filesep));
    assert(~isfile(laterFile),'V25G2:Sequence','Later run %s already has a result.',allowed(k));
end

prefEnv=getenv('MATLAB_PREFDIR');activePref=prefdir;
report=struct();report.stage='V2.5-G2 remaining calibration acquisition';
report.runId=char(runId);report.role='CALIBRATION_ONLY';report.registryRowIndex=rowIndex;
report.replacesRunId='NONE';report.replacementGeneration=0;
report.originalReservedPath=originalReservedFile;
report.originalReservedArtifactRole=char(ifelse(runId=="FWCAL_C02", ...
    "PRE_SIM_FAILURE_EVIDENCE","UNUSED_RESERVED_PATH"));
report.originalReservedArtifactExcludedFromCalibration=runId=="FWCAL_C02";
report.resultPath=resultFile;report.resultPathPreRunAbsent=true;
report.matlabStartup=struct('version',version,'startupGateReached',true, ...
    'prelaunchUTC',char(evalin('base','g2_prelaunch_utc')), ...
    'runnerStartDatenum',now,'runnerStartUTC',datestr(now,30), ...
    'simulinkLicense',license('test','Simulink'),'simulinkLoadReached',false);
assert(report.matlabStartup.simulinkLicense==1,'V25G2:Startup','Simulink license gate failed.');
load_system('simulink');report.matlabStartup.simulinkLoadReached=bdIsLoaded('simulink');
assert(report.matlabStartup.simulinkLoadReached,'V25G2:Startup','Simulink load gate failed.');
report.matlabPrefdir=struct('environmentValue',prefEnv,'activeValue',activePref, ...
    'expectedFreshValue',expectedFreshPrefdir,'environmentUnset',isempty(prefEnv), ...
    'userEnvironmentUnset',evalin('base','g2_prefdir_user_unset'), ...
    'machineEnvironmentUnset',evalin('base','g2_prefdir_machine_unset'), ...
    'activeExact',strcmpi(activePref,expectedFreshPrefdir));
assert(report.matlabPrefdir.environmentUnset&&report.matlabPrefdir.activeExact, ...
    'V25G2:PREFDIR','R4 fresh default PREFDIR policy failed.');
q04Info=dir(q04Quarantine);set2Info=dir(set2Quarantine);activeQ04Info=dir(activeQ04);
report.postQuarantine=struct('classification','POST_QUARANTINE_STARTUP_STABILITY_CONFIRMED', ...
    'q04OriginalPath',q04Quarantine,'q04OriginalExists',isfile(q04Quarantine), ...
    'q04OriginalSHA256','','q04OriginalBytes',0,'q04OriginalMTime','', ...
    'activeQ04Path',activeQ04,'activeQ04Exists',isfile(activeQ04), ...
    'activeQ04SHA256','','activeQ04Bytes',0,'activeQ04MTime','', ...
    'set2OriginalPath',set2Quarantine,'set2OriginalExists',isfile(set2Quarantine), ...
    'set2OriginalSHA256','','set2OriginalBytes',0,'set2OriginalMTime','', ...
    'activeSet2Path',activeSet2,'activeSet2SourceAbsent',~isfile(activeSet2), ...
    'activeSet2SourceAbsentAtRunnerEntry',~isfile(activeSet2), ...
    'restorePerformed',false,'additionalQuarantinePerformed',false);
assert(~isempty(q04Info)&&~isempty(set2Info)&&~isempty(activeQ04Info), ...
    'V25G2:Quarantine','Required quarantine/active-Q04 evidence is missing.');
report.postQuarantine.q04OriginalSHA256=sha256(q04Quarantine);
report.postQuarantine.q04OriginalBytes=q04Info.bytes;
report.postQuarantine.q04OriginalMTime=datestr(q04Info.datenum,30);
report.postQuarantine.activeQ04SHA256=sha256(activeQ04);
report.postQuarantine.activeQ04Bytes=activeQ04Info.bytes;
report.postQuarantine.activeQ04MTime=datestr(activeQ04Info.datenum,30);
report.postQuarantine.set2OriginalSHA256=sha256(set2Quarantine);
report.postQuarantine.set2OriginalBytes=set2Info.bytes;
report.postQuarantine.set2OriginalMTime=datestr(set2Info.datenum,30);
assert(strcmpi(report.postQuarantine.q04OriginalSHA256,q04Expected)&& ...
    strcmpi(report.postQuarantine.set2OriginalSHA256,set2Expected)&& ...
    report.postQuarantine.activeQ04Exists&&report.postQuarantine.activeSet2SourceAbsent, ...
    'V25G2:Quarantine','Post-quarantine hard lock failed.');
report.runCard=struct('runId',char(runId),'role','CALIBRATION_ONLY', ...
    'registryRowIndex',rowIndex,'replacesRunId','NONE', ...
    'plannedAmplitudeRad',amplitude,'commandedAmplitudeRad',amplitude, ...
    'plannedFrequencyHz',frequency,'commandedFrequencyHz',frequency, ...
    'plannedDurationS',duration,'stopTimeS',duration, ...
    'plannedEstimatorRateHz',rate,'waveform','SINE_FRONT_EQUAL_REAR_ZERO', ...
    'frontSteeringPolicy','FL_FR_SAME_PHASE','rearSteeringPolicy','RL_RR_ZERO', ...
    'speedScope',char(reg.vx_control_mode),'truthAlignmentRule',char(reg.truth_alignment_rule), ...
    'evaluationWindowRule',char(reg.evaluation_window_s),'targetPath',target, ...
    'targetSHA256',targetExpected,'activePREFDIR',activePref,'resultPath',resultFile, ...
    'originalReservedPath',originalReservedFile, ...
    'originalReservedArtifactExcludedFromCalibration',report.originalReservedArtifactExcludedFromCalibration, ...
    'SET2PrelaunchPolicy','MUST_BE_ABSENT', ...
    'SET2PostStartupRegenerationPolicy','ALLOWED_WITH_PROVENANCE', ...
    'activeSet2SourceAbsentAtRunnerEntry',report.postQuarantine.activeSet2SourceAbsentAtRunnerEntry, ...
    'testSpeedAssignedByRunner',false);
report.simCalled=false;report.simCallCount=0;report.runtimeAuthorizationConsumed=false;
report.simulationCompleted=false;report.carSimRun=false;report.raw=struct();
report.consoleText='';report.runtimeError=struct('identifier','','message','','report','');

% Immutable preregistration, C01R1, recovery, and frozen evidence.
historyFiles={fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5F_CALIBRATION_HOLDOUT_PLAN.md'); ...
    suiteFile;registryFile;fullfile(root,'results','vy_fixed_fusion_v2_5g1c_remediation_registry.csv'); ...
    fullfile(root,'results','vy_fixed_fusion_v2_5g1c_preregistration_gates.csv'); ...
    fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1C_C01_REPLACEMENT_PREREGISTRATION.md'); ...
    fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1B_R4_STATUS.md'); ...
    fullfile(root,'results','vy_fixed_fusion_v2_5g1b_recovery_diagnostic.mat'); ...
    fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1B_RECOVERY_DIAGNOSTIC_STATUS.md'); ...
    c01r1;fullfile(root,'results','vy_fixed_fusion_v2_5g1d_C01R1_acquisition_record.csv'); ...
    fullfile(root,'results','vy_fixed_fusion_v2_5g1d_C01R1_integrity_gates.csv'); ...
    fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G1D_C01R1_STATUS.md'); ...
    fullfile(root,'results','vy_fixed_fusion_v2_5g_fwcal_c02.mat'); ...
    remediationFile;fullfile(root,'results','vy_fixed_fusion_v2_5g2_C02_set2_lifecycle_evidence.csv'); ...
    fullfile(root,'docs','STAGE_VY_FIXED_FUSION_V2_5G2_C02_R0_PRESIM_REMEDIATION.md')};
historyHashes={'97E3D7C9C3F35853372702A8CC545FEB02D9C182CEC012D47BA177D19673F230'; ...
    'AA3784A3CFCDAF8D048D743109477A773267140B693D71FF141E2E1BD58C489E'; ...
    '92B052D8450F432510C31035CDBE5A38BFE8CD7614691E3BE305D4D45CB9CFBE'; ...
    'C112249565DB5DCBAFE0A04D27FA7593E6F427DB26072CD3803D7E9E70D4E7A7'; ...
    '40676D452D47483644EA87FFE61ADFDBC942ECBD052D631875F368307DA18CAB'; ...
    '29442D6A5194C799198C3ED8BC97520154EB02774DAED8671A471D5C6B19746C'; ...
    'A91D13C0B59227DE85085D22767BEA9B1FDA411EB83BF3302B27881B2BE0CD2A'; ...
    '030CE3FDE238641D046D9DC9DABF07AFE75BB00F38CB12E0181F6755C4A7CC12'; ...
    '4C3EA774732CDB163B32BC39A7AE93D1BE38F922C69E7BD8DBC557EBB2CAA6C7'; ...
    '0AD814FFB9637A9DFBFB498E3AF36CEC4F8E6E27DEB4F1EB130BE338304870F4'; ...
    '0D61638DE08D619D5D302CDE1F5DF9CF22B4F334475836913CC505F85A88ABBF'; ...
    '6FD8DB6AFF9737FDCF79F6FB5DE1CF8F840192182F16429AC8D584A0DB95CFD0'; ...
    '376570356400745C260AF2FA293EA5704E067061C16FCB3B355101CCB20F750B'; ...
    'F78B76F1D63CB465B98401BF033E842A6BC440D88237F625AD11E8FF1D9A484F'; ...
    'C7E59555C0DD94946DDFECE583144EE10C353B39249D44E477FD28B2D03AB402'; ...
    'E4B32CBAEA2E3F48A10368D5205604757F08AC880B2ECE424D719FFC560AA8CB'; ...
    '346C1C6ED67905B63EFA8CCC5D67C98283B923D405C385D2E5E112A3803E8310'};
report.historyBefore=hash_files(historyFiles);
assert(hashes_match(report.historyBefore,historyHashes),'V25G2:History','Historical evidence changed.');
[frozenFiles,frozenHashes]=frozen_manifest(root);report.frozenBefore=hash_files(frozenFiles);
assert(hashes_match(report.frozenBefore,frozenHashes),'V25G2:Frozen','Frozen hash mismatch.');
report.targetHashBefore=sha256(target);

oldPwd=pwd;oldPath=path;cleanupObj=onCleanup(@()cleanup(model,oldPwd,oldPath));console='';
try
    solverDir='D:\carsim\CarSim2021.0_Prog\Programs\solvers';
    solverSfDir=fullfile(solverDir,'Matlab84+');solverDll=fullfile(solverDir,'carsim_64.dll');
    solverMex=fullfile(solverSfDir,'vs_sf.mexw64');solverLibrary=fullfile(solverSfDir,'Solver_SF.slx');
    assert(isfile(simFile)&&isfile(solverDll)&&isfile(solverMex)&&isfile(solverLibrary), ...
        'V25G2:CarSim','Required D: CarSim file missing.');
    simText=fileread(simFile);report.carSim=struct('pwd','','activeSimfile',simFile, ...
        'simfileSHA256',sha256(simFile),'progDir',macro_value(simText,'PROGDIR'), ...
        'dataDir',macro_value(simText,'DATADIR'),'solverExpected',solverDll,'solverActual','', ...
        'mexExpected',solverMex,'mexActual','','gRequestBefore',contains(lower(simText),'g:\carsim'), ...
        'gRequestConsole',false);
    assert(strcmpi(report.carSim.simfileSHA256,'A50912CE50F59B216A4CF939228E63A0F27B9818C52A2ABE493345C53FA7A2EA')&& ...
        strcmpi(report.carSim.progDir,'D:\carsim\CarSim2021.0_Prog\')&& ...
        strcmpi(report.carSim.dataDir,'D:\carsim\CarSim2021.0_Data\')&&~report.carSim.gRequestBefore, ...
        'V25G2:CarSim','simfile policy mismatch.');
    addpath(md);addpath(solverDir);addpath(solverSfDir);
    Simulink.fileGenControl('set','CacheFolder',fullfile(tempdir,'vy_fixed_fusion_v2_5g2_cache'), ...
        'CodeGenFolder',fullfile(tempdir,'vy_fixed_fusion_v2_5g2_codegen'),'createDir',true);
    cd(md);report.carSim.pwd=pwd;report.carSim.activeSimfile=fullfile(pwd,'simfile.sim');
    report.carSim.mexActual=which('vs_sf');
    assert(strcmpi(pwd,md)&&strcmpi(report.carSim.activeSimfile,simFile)&& ...
        strcmpi(report.carSim.mexActual,solverMex),'V25G2:Environment','cwd/simfile/MEX gate failed.');
    load_system('Solver_SF');load_system(target);
    postLoadSet2=file_metadata(activeSet2);
    postLoadSet2.generatedDuringCurrentSession=postLoadSet2.exists&& ...
        postLoadSet2.mtimeDatenum>=report.matlabStartup.runnerStartDatenum-2/86400;
    postLoadSet2.provenanceAccepted=~postLoadSet2.exists|| ...
        (report.postQuarantine.activeSet2SourceAbsentAtRunnerEntry&& ...
        postLoadSet2.generatedDuringCurrentSession);
    assert(postLoadSet2.provenanceAccepted,'V25G2:SET2Provenance', ...
        'Post-startup SET-2 exists without current-session generation provenance.');
    report.static=static_preflight(model);assert(report.static.pass,'V25G2:Static','Static gate failed.');
    report.weights=report.static.weights;report.fParameters=report.static.fParameters;
    w=get_param(model,'ModelWorkspace');
    assignin(w,'test_steer_amplitude',amplitude);assignin(w,'test_steer_frequency',frequency);
    assignin(w,'vy_v17_mode_code',20);assignin('base','test_steer_amplitude',amplitude);
    assignin('base','test_steer_frequency',frequency);assignin('base','vy_v17_mode_code',20);
    clear vy_dynamic_ekf_v1_17 vy_kinematic_kf
    logs={'steer_cmd_rad','steer_to_carsim_deg','steer_fl_carsim_deg', ...
        'steer_fr_carsim_deg','steer_rl_carsim_deg','steer_rr_carsim_deg', ...
        'reset_g0','avz_imu_g0','kkf_u_log1','kkf_x_log1','kkf_P_log1', ...
        'kkf_diag_log1','dekf_x_log','dekf_P_log','dekf_diag_log','parallel_input_log', ...
        'fusion_vy_d_log','fusion_vy_k_log','fusion_vy_f_log','fusion_f_P_log', ...
        'fusion_f_diag_log','fusion_vy_fw_log','vy_true_log1','Vx_true_log'};
    report.logVariables=logs;
    assert(all(cellfun(@(n)numel(find_system(model,'SearchDepth',1,'BlockType','ToWorkspace', ...
        'VariableName',n))==1,logs)),'V25G2:Logging','Required log boundary missing.');
    report.immediatePreSim=struct('pwd',pwd,'activeSimfile',report.carSim.activeSimfile, ...
        'simfileSHA256',sha256(report.carSim.activeSimfile),'progDir',report.carSim.progDir, ...
        'dataDir',report.carSim.dataDir,'solver',solverDll,'mex',which('vs_sf'), ...
        'activePREFDIR',prefdir,'MATLAB_PREFDIR',getenv('MATLAB_PREFDIR'), ...
        'activeSet2SourceAbsent',~postLoadSet2.exists, ...
        'postLoadSet2',postLoadSet2, ...
        'SET2PrelaunchPolicy','MUST_BE_ABSENT', ...
        'SET2PostStartupRegenerationPolicy','ALLOWED_WITH_PROVENANCE', ...
        'q04OriginalSHA256',sha256(q04Quarantine), ...
        'set2OriginalSHA256',sha256(set2Quarantine), ...
        'plannedAmplitude',amplitude,'commandedAmplitude',amplitude, ...
        'plannedFrequency',frequency,'commandedFrequency',frequency, ...
        'plannedDuration',duration,'StopTime',duration,'plannedRate',rate);
    assert(strcmpi(report.immediatePreSim.pwd,md)&&strcmpi(report.immediatePreSim.activeSimfile,simFile)&& ...
        strcmpi(report.immediatePreSim.solver,solverDll)&&strcmpi(report.immediatePreSim.mex,solverMex)&& ...
        strcmpi(report.immediatePreSim.activePREFDIR,expectedFreshPrefdir)&& ...
        isempty(report.immediatePreSim.MATLAB_PREFDIR)&& ...
        report.immediatePreSim.postLoadSet2.provenanceAccepted&& ...
        strcmpi(report.immediatePreSim.q04OriginalSHA256,q04Expected)&& ...
        strcmpi(report.immediatePreSim.set2OriginalSHA256,set2Expected)&& ...
        amplitude==report.immediatePreSim.commandedAmplitude&&frequency==report.immediatePreSim.commandedFrequency&& ...
        duration==report.immediatePreSim.StopTime,'V25G2:ImmediatePreSim','Immediate pre-sim gate failed.');
    fprintf(['G2_RUN_CARD|run_id=%s|role=%s|row=%d|plannedA=%.17g|commandedA=%.17g|' ...
        'plannedF=%.17g|commandedF=%.17g|plannedDuration=%.17g|StopTime=%.17g|' ...
        'rate=%.17g|waveform=%s|front=%s|rear=%s|speed=%s|targetHash=%s|' ...
        'prefdir=%s|activeSet2AbsentAtLaunch=1|postLoadSet2Exists=%d|' ...
        'postLoadSet2Hash=%s|postLoadSet2CTime=%s|postLoadSet2MTime=%s|' ...
        'postLoadSet2Provenance=%d|cwd=%s|simfile=%s|solver=%s|mex=%s|result=%s\n'], ...
        report.runId,report.role,rowIndex,amplitude,amplitude,frequency,frequency,duration,duration,rate, ...
        report.runCard.waveform,report.runCard.frontSteeringPolicy,report.runCard.rearSteeringPolicy, ...
        report.runCard.speedScope,targetExpected,activePref,postLoadSet2.exists,postLoadSet2.sha256, ...
        postLoadSet2.creationTimeUTC,postLoadSet2.mtimeUTC,postLoadSet2.provenanceAccepted, ...
        pwd,report.carSim.activeSimfile, ...
        solverDll,solverMex,resultFile);

    report.simCalled=true;report.simCallCount=1;report.runtimeAuthorizationConsumed=true;
    console=evalc("out=sim(model,'StopTime',sprintf('%.17g',duration),"+ ...
        "'ReturnWorkspaceOutputs','on','FastRestart','off');");
    fprintf('%s',console);report.consoleText=console;
    report.carSim.solverActual=solver_path_from_console(console);
    report.carSim.gRequestConsole=contains(lower(console),'g:\carsim');
    report.carSimRun=contains(console,'Termination at simulation time')&& ...
        strcmpi(report.carSim.solverActual,solverDll)&&~report.carSim.gRequestConsole;
    assert(report.carSimRun,'V25G2:CarSim','CarSim completion evidence missing.');
    for k=1:numel(logs),name=logs{k};report.raw.(name)=record_timeseries(out.get(name));end
    report.stopTimeActualS=max([report.raw.fusion_vy_d_log.time(end), ...
        report.raw.fusion_vy_k_log.time(end),report.raw.fusion_vy_f_log.time(end), ...
        report.raw.fusion_vy_fw_log.time(end)]);
    report.simulationCompleted=true;
catch ME
    report.consoleText=console;report.runtimeError.identifier=ME.identifier;
    report.runtimeError.message=ME.message;report.runtimeError.report=getReport(ME,'extended','hyperlinks','off');
end

cleanup(model,oldPwd,oldPath);clear cleanupObj
report.targetHashAfter=sha256(target);report.targetHashUnchanged=strcmpi(report.targetHashBefore,report.targetHashAfter);
report.frozenAfter=hash_files(frozenFiles);report.allFrozenHashesUnchanged=hashes_match(report.frozenAfter,frozenHashes);
report.historyAfter=hash_files(historyFiles);
report.historyUnchanged=hashes_equal(report.historyBefore,report.historyAfter)&&hashes_match(report.historyAfter,historyHashes);
report.preregistrationUnchanged=report.historyUnchanged;
if ~report.simCalled
    fprintf(['G2_PRE_SIM_BLOCK|id=%s|simCalled=0|authorization=UNCONSUMED|' ...
        'formalResultCreated=0|error=%s|message=%s\n'],report.runId, ...
        report.runtimeError.identifier,report.runtimeError.message);
    error('V25G2:PreSimBlocked','%s pre-sim blocked without consuming runtime authorization: %s', ...
        report.runId,report.runtimeError.message);
end
if report.simulationCompleted
    [analysis,dataset]=analyze_vy_fixed_fusion_v2_5g2_remaining_calibration(report,reg);
    report.analysis=analysis;save(resultFile,'report','dataset','-v7.3');
else % sim() was called: retain immutable runtime-failure evidence at the formal path.
    save(resultFile,'report','-v7.3');
end
resultHash=sha256(resultFile);info=dir(resultFile);
fprintf(['G2_RUNTIME_EVIDENCE|id=%s|simCalled=%d|simCount=%d|completed=%d|carSim=%d|' ...
    'stop=%.17g|solver=%s|targetUnchanged=%d|historyUnchanged=%d|' ...
    'resultHash=%s|bytes=%d\n'],report.runId,report.simCalled,report.simCallCount, ...
    report.simulationCompleted,report.carSimRun,getfield_default(report,'stopTimeActualS',NaN), ...
    getfield_default(report.carSim,'solverActual',''),report.targetHashUnchanged, ...
    report.historyUnchanged,resultHash,info.bytes);
if ~report.simulationCompleted
    error('V25G2:RuntimeFailed','%s runtime failed after authorization consumption: %s',report.runId,report.runtimeError.message);
end
assert(report.analysis.passed&&report.targetHashUnchanged&&report.allFrozenHashesUnchanged&& ...
    report.historyUnchanged,'V25G2:Integrity','Runtime/data-integrity gate failed.');
fprintf('%s ACQUISITION PASS\n',report.runId);
end

function audit=static_preflight(m)
fusion=[m '/Fixed Weight D K F Fusion'];fSub=[m '/F-Track 100Hz'];
fp=get_param(fusion,'PortHandles');fsp=get_param(fSub,'PortHandles');
params=parse_expr_list(get_param(fusion,'Parameters'));
fParams=parse_expr_list(get_param([fSub '/F-Track Stateful Boundary'],'Parameters'));
audit=struct();audit.weights=struct('values',params,'alpha_D',params(1),'alpha_K',params(2), ...
    'alpha_F',params(3),'classification','TEST-ONLY / UNSELECTED');
audit.fParameters=struct('Ts',fParams(1),'Vy_F0',fParams(2),'P0_F',fParams(3),'Q_F',fParams(4));
audit.fusionSources=arrayfun(@source_of_port,fp.Inport,'UniformOutput',false);
audit.fusionSourcesExact=isequal(audit.fusionSources(:), ...
    {[m '/Fusion D State Select Vy'];[m '/Fusion K State Select Vy'];fSub});
audit.fValidSource=source_of_port(fsp.Inport(6));
audit.fValidZero=strcmp(audit.fValidSource,[m '/F Feedback Valid Disabled'])&& ...
    str2double(get_param(audit.fValidSource,'Value'))==0;
audit.schedulers={source_of_trigger([m '/Parallel D-EKF 100Hz']), ...
    source_of_trigger([m '/K-KF 100Hz']),source_of_trigger(fSub)};
audit.schedulers100Hz=all(cellfun(@scheduler100,audit.schedulers));
audit.schedulersIndependent=numel(unique(audit.schedulers))==3;
cmd=[m '/G0 Steer Cmd Rad'];gain=[m '/Gain22'];sw=[m '/Manual Switch1'];
audit.steering=struct('amplitude',get_param(cmd,'Amplitude'),'frequency',get_param(cmd,'Frequency'), ...
    'gain',get_param(gain,'Gain'),'switch',get_param(sw,'CurrentSetting'));
audit.noOnlineTrueVy=audit.fusionSourcesExact;
audit.noP_FW=numel(fp.Outport)==1&&isempty(find_system(m,'SearchDepth',1,'BlockType','ToWorkspace','VariableName','P_FW'));
audit.noCovarianceFusion=numel(fp.Inport)==3&&audit.fusionSourcesExact;audit.noFeedbackClosure=audit.fValidZero;
audit.pass=isequal(params,[1/3 1/3 1/3])&&fParams(1)==0.01&&fParams(3)==0.5&& ...
    fParams(4)==0.0025&&audit.fusionSourcesExact&&audit.fValidZero&& ...
    audit.schedulers100Hz&&audit.schedulersIndependent&& ...
    strcmp(audit.steering.amplitude,'test_steer_amplitude')&& ...
    strcmp(audit.steering.frequency,'2*pi*test_steer_frequency')&& ...
    strcmp(strtrim(audit.steering.gain),'180/pi')&&strcmp(audit.steering.switch,'0')&& ...
    audit.noOnlineTrueVy&&audit.noP_FW&&audit.noCovarianceFusion&&audit.noFeedbackClosure;
end
function x=parse_expr_list(s),p=strsplit(s,',');x=zeros(1,numel(p));for k=1:numel(p),x(k)=str2num(p{k});end,end %#ok<ST2NM>
function tf=scheduler100(p),tf=strcmp(get_param(p,'MaskType'),'Function-Call Generator')&&abs(str2double(get_param(p,'sample_time'))-0.01)<1e-15;end
function src=source_of_port(p),l=get_param(p,'Line');assert(l>0,'Unconnected input.');src=getfullname(get_param(l,'SrcBlockHandle'));end
function src=source_of_trigger(b),p=get_param(b,'PortHandles');src=source_of_port(p.Trigger(1));end
function r=record_timeseries(ts),assert(isa(ts,'timeseries'),'Expected timeseries.');r=struct('time',double(ts.Time(:)),'data',double(ts.Data),'sampleCount',numel(ts.Time),'dataSize',size(ts.Data));end
function value=macro_value(text,key),t=regexp(text,['(?m)^' key '\s+([^\r\n]+)'],'tokens','once');assert(~isempty(t),'Missing %s',key);value=strtrim(t{1});end
function p=solver_path_from_console(text),t=regexp(text,'Use vehicle solver:\s*([^\r\n]+)','tokens','once');if isempty(t),p='';else,p=strtrim(t{1});end,end
function cleanup(m,oldPwd,oldPath),if bdIsLoaded(m),close_system(m,0);end;if bdIsLoaded('Solver_SF'),close_system('Solver_SF',0);end;cd(oldPwd);path(oldPath);evalin('base','clear test_steer_amplitude test_steer_frequency vy_v17_mode_code');end
function v=asnum(x),if isnumeric(x),v=double(x);else,v=str2double(string(x));end;assert(isscalar(v));end
function v=getfield_default(s,f,d),if isfield(s,f),v=s.(f);else,v=d;end,end
function y=ifelse(tf,a,b),if tf,y=a;else,y=b;end,end
function file=formal_result_path(root,reg,remediationFile)
if string(reg.run_id)=="FWCAL_C02"
    rem=readtable(remediationFile,'TextType','string','VariableNamingRule','preserve','Delimiter',',');
    rem=rem(rem.run_id=="FWCAL_C02",:);assert(height(rem)==1,'V25G2:Remediation','C02 remediation row missing.');
    file=fullfile(root,strrep(char(rem.new_formal_runtime_path),'/',filesep));
else
    file=fullfile(root,strrep(char(reg.result_path_reserved),'/',filesep));
end
end
function m=file_metadata(file)
m=struct('path',file,'exists',isfile(file),'sha256','','bytes',0, ...
    'creationTimeUTC','','mtimeUTC','','mtimeDatenum',NaN, ...
    'generatedDuringCurrentSession',false,'provenanceAccepted',false);
if ~m.exists,return,end
d=dir(file);m.sha256=sha256(file);m.bytes=d.bytes;m.mtimeDatenum=d.datenum;
m.mtimeUTC=datestr(d.datenum,30);
try
    fi=System.IO.FileInfo(file);m.creationTimeUTC=char(fi.CreationTimeUtc.ToString('o'));
    m.mtimeUTC=char(fi.LastWriteTimeUtc.ToString('o'));
catch
    m.creationTimeUTC='UNAVAILABLE';
end
end
function [files,hashes]=frozen_manifest(root)
files={fullfile(root,'model','vx_vy_fixed_fusion_v2_5.slx');fullfile(root,'model','vy_fixed_weight_fusion_simulink_sfun.m');fullfile(root,'model','vy_fixed_weight_fusion_step.m');fullfile(root,'model','vx_vy_parallel_dk_v2_3.slx');fullfile(root,'model','vx_vy_dekf_v1_17.slx');fullfile(root,'model','vy_dynamic_ekf_v1_17.m');fullfile(root,'model','vy_dynamic_ekf_step_v17.m');fullfile(root,'model','vy_dynamic_ekf_step_v13.m');fullfile(root,'model','vx_vy_kkf_v2_1.slx');fullfile(root,'model','vx_vy_kkf_v2_1g_steer.slx');fullfile(root,'model','vy_kinematic_kf_step.m');fullfile(root,'model','vy_kinematic_kf.m');fullfile(root,'model','vx_vy_dkekf_v2_2.slx');fullfile(root,'model','vy_dkekf_baseline_step.m');fullfile(root,'model','vy_dkekf_baseline.m');fullfile(root,'model','vy_dkekf_baseline_simulink_sfun.m');fullfile(root,'model','vy_feedback_propagation_step.m');fullfile(root,'model','vy_feedback_propagation_simulink_sfun.m');fullfile(root,'model','vx_vy_feedback_track_v2_4.slx')};
hashes={'801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE';'B7185A2E26B2874D792266D6CBAEC26A8DED6FDFBDFC862ACC394DE01F94F30A';'4DE407D651FD3366357BFFF181FDB8474273E769982A18EFB96426FC05CC254C';'98461DB290723A5CCDF62398CE5063DE0C9B6C7586334D479B159A771EB128C0';'108F819DCD1B71FD6D795D7148CBF32FE1A888AE9878908E894A07626ED003AE';'5550D0389FC4D1DCF7F65B0E00B4C51A949F2B9ADD33C2D78D1122A31291A1A0';'4010F6A4BD669AC048297C2F416F0B8826F729F4552D73445703184F052C4A4F';'498A446E13E654387E3D36BF4694A336E75B2100E765DAC0414A01367531CDE4';'B67A98A6080374304E2D3424F85589C913E6EC4DB25BC9912CBFD2BC441C2712';'59B25C5E350140AB0EAFD8345D5A9145D6981B96481023537A3BD01A787F728E';'3786646EE5163D231DD8964614A8875217DFA496EB593B455E4E029E26DA2244';'F242CB75BA08D22CB1EED87731746CF80D54FD39C1899B45E9980A40576414D4';'E768FB2AD33A6EEAABDE2FB7C40BE660B78F350A90C752327DC9B423F50F2E15';'6475B9DBC93EB6E25C2BB9FAD81CA11B2E08C26E7F2AE6A33C50E35B2790B457';'7E731D7DF0BB2CA4455E3AA16E7513114E04472D38C62F1F453B631056306973';'12F0D82643D65AA5098ED20C0655234F3A2E7EF6D6F5E7DEE5B80BC1A201BDA1';'80C21D2CDC74F23C964DC50EAC48F2C026AD27027B160BB851B491E301D0E5FF';'2FF7E488CC60DD729EC4948066714A95DAC15BBDB08BA45004EF6A7C8E1234B0';'951A0D6E454F9C4C8ECD90EB4AD0372270F7D5EDCC15203B68D877C2ED27BF84'};
end
function r=hash_files(files),r=repmat(struct('path','','sha256',''),numel(files),1);for k=1:numel(files),r(k)=struct('path',files{k},'sha256',sha256(files{k}));end,end
function ok=hashes_match(r,e),ok=numel(r)==numel(e);for k=1:numel(r),ok=ok&&strcmpi(r(k).sha256,e{k});end,end
function ok=hashes_equal(a,b),ok=numel(a)==numel(b);for k=1:numel(a),ok=ok&&strcmpi(a(k).path,b(k).path)&&strcmpi(a(k).sha256,b(k).sha256);end,end
function h=sha256(file),d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());while ds.read()~=-1,end;b=typecast(d.digest(),'uint8');h=upper(reshape(dec2hex(b,2).',1,[]));clear c,end
