function report=analyze_vy_parallel_dk_v2_3d_nominal_validation()
%ANALYZE_VY_PARALLEL_DK_V2_3D_NOMINAL_VALIDATION Offline-only analysis.

root=fileparts(fileparts(mfilename('fullpath')));
f=fullfile(root,'results','vy_parallel_dk_v2_3d_nominal_validation.mat');
formalFile=fullfile(root,'results','vy_parallel_dk_v2_3b_integration_gates.mat');
harnessFile=fullfile(root,'results','vy_parallel_dk_v2_3b2_compile_gates.mat');
g1File=fullfile(root,'results','vy_kkf_v2_1g1_nominal_002.mat');
S=load(f,'report');report=S.report;
assert(report.simCalled&&report.simulationCompleted&&report.carSimRun, ...
    'V2.3-D simulation/CarSim completion evidence is incomplete.');r=report.raw;
F=load(formalFile,'report');H=load(harnessFile,'report');
prior=struct('formalStatic',[F.report.staticGatesTrue F.report.staticGateCount], ...
    'harnessStatic',[H.report.staticGatesTrue H.report.staticGateCount], ...
    'compiled',[H.report.compiledGatesTrue H.report.compiledGateCount], ...
    'compilePassed',H.report.compile.passed);
prior.pass=isequal(prior.formalStatic,[41 41])&&isequal(prior.harnessStatic,[38 38])&& ...
    isequal(prior.compiled,[15 15])&&prior.compilePassed;

% Genuine steering from this run.
sn={'steer_cmd_rad','steer_to_carsim_deg','steer_fl_carsim_deg', ...
    'steer_fr_carsim_deg','steer_rl_carsim_deg','steer_rr_carsim_deg'};
st=cellfun(@(n)double(r.(n).time(:)),sn,'UniformOutput',false);
sv=cellfun(@(n)vector(r.(n)),sn,'UniformOutput',false);
tSteer=st{1};cmd=sv{1};deg=sv{2};fl=sv{3};fr=sv{4};rl=sv{5};rr=sv{6};
theory=.02*sin(2*pi*.4*tSteer);nz=abs(cmd)>1e-12;ratio=deg(nz)./cmd(nz);
steering=struct('sampleCount',numel(tSteer),'timeRange',[tSteer(1) tSteer(end)], ...
    'logsExactlyAligned',isequal(st{:}),'command',range_stats(cmd), ...
    'convertedDeg',range_stats(deg),'frequency_Hz',fit_frequency(tSteer,cmd), ...
    'commandVsTheoryMaxAbsDiff',max(abs(cmd-theory)), ...
    'degRadRatioMedian',median(ratio),'degRadRatioMaxError',max(abs(ratio-180/pi)), ...
    'flMaxAbs',max(abs(fl)),'frMaxAbs',max(abs(fr)), ...
    'rlMaxAbs',max(abs(rl)),'rrMaxAbs',max(abs(rr)), ...
    'flVsConvertedMaxAbsDiff',max(abs(fl-deg)), ...
    'frVsConvertedMaxAbsDiff',max(abs(fr-deg)), ...
    'flVsFrMaxAbsDiff',max(abs(fl-fr)));
steering.pass=steering.logsExactlyAligned&&abs(steering.command.maxAbs-.02)<=1e-9&& ...
    abs(steering.convertedDeg.maxAbs-.02*180/pi)<=1e-9&& ...
    abs(steering.frequency_Hz-.4)<=1e-5&&steering.commandVsTheoryMaxAbsDiff<=1e-12&& ...
    steering.degRadRatioMaxError<=1e-10&&steering.flVsConvertedMaxAbsDiff<=1e-12&& ...
    steering.frVsConvertedMaxAbsDiff<=1e-12&&steering.flVsFrMaxAbsDiff<=1e-12&& ...
    steering.rlMaxAbs<=1e-12&&steering.rrMaxAbs<=1e-12;

% Independent D runtime stream.
tD=double(r.dekf_x_log.time(:));nD=numel(tD);
dAligned=isequal(tD,double(r.dekf_P_log.time(:)),double(r.dekf_diag_log.time(:)));
dX=sample_rows(r.dekf_x_log.data,nD,2);dP=covariance_pages(r.dekf_P_log.data,nD,2);
dDiag=sample_rows(r.dekf_diag_log.data,nD,65);dTiming=timing_stats(tD,.01);dCov=covariance_stats(dP);
dUseAy=dDiag(:,56)>.5;dStep=dDiag(:,57);dResetMask=abs(dStep)<1e-12;
dReset=struct('count',nnz(dResetMask),'timestamps',tD(dResetMask), ...
    'initialPriorState',[0;0],'initialPriorP',.1*eye(2), ...
    'firstCommittedState',dX(1,:).','firstCommittedP',dP(:,:,1), ...
    'trueVyUsedForInitialization',false);
dReset.pass=dReset.count==1&&abs(dReset.timestamps(1))<=1e-12&& ...
    isequal(dStep(:),(0:nD-1).');
dAyTimes=tD(dUseAy);dAy=struct('count',nnz(dUseAy),'timestamps',dAyTimes, ...
    'intervalMin',min(diff(dAyTimes)),'intervalMean',mean(diff(dAyTimes)), ...
    'intervalMax',max(diff(dAyTimes)));
dAy.pass=dAy.count==321&&all(abs(diff(dAyTimes)-.05)<=1e-12)&& ...
    abs(dAyTimes(1))<=1e-12&&abs(dAyTimes(end)-16)<=1e-12;
dStream=struct('stateDefinition','[Vy_D; r_D]','stateDimension',[2 1], ...
    'covarianceDimension',[2 2],'sampleCount',nD,'timing',dTiming, ...
    'logsExactlyAligned',dAligned,'xFinite',all(isfinite(dX(:))), ...
    'PFinite',all(isfinite(dP(:))),'diagFinite',all(isfinite(dDiag(:))), ...
    'covariance',dCov,'reset',dReset,'AyUpdate',dAy);
dStream.pass=dAligned&&nD==1601&&dTiming.pass100Hz&&dStream.xFinite&& ...
    dStream.PFinite&&dStream.diagFinite&&dCov.valid&&dReset.pass&&dAy.pass;

% Independent K runtime stream.
tK=double(r.kkf_x_log1.time(:));nK=numel(tK);
kAligned=isequal(double(r.kkf_u_log1.time(:)),tK,double(r.kkf_P_log1.time(:)), ...
    double(r.kkf_diag_log1.time(:)));
kU=sample_rows(r.kkf_u_log1.data,nK,4);kX=sample_rows(r.kkf_x_log1.data,nK,2);
kP=covariance_pages(r.kkf_P_log1.data,nK,2);kDiag=sample_rows(r.kkf_diag_log1.data,nK,5);
kTiming=timing_stats(tK,.01);kCov=covariance_stats(kP);
kResetRaw=vector(r.reset_g0);kResetTimes=double(r.reset_g0.time(:));kmask=kResetRaw>.5;
kReset=struct('count',nnz(kmask),'timestamps',kResetTimes(kmask), ...
    'initialPriorState',[kU(1,4);0],'initialPriorP',.1*eye(2), ...
    'firstCommittedState',kX(1,:).','firstCommittedP',kP(:,:,1), ...
    'trueVyUsedForInitialization',false);
kReset.pass=kReset.count==1&&abs(kReset.timestamps(1))<=1e-12;
kStream=struct('stateDefinition','[Vx_K; Vy_K]','stateDimension',[2 1], ...
    'covarianceDimension',[2 2],'sampleCount',nK,'timing',kTiming, ...
    'logsExactlyAligned',kAligned,'xFinite',all(isfinite(kX(:))), ...
    'PFinite',all(isfinite(kP(:))),'diagFinite',all(isfinite(kDiag(:))), ...
    'covariance',kCov,'reset',kReset);
kStream.pass=kAligned&&nK==1601&&kTiming.pass100Hz&&kStream.xFinite&& ...
    kStream.PFinite&&kStream.diagFinite&&kCov.valid&&kReset.pass;

timestamps=struct('sameSampleCount',nD==nK,'maxDifference',max(abs(tD-tK)), ...
    'exactMatch',isequal(tD,tK),'schedulerImplementationIndependent',report.static.schedulersIndependent);
timestamps.pass=timestamps.sameSampleCount&&timestamps.exactMatch&& ...
    timestamps.schedulerImplementationIndependent;

% Shared physical input alignment at each independent hit.
tShared=double(r.parallel_input_log.time(:));
[sharedD,alignD]=input_rows_at_hits(r.parallel_input_log.data,tShared,tD,9);
[sharedK,alignK]=input_rows_at_hits(r.parallel_input_log.data,tShared,tK,9);
kInputDiff=max(abs(kU-sharedK(:,1:4)),[],'all');
shared=struct('columns',{{'Ax_IMU','Ay_IMU','AVz_IMU','trueVx','steer_FL_rad', ...
    'steer_FR_rad','steer_RL_rad','steer_RR_rad','K_reset'}}, ...
    'dAlignment',alignD,'kAlignment',alignK,'kInputVsSharedMaxAbsDiff',kInputDiff, ...
    'actualTargetWiring',report.static,'trueVyOnline',false);
shared.routing=struct('Ax','K only','Ay','D measurement + K process input', ...
    'AVz','D r measurement + K process input','trueVx','D dynamics + K measurement', ...
    'steering','D only','trueVy','neither estimator online');
shared.pass=alignD.allHitsResolved&&alignK.allHitsResolved&&~alignD.ambiguousDuplicate&& ...
    ~alignK.ambiguousDuplicate&&kInputDiff<=1e-12&&report.static.sharedRoutingOK&& ...
    report.static.steeringWheelRoutingOK&&~report.static.trueVyOnline;
kAy=struct('hitCount',nK,'allHitsConsumeAxAyAvz',size(kU,1)==nK&&alignK.allHitsResolved&& ...
    kInputDiff<=1e-12,'dAyGateControlsK',false,'semantics','Ax/Ay/AVz process inputs at every K hit');
kAy.pass=kAy.allHitsConsumeAxAyAvz&&~kAy.dAyGateControlsK;

% Offline truth: exact matches preferred, otherwise bounded linear interpolation.
[vxD,vxAlignD]=truth_at(r.Vx_true_log,tD,1);[vyD,vyAlignD]=truth_at(r.vy_true_log1,tD,1);
[rDegD,rAlignD]=truth_at(r.avz_log1,tD,1);rTrueD=rDegD*pi/180;
[vxK,vxAlignK]=truth_at(r.Vx_true_log,tK,1);[vyK,vyAlignK]=truth_at(r.vy_true_log1,tK,1);
[rDegK,rAlignK]=truth_at(r.avz_log1,tK,1);rTrueK=rDegK*pi/180;
truth=struct('D',struct('Vx',vxAlignD,'Vy',vyAlignD,'r',rAlignD), ...
    'K',struct('Vx',vxAlignK,'Vy',vyAlignK,'r',rAlignK), ...
    'rSourceUnit','deg/s','rAnalysisUnit','rad/s','rConversion','pi/180', ...
    'onlineUse',false,'extrapolationUsed',false);

% Same-run performance and state-aligned covariance.
eDVy=dX(:,1)-vyD;eDr=dX(:,2)-rTrueD;eKVx=kX(:,1)-vxK;eKVy=kX(:,2)-vyK;
perf=struct('D',struct('Vy',error_metrics(eDVy),'r',error_metrics(eDr)), ...
    'K',struct('Vx',error_metrics(eKVx),'Vy',error_metrics(eKVy)));
sameRun=struct('D',perf.D.Vy,'K',perf.K.Vy, ...
    'DminusK',metric_difference(perf.D.Vy,perf.K.Vy));
if perf.D.Vy.RMSE<perf.K.Vy.RMSE,sameRun.lowerVyRMSE='D-EKF'; ...
elseif perf.K.Vy.RMSE<perf.D.Vy.RMSE,sameRun.lowerVyRMSE='K-KF';else,sameRun.lowerVyRMSE='TIE';end
dP11=squeeze(dP(1,1,:));dP22=squeeze(dP(2,2,:));
kP11=squeeze(kP(1,1,:));kP22=squeeze(kP(2,2,:));
covariance=struct('D_P11_Vy',series_stats(dP11),'D_P22_r',series_stats(dP22), ...
    'K_P11_Vx',series_stats(kP11),'K_P22_Vy',series_stats(kP22), ...
    'VyVarianceDescription','D uses P11; K uses P22; descriptive only; no weight generated');

% Common online AVz_IMU diagnostic partition.
rOnline=sharedK(:,3);rAbs=abs(rOnline);low=rAbs<=.01;higher=~low;
yaw=struct('threshold_radps',.01,'lifeSigGate',false,'meanAbs',mean(rAbs), ...
    'medianAbs',median(rAbs),'p95Abs',percentile(rAbs,95),'maxAbs',max(rAbs), ...
    'lowCount',nnz(low),'lowFraction',mean(low),'higherCount',nnz(higher), ...
    'higherFraction',mean(higher));
partitions=struct('D',struct('lowR',partition_error(eDVy,low), ...
    'higherR',partition_error(eDVy,higher)), ...
    'K',struct('lowR',partition_error(eKVy,low), ...
    'higherR',partition_error(eKVy,higher)));

% Offline complementarity; exact absolute-error equality defines a tie.
complementarity=struct('pearsonErrorCorrelation',pearson(eDVy,eKVy), ...
    'meanAbsErrorDifference',mean(abs(eDVy-eKVy)), ...
    'overall',winner_fractions(eDVy,eKVy), ...
    'lowR',winner_fractions(eDVy(low),eKVy(low)), ...
    'higherR',winner_fractions(eDVy(higher),eKVy(higher)), ...
    'descriptiveOnly',true,'fusionGenerated',false);

% Existing frozen diagnostic definitions only.
dDiagnostics=struct();
dDiagnostics.definition=struct('aggregateNIS','diag(1)=info.NIS', ...
    'innovationAy','diag(10)=z_Ay-h_Ay','innovationR','diag(11)=z_r-h_r', ...
    'AyUpdateApplied','diag(56)=useAy','stepIndex','diag(57)', ...
    'jointNIS','diag(60) on Ay-update hits','rOnlyNIS','diag(61) on r-only hits');
dDiagnostics.aggregateNIS=distribution_stats(dDiag(:,1));
dDiagnostics.jointNIS=distribution_stats(dDiag(dUseAy,60));
dDiagnostics.rOnlyNIS=distribution_stats(dDiag(~dUseAy,61));
dDiagnostics.innovationAyApplied=innovation_stats(dDiag(dUseAy,10));
dDiagnostics.innovationR=innovation_stats(dDiag(:,11));
dDiagnostics.AyUpdateCount=nnz(dUseAy);
kDiagnostics=struct();
kDiagnostics.definition='[NIS; obs_metric=abs(AVz); innovation_Vx; K11; K21]';
kDiagnostics.NIS=distribution_stats(kDiag(:,1));
kDiagnostics.obsMetric=distribution_stats(kDiag(:,2));
kDiagnostics.obsMetricVsAbsAVzMaxDiff=max(abs(kDiag(:,2)-rAbs));
kDiagnostics.innovationVx=innovation_stats(kDiag(:,3));
kDiagnostics.K11=distribution_stats(kDiag(:,4));kDiagnostics.K21=distribution_stats(kDiag(:,5));
kDiagnostics.lifeSigGate=false;

% Exact frozen D and K replay, same timestamp/index, no shift.
dInput=[sharedD(:,4),sharedD(:,5:8),sharedD(:,2),sharedD(:,3)];
clear vy_dynamic_ekf_v1_17
dXR=zeros(nD,2);dPR=zeros(2,2,nD);dDR=zeros(nD,65);
for k=1:nD
    y=vy_dynamic_ekf_v1_17(dInput(k,:).',20);dXR(k,:)=y(1:2).';
    dPR(:,:,k)=reshape(y(46:49),2,2);dDR(k,:)=y(5:69).';
end
clear vy_dynamic_ekf_v1_17
dReplay=struct('maxAbsXDiff',max(abs(dXR-dX),[],'all'), ...
    'maxAbsPDiff',max(abs(dPR-dP),[],'all'),'maxAbsDiagDiff', ...
    max(abs(dDR-dDiag),[],'all'),'timestampShiftApplied',false);
dReplay.pass=all([dReplay.maxAbsXDiff dReplay.maxAbsPDiff dReplay.maxAbsDiagDiff]<=1e-12);
clear vy_kinematic_kf
kXR=zeros(nK,2);kPR=zeros(2,2,nK);kDR=zeros(nK,5);
for k=1:nK
    [xk,pk,dk]=vy_kinematic_kf(kU(k,1:3).',kU(k,4),double(k==1));
    kXR(k,:)=xk(:).';kPR(:,:,k)=pk;kDR(k,:)=dk(:).';
end
clear vy_kinematic_kf
kReplay=struct('maxAbsXDiff',max(abs(kXR-kX),[],'all'), ...
    'maxAbsPDiff',max(abs(kPR-kP),[],'all'),'maxAbsDiagDiff', ...
    max(abs(kDR-kDiag),[],'all'),'timestampShiftApplied',false);
kReplay.pass=all([kReplay.maxAbsXDiff kReplay.maxAbsPDiff kReplay.maxAbsDiagDiff]<=1e-12);
oneHit=struct('D',dTiming.pass100Hz&&dReplay.pass&&alignD.allHitsResolved&& ...
    isequal(dStep(:),(0:nD-1).'),'K',kTiming.pass100Hz&&kReplay.pass&&alignK.allHitsResolved);

% Independent G1-A comparison only after actual input/condition audit.
g1=qualified_g1_comparison(g1File,tK,kU,kX,kP,kDiag,tSteer,cmd,vxK,vyK,perf.K.Vy);
dReference=struct('qualified',false, ...
    'statement','NO QUALIFIED INDEPENDENT GENUINE D-EKF 16-S REFERENCE AVAILABLE', ...
    'validationRoute','current 16-s exact replay is sufficient for non-interference');

independence=struct('formalGatesAllTrue',all(cellfun(@logical,struct2cell(F.report.gates))), ...
    'harnessGatesAllTrue',all(cellfun(@logical,struct2cell(H.report.gates))), ...
    'noDToK',true,'noKToD',true,'noCovarianceExchange',true, ...
    'noPseudoMeasurement',true,'noWeightedSum',true,'noSwitch',true,'noAlpha',true, ...
    'noReliability',true,'noLifeSig',true,'noThirdTrack',true,'noVyFinal',true, ...
    'runtimeDualReplayIndependent',dReplay.pass&&kReplay.pass&&report.static.schedulersIndependent);
independence.pass=independence.formalGatesAllTrue&&independence.harnessGatesAllTrue&& ...
    independence.runtimeDualReplayIndependent;

a=struct();
a.runtime=struct('simCalled',report.simCalled,'simulationCompleted',report.simulationCompleted, ...
    'carSimRun',report.carSimRun,'stopTimeActual_s',report.stopTimeActual_s, ...
    'solverActual',report.carSim.solverActual, ...
    'gRequest',report.carSim.gRequestBefore||report.carSim.gRequestConsole);
a.priorEvidence=prior;a.steering=steering;a.D=dStream;a.K=kStream;
a.timestampRelationship=timestamps;a.sharedPhysicalInputs=shared;a.KProcessInputs=kAy;
a.offlineTruth=truth;a.performance=perf;a.sameRunComparison=sameRun;
a.stateAlignedCovariance=covariance;a.yawExcitation=yaw;a.partitionPerformance=partitions;
a.complementarity=complementarity;a.DDiagnostics=dDiagnostics;a.KDiagnostics=kDiagnostics;
a.DExactReplay=dReplay;a.KExactReplay=kReplay;a.oneHit=oneHit;
a.KG1ANonInterference=g1;a.DIndependentReference=dReference;a.independence=independence;
a.hashIntegrity=struct('targetBefore',report.targetHashBefore,'targetAfter',report.targetHashAfter, ...
    'targetUnchanged',report.targetHashUnchanged,'allFrozenUnchanged',report.allFrozenHashesUnchanged);
a.dkekfRunPerformed=false;a.fusionPerformed=false;a.lifeSigImplemented=false;a.thirdTrackImplemented=false;
metricsFinite=all(isfinite([metrics_vector(perf.D.Vy) metrics_vector(perf.D.r) ...
    metrics_vector(perf.K.Vx) metrics_vector(perf.K.Vy)]));
a.pass=report.simCalled&&report.simulationCompleted&&report.carSimRun&& ...
    abs(report.stopTimeActual_s-16)<=1e-12&&~a.runtime.gRequest&&steering.pass&& ...
    dStream.pass&&kStream.pass&&timestamps.pass&&shared.pass&&kAy.pass&& ...
    metricsFinite&&dReplay.pass&&kReplay.pass&&oneHit.D&&oneHit.K&& ...
    independence.pass&&report.targetHashUnchanged&&report.allFrozenHashesUnchanged&&prior.pass;
report.analysis=a;save(f,'report','-v7.3');
fprintf(['V23D_ANALYSIS|pass=%d|steer=[%.17g %.17g %.17g %.3g]|' ...
    'D=%d|K=%d|dt=[%.17g %.17g]|Dreset=%d|Kreset=%d|DAy=%d|Kinputs=%d|' ...
    'Dreplay=[%.3g %.3g %.3g]|Kreplay=[%.3g %.3g %.3g]|oneHit=[%d %d]|hash=%d\n'], ...
    a.pass,steering.command.maxAbs,steering.convertedDeg.maxAbs,steering.frequency_Hz, ...
    steering.commandVsTheoryMaxAbsDiff,nD,nK,dTiming.dtMean,kTiming.dtMean, ...
    dReset.count,kReset.count,dAy.count,kAy.hitCount,dReplay.maxAbsXDiff, ...
    dReplay.maxAbsPDiff,dReplay.maxAbsDiagDiff,kReplay.maxAbsXDiff,kReplay.maxAbsPDiff, ...
    kReplay.maxAbsDiagDiff,oneHit.D,oneHit.K,a.hashIntegrity.targetUnchanged);
fprintf('PERF|D_Vy=%s|D_r=%s|K_Vx=%s|K_Vy=%s|lower=%s\n', ...
    mat2str(metrics_vector(perf.D.Vy),17),mat2str(metrics_vector(perf.D.r),17), ...
    mat2str(metrics_vector(perf.K.Vx),17),mat2str(metrics_vector(perf.K.Vy),17), ...
    sameRun.lowerVyRMSE);
fprintf(['PART|yaw=[%.17g %.17g %.17g %.17g]|low=%d/%.17g|higher=%d/%.17g|' ...
    'Dlow=%s|Dhigh=%s|Klow=%s|Khigh=%s\n'],yaw.meanAbs,yaw.medianAbs, ...
    yaw.p95Abs,yaw.maxAbs,yaw.lowCount,yaw.lowFraction,yaw.higherCount,yaw.higherFraction, ...
    mat2str(partition_vector(partitions.D.lowR),17),mat2str(partition_vector(partitions.D.higherR),17), ...
    mat2str(partition_vector(partitions.K.lowR),17),mat2str(partition_vector(partitions.K.higherR),17));
fprintf('COMP|corr=%.17g|meanAbsDelta=%.17g|overall=%s|low=%s|higher=%s|G1exact=%d\n', ...
    complementarity.pearsonErrorCorrelation,complementarity.meanAbsErrorDifference, ...
    mat2str(winner_vector(complementarity.overall),17), ...
    mat2str(winner_vector(complementarity.lowR),17), ...
    mat2str(winner_vector(complementarity.higherR),17),g1.samplewiseExactQualified);
end

function g=qualified_g1_comparison(file,t,u,x,P,d,tSteer,cmd,vxTrue,vyTrue,kPerf)
g=struct('performed',false,'samplewiseExactQualified',false,'reason','');
if ~isfile(file),g.reason='G1-A machine-readable result missing';return;end
S=load(file,'report');q=S.report;
if ~isfield(q,'analysis')||~q.steeringGate.pass,g.reason='G1-A analyzed genuine evidence invalid';return;end
r=q.raw;tOld=double(r.kkf_x_log1.time(:));n=numel(tOld);
uOld=sample_rows(r.kkf_u_log1.data,n,4);xOld=sample_rows(r.kkf_x_log1.data,n,2);
pOld=covariance_pages(r.kkf_P_log1.data,n,2);dOld=sample_rows(r.kkf_diag_log1.data,n,5);
[vxOld,~]=truth_at(r.vx_true_offline,tOld,1);[vyOld,~]=truth_at(r.vy_true_offline,tOld,1);
tSOld=double(r.steer_cmd_rad.time(:));cmdOld=vector(r.steer_cmd_rad);
g.performed=true;g.commandedConditionMatch=q.condition.Vx_mps==20&& ...
    q.condition.steerAmplitude_rad==.02&&q.condition.steerFrequency_Hz==.4&&q.stopTime_s==16;
g.timestampExact=isequal(t,tOld);g.inputMaxAbsDiff=conditional_diff(u,uOld,g.timestampExact);
g.truthMaxAbsDiff=conditional_diff([vxTrue vyTrue],[vxOld vyOld],g.timestampExact);
g.steeringTimeExact=isequal(tSteer,tSOld);
g.steeringMaxAbsDiff=conditional_diff(cmd,cmdOld,g.steeringTimeExact);
g.samplewiseExactQualified=g.commandedConditionMatch&&g.timestampExact&&g.steeringTimeExact&& ...
    g.inputMaxAbsDiff==0&&g.truthMaxAbsDiff==0&&g.steeringMaxAbsDiff==0;
if g.samplewiseExactQualified
    g.xMaxAbsDiff=max(abs(x-xOld),[],'all');g.PMaxAbsDiff=max(abs(P-pOld),[],'all');
    g.diagMaxAbsDiff=max(abs(d-dOld),[],'all');g.reason='actual inputs/truth/steering exact';
else
    g.xMaxAbsDiff=NaN;g.PMaxAbsDiff=NaN;g.diagMaxAbsDiff=NaN;
    g.reason='actual inputs not samplewise exact; metric-level reference only';
end
g.currentVyPerformance=kPerf;g.referenceVyPerformance=q.analysis.performance.Vy;
g.metricDifference=metric_difference(kPerf,q.analysis.performance.Vy);
end
function z=conditional_diff(a,b,eligible)
if eligible&&isequal(size(a),size(b)),z=max(abs(a-b),[],'all');else,z=NaN;end
end
function [y,a]=truth_at(rec,t,w)
tr=double(rec.time(:));yr=sample_rows(rec.data,numel(tr),w);[tr,ia]=unique(tr,'stable');yr=yr(ia,:);
tol=64*eps(max(1,max(abs(t))));assert(t(1)>=tr(1)-tol&&t(end)<=tr(end)+tol, ...
    'Truth does not cover estimator timestamps; extrapolation forbidden.');
[tf,loc]=ismember(t,tr);
if all(tf),y=yr(loc,:);method='exact timestamp match';delta=0;
else,y=interp1(tr,yr,t,'linear');assert(all(isfinite(y(:))));method='linear interpolation, no extrapolation';
    delta=max(arrayfun(@(q)min(abs(tr-q)),t));end
a=struct('sourceSampleCount',numel(tr),'targetSampleCount',numel(t), ...
    'sourceRange',[tr(1) tr(end)],'method',method,'maxNearestTimeDelta',delta);
end
function s=error_metrics(e)
s=struct('RMSE',sqrt(mean(e.^2)),'MAE',mean(abs(e)),'Bias',mean(e), ...
    'MaxAbsError',max(abs(e)),'FinalError',e(end));
end
function s=partition_error(e,m),assert(any(m));s=error_metrics(e(m));s.sampleCount=nnz(m);end
function d=metric_difference(a,b)
d=struct('RMSE',a.RMSE-b.RMSE,'MAE',a.MAE-b.MAE,'Bias',a.Bias-b.Bias, ...
    'MaxAbsError',a.MaxAbsError-b.MaxAbsError,'FinalError',a.FinalError-b.FinalError);
end
function s=winner_fractions(eD,eK)
aD=abs(eD);aK=abs(eK);d=aD<aK;k=aK<aD;tie=aD==aK;
s=struct('sampleCount',numel(eD),'DFraction',mean(d),'KFraction',mean(k), ...
    'tieFraction',mean(tie),'tieDefinition','exact equality of absolute errors');
end
function c=pearson(x,y)
q=corrcoef(x,y);if numel(q)<4||~isfinite(q(1,2)),c=NaN;else,c=q(1,2);end
end
function s=series_stats(x)
s=struct('initial',x(1),'final',x(end),'min',min(x),'max',max(x),'mean',mean(x));
end
function s=distribution_stats(x)
s=struct('sampleCount',numel(x),'mean',mean(x),'median',median(x), ...
    'p95',percentile(x,95),'max',max(x));
end
function s=innovation_stats(x)
s=struct('sampleCount',numel(x),'mean',mean(x),'RMS',sqrt(mean(x.^2)),'maxAbs',max(abs(x)));
end
function q=percentile(x,p)
x=sort(x(:));z=1+(numel(x)-1)*p/100;i=floor(z);j=ceil(z);
if i==j,q=x(i);else,q=x(i)+(z-i)*(x(j)-x(i));end
end
function f=fit_frequency(t,y),f=fminbnd(@(q)fit_error(q,t,y),.1,1);end
function e=fit_error(f,t,y),A=[sin(2*pi*f*t(:)) cos(2*pi*f*t(:))];e=norm(A*(A\y(:))-y(:))^2;end
function s=range_stats(x),s=struct('min',min(x),'max',max(x),'maxAbs',max(abs(x)));end
function v=vector(rec),v=double(rec.data(:));end
function a=sample_rows(data,n,w)
a=double(data);sz=size(a);if ismatrix(a),if isequal(sz,[n w]),return;end
if isequal(sz,[w n]),a=a.';return;end,end
if numel(a)==n*w,a=reshape(a,w,n).';return;end
error('VY_PARALLEL_DK:LogShape','Cannot resolve width %d from %s.',w,mat2str(sz));
end
function p=covariance_pages(data,n,w)
p=double(data);sz=size(p);if ndims(p)==3&&isequal(sz,[w w n]),return;end
if ndims(p)==3&&isequal(sz,[n w w]),p=permute(p,[2 3 1]);return;end
if ismatrix(p)&&isequal(sz,[n w*w]),p=reshape(p.',w,w,n);return;end
if numel(p)==w*w*n,p=reshape(p,w,w,n);return;end
error('VY_PARALLEL_DK:CovShape','Cannot resolve covariance %s.',mat2str(sz));
end
function s=timing_stats(t,Ts)
dt=diff(t);s=struct('tStart',t(1),'tEnd',t(end),'dtMin',min(dt), ...
    'dtMean',mean(dt),'dtMax',max(dt),'duplicateTimestampCount',nnz(dt<=0), ...
    'missingHitCount',sum(max(round(dt/Ts)-1,0)));
s.pass100Hz=all(abs(dt-Ts)<=1e-12)&&s.duplicateTimestampCount==0&& ...
    s.missingHitCount==0&&abs(t(1))<=1e-12&&abs(t(end)-16)<=1e-12;
end
function s=covariance_stats(P)
n=size(P,3);asym=zeros(n,1);mineig=zeros(n,1);
for k=1:n,asym(k)=max(abs(P(:,:,k)-P(:,:,k).'),[],'all'); ...
        mineig(k)=min(eig((P(:,:,k)+P(:,:,k).')/2));end
s=struct('maxAsymmetry',max(asym),'minimumEigenvalue',min(mineig));
s.valid=s.maxAsymmetry<=1e-12&&s.minimumEigenvalue>=-1e-12;
end
function [hits,audit]=input_rows_at_hits(data,inputTime,hitTime,w)
inputTime=double(inputTime(:));a=sample_rows(data,numel(inputTime),w);hits=zeros(numel(hitTime),w);
match=zeros(numel(hitTime),1);nearest=zeros(numel(hitTime),1);ambiguous=false;
for k=1:numel(hitTime),delta=abs(inputTime-hitTime(k));nearest(k)=min(delta);ix=find(delta==nearest(k));
    match(k)=numel(ix);tol=32*eps(max(1,abs(hitTime(k))));if nearest(k)>tol,continue;end
    c=a(ix,:);if size(c,1)>1&&any(max(abs(c-c(end,:)),[],2)>1e-12),ambiguous=true;end
    hits(k,:)=c(end,:);end
audit=struct('rawInputSampleCount',numel(inputTime),'hitSampleCount',numel(hitTime), ...
    'matchCountPerHit',match,'nearestTimeDelta',nearest, ...
    'allHitsResolved',all(match>=1)&&all(nearest==0),'duplicateMatchCount',nnz(match>1), ...
    'ambiguousDuplicate',ambiguous,'timestampShiftApplied',false);
end
function x=metrics_vector(s),x=[s.RMSE s.MAE s.Bias s.MaxAbsError s.FinalError];end
function x=partition_vector(s),x=[s.RMSE s.MAE s.Bias];end
function x=winner_vector(s),x=[s.DFraction s.KFraction s.tieFraction];end
