function report=analyze_vy_dkekf_v2_2d1_steer_smoke()
%ANALYZE_VY_DKEKF_V2_2D1_STEER_SMOKE Analyze D1 evidence; never simulates.
root=fileparts(fileparts(mfilename('fullpath')));
f=fullfile(root,'results','vy_dkekf_v2_2d1_steer_smoke.mat');
c2File=fullfile(root,'results','vy_dkekf_v2_2c2_preflight.mat');
S=load(f,'report');report=S.report;
assert(report.simulationCompleted&&report.carSimRun, ...
    'D1 simulation/CarSim completion evidence is missing.');
r=report.raw;
cmd=v(r.d1_steer_cmd_rad);deg=v(r.d1_steer_to_carsim_deg);
fl=v(r.d1_steer_fl_boundary_deg);fr=v(r.d1_steer_fr_boundary_deg);
rl=v(r.d1_steer_rl_boundary_deg);rr=v(r.d1_steer_rr_boundary_deg);
assert(isequal(numel(cmd),numel(deg),numel(fl),numel(fr),numel(rl),numel(rr)), ...
    'Steering evidence logs are not sample-aligned.');
t=double(r.dkekf_x_log1.time(:));n=numel(t);
outputLogsAligned=isequal(t,double(r.dkekf_P_log1.time(:)), ...
    double(r.dkekf_diag_log1.time(:)));
assert(outputLogsAligned,'DK-EKF x/P/diag logs do not share exact timestamps.');
[u,inputAlignment]=input_rows_at_hits(r.dkekf_u_log1.data, ...
    r.dkekf_u_log1.time,t,10);
assert(inputAlignment.allHitsResolved&&~inputAlignment.ambiguousDuplicate, ...
    'Runtime input log cannot be resolved exactly at every DK-EKF hit.');
x=sample_rows(r.dkekf_x_log1.data,n,3);
p=covariance_pages(r.dkekf_P_log1.data,n);
d=sample_rows(r.dkekf_diag_log1.data,n,7);
ix=abs(cmd)>1e-10;ratio=deg(ix)./cmd(ix);dt=diff(t);

g=struct();
g.simulationCompleted=report.simulationCompleted;
g.carSimRun=report.carSimRun;
g.sourceMin_rad=min(cmd);g.sourceMax_rad=max(cmd);
g.sourceMaxAbs_rad=max(abs(cmd));
g.sourceAmplitudeOK=abs(g.sourceMaxAbs_rad-0.02)<1e-6;
g.convertedMaxAbs_deg=max(abs(deg));
g.convertedMin_deg=min(deg);g.convertedMax_deg=max(deg);
g.convertedAmplitudeOK=abs(g.convertedMaxAbs_deg-0.02*180/pi)<1e-5;
g.ratioMedian=median(ratio);
g.ratioMaxError=max(abs(ratio-180/pi));
g.ratioOK=g.ratioMaxError<1e-10;
g.frequency_Hz=fitf(r.d1_steer_cmd_rad.time,cmd);
g.frequencyOK=abs(g.frequency_Hz-.4)<1e-5;
g.frontBoundaryMaxAbs_deg=[max(abs(fl)) max(abs(fr))];
g.flFrMaxAbsDiff=max(abs(fl-fr));
g.frontCommandMaxAbsDiff=max([abs(fl-deg);abs(fr-deg)]);
g.frontCommandMatch=g.frontCommandMaxAbsDiff<1e-12;
g.frontApplied=g.frontCommandMatch&&any(abs(fl)>1e-8)&&any(abs(fr)>1e-8);
g.rearMaxAbs_deg=[max(abs(rl)) max(abs(rr))];
g.rearZero=all(g.rearMaxAbs_deg<1e-12);
avz=v(r.d1_avz_imu);
g.avzMaxAbs_radps=max(abs(avz));
g.avzRMS_radps=sqrt(mean(avz.^2));
g.c2YawComparison=compare_c2(c2File,r.d1_avz_imu);
g.avzPhysicalYawResponse=~g.c2YawComparison.exactEqual&& ...
    g.c2YawComparison.maxAbsDiff>1e-6;
g.timing=struct('xSampleCount',r.dkekf_x_log1.sampleCount, ...
    'pSampleCount',r.dkekf_P_log1.sampleCount, ...
    'diagSampleCount',r.dkekf_diag_log1.sampleCount, ...
    'rawInputSampleCount',r.dkekf_u_log1.sampleCount, ...
    'tStart',t(1),'tEnd',t(end),'dtMin',min(dt),'dtMean',mean(dt), ...
    'dtMax',max(dt),'duplicateTimestampCount',nnz(dt<=0), ...
    'missingHitCount',sum(max(round(dt/0.01)-1,0)), ...
    'outputLogsAligned',outputLogsAligned,'inputAlignment',inputAlignment);
g.dkekf100Hz=all(abs(dt-.01)<1e-12)&& ...
    g.timing.duplicateTimestampCount==0&&g.timing.missingHitCount==0&& ...
    n==round((t(end)-t(1))/.01)+1;
g.dkekfSampleCount=n;
res=u(:,6)>.5;g.resetHighCount=nnz(res);g.resetTimestamps=t(res);
g.resetOnceAtT0=g.resetHighCount==1&&abs(g.resetTimestamps(1))<1e-12;
g.resetInitialStatePrior=[u(1,4);0;0];
g.resetInitialCovariancePrior=diag([0.1 0.1 0.1]);
g.trueVyUsedForInitialization=false;
ay=u(:,5)>.5;
applied=d(:,4)>.5;g.doAyUpdateHighCount=nnz(ay);
g.ayUpdateAppliedCount=nnz(applied);g.doAyUpdateTimestamps=t(ay);
g.ayUpdateAppliedTimestamps=t(applied);
g.aySequenceExact=isequal(ay,applied);g.ay20Hz=g.aySequenceExact;
g.dimensions=struct('x',size(x,2),'P',size(p(:,:,1)),'diag',size(d,2));
g.dimensionsOK=g.dimensions.x==3&&isequal(g.dimensions.P,[3 3])&&g.dimensions.diag==7;
g.finiteX=all(isfinite(x(:)));g.finiteP=all(isfinite(p(:)));
g.finiteDiag=all(isfinite(d(:)));g.finite=g.finiteX&&g.finiteP&&g.finiteDiag;
pd=zeros(n,3);for k=1:n,pd(k,:)=diag(p(:,:,k)).';end
g.covariance=struct('maxAsymmetry',max(abs(p-permute(p,[2 1 3])),[],'all'), ...
    'minEigenvalue',min(arrayfun(@(k)min(eig((p(:,:,k)+p(:,:,k)')/2)),1:size(p,3))), ...
    'p11MinMax',[min(pd(:,1)) max(pd(:,1))], ...
    'p22MinMax',[min(pd(:,2)) max(pd(:,2))], ...
    'p33MinMax',[min(pd(:,3)) max(pd(:,3))]);
g.covarianceValid=g.covariance.maxAsymmetry<=1e-12&& ...
    g.covariance.minEigenvalue>=-1e-12;
[rx,rp,rd]=replay(u);
g.exactReplay=struct('maxAbsXDiff',max(abs(rx(:)-x(:))), ...
    'maxAbsPDiff',max(abs(rp(:)-p(:))), ...
    'maxAbsDiagDiff',max(abs(rd(:)-d(:))));
g.exactReplayOK=all(struct2array(g.exactReplay)<=1e-12);
g.oneHitOneCommittedAdvance=g.dkekf100Hz&&g.exactReplayOK&& ...
    inputAlignment.allHitsResolved&&~inputAlignment.timestampShiftApplied;
c2=load(c2File,'report');g.fairness=c2.report.static.fairness;
g.fairness.pass=~g.fairness.trueVyOnline&&g.fairness.trueVxMeasurementOnly&& ...
    g.fairness.axPredictionInput&&g.fairness.avzMeasurementOnly&& ...
    g.fairness.ayMeasurementOnly&&g.fairness.sharedStateAndP&& ...
    ~g.fairness.outputFusion&&~g.fairness.lifeSig&&~g.fairness.adaptiveFusion;
g.frozenHashUnchanged=report.frozenHashUnchanged&& ...
    report.allFrozenHashesUnchanged&&report.validationModelHashUnchanged;
g.newModelHash=report.newModelHash;
g.pass=g.simulationCompleted&&g.carSimRun&&g.sourceAmplitudeOK&& ...
    g.convertedAmplitudeOK&&g.ratioOK&& ...
    g.frequencyOK&&g.frontApplied&&g.rearZero&&g.avzPhysicalYawResponse&& ...
    g.dkekf100Hz&&g.resetOnceAtT0&&g.ay20Hz&&g.dimensionsOK&&g.finite&& ...
    g.covarianceValid&&g.exactReplayOK&&g.oneHitOneCommittedAdvance&& ...
    g.fairness.pass&&g.frozenHashUnchanged;
report.analysis=g;save(f,'report','-v7.3');
fprintf(['V2_2D1_ANALYSIS|pass=%d|src=%.15g|deg=%.15g|ratioErr=%.3g|' ...
    'front=[%.15g %.15g]|frontCmdDiff=%.3g|rear=[%.15g %.15g]|' ...
    'avzMax=%.15g|avzRMS=%.15g|c2Diff=[%.15g %.15g]|' ...
    'samples=%d/%d/%d|t=[%.15g %.15g]|dt=[%.15g %.15g %.15g]|' ...
    'reset=%d|Ay=%d/%d|finite=%d|P=[%.3g %.15g]|' ...
    'replay=[%.3g %.3g %.3g]|oneHit=%d\n'], ...
    g.pass,g.sourceMaxAbs_rad,g.convertedMaxAbs_deg,g.ratioMaxError, ...
    g.frontBoundaryMaxAbs_deg,g.frontCommandMaxAbsDiff,g.rearMaxAbs_deg, ...
    g.avzMaxAbs_radps,g.avzRMS_radps,g.c2YawComparison.maxAbsDiff, ...
    g.c2YawComparison.rmsDiff,g.timing.xSampleCount,g.timing.pSampleCount, ...
    g.timing.diagSampleCount,g.timing.tStart,g.timing.tEnd,g.timing.dtMin, ...
    g.timing.dtMean,g.timing.dtMax,g.resetHighCount,g.doAyUpdateHighCount, ...
    g.ayUpdateAppliedCount,g.finite,g.covariance.maxAsymmetry, ...
    g.covariance.minEigenvalue,g.exactReplay.maxAbsXDiff, ...
    g.exactReplay.maxAbsPDiff,g.exactReplay.maxAbsDiagDiff, ...
    g.oneHitOneCommittedAdvance);
end
function y=v(r),y=double(r.data(:));end
function a=sample_rows(data,n,w),a=double(data);s=size(a);if ismatrix(a),if isequal(s,[n w]),return;end;if isequal(s,[w n]),a=a.';return;end,end;if numel(a)==n*w,a=reshape(a,w,n).';return;end;error('VY_DKEKF:LogShape','Cannot resolve %d-wide log with size %s.',w,mat2str(s));end
function [hits,audit]=input_rows_at_hits(data,inputTime,hitTime,w),inputTime=double(inputTime(:));a=sample_rows(data,numel(inputTime),w);hits=zeros(numel(hitTime),w);matchCount=zeros(numel(hitTime),1);nearCount=zeros(numel(hitTime),1);nearestDelta=zeros(numel(hitTime),1);ambiguous=false;for k=1:numel(hitTime),tol=32*eps(max(1,abs(hitTime(k))));delta=abs(inputTime-hitTime(k));nearestDelta(k)=min(delta);ix=find(delta==nearestDelta(k));matchCount(k)=numel(ix);nearCount(k)=nnz(delta<=tol);if nearestDelta(k)>tol,continue;end;c=a(ix,:);if size(c,1)>1&&any(max(abs(c-c(end,:)),[],2)>1e-12),ambiguous=true;end;hits(k,:)=c(end,:);end;audit=struct('rawInputSampleCount',numel(inputTime),'hitSampleCount',numel(hitTime),'matchCountPerHit',matchCount,'nearCoincidentCountPerHit',nearCount,'nearestTimeDelta',nearestDelta,'allHitsResolved',all(matchCount>=1)&&all(nearestDelta==0),'duplicateMatchCount',nnz(matchCount>1),'ambiguousDuplicate',ambiguous,'timestampShiftApplied',false);end
function p=covariance_pages(data,n),p=double(data);s=size(p);if ndims(p)==3&&isequal(s,[3 3 n]),return;end;if ndims(p)==3&&isequal(s,[n 3 3]),p=permute(p,[2 3 1]);return;end;if ismatrix(p)&&isequal(s,[n 9]),p=reshape(p.',3,3,n);return;end;if numel(p)==9*n,p=reshape(p,3,3,n);return;end;error('VY_DKEKF:LogShape','Cannot resolve covariance log size %s.',mat2str(s));end
function f=fitf(t,y),f=fminbnd(@(q)fiterr(q,t,y),.1,1);end
function e=fiterr(f,t,y),A=[sin(2*pi*f*t(:)) cos(2*pi*f*t(:))];e=norm(A*(A\y(:))-y(:))^2;end
function c=compare_c2(f,newRec)
S=load(f,'report');old=S.report.raw.dkekf_u_log1;
u=sample_rows(old.data,old.sampleCount,10);to=double(old.time(:));yo=u(:,3);
tn=double(newRec.time(:));yn=v(newRec);[tn,ia]=unique(tn,'stable');yn=yn(ia);
keep=to>=tn(1)&to<=min([tn(end),0.20]);ti=to(keep);oldAy=yo(keep);
newAy=interp1(tn,yn,ti,'linear');delta=newAy-oldAy;
c=struct('sampleCount',numel(ti),'newMaxAbs',max(abs(newAy)), ...
    'newRMS',sqrt(mean(newAy.^2)),'c2MaxAbs',max(abs(oldAy)), ...
    'c2RMS',sqrt(mean(oldAy.^2)),'maxAbsDiff',max(abs(delta)), ...
    'rmsDiff',sqrt(mean(delta.^2)),'exactEqual',isequaln(newAy,oldAy));
end
function [xr,pr,dr]=replay(u),n=size(u,1);xr=zeros(n,3);pr=zeros(3,3,n);dr=zeros(n,7);par=struct('m',1860,'Iz',2687.1,'a',1.18,'b',1.77,'track',1.575,'Rw',.393,'k_f',.78181,'k_r',1.09186);cfg=struct('Q_DK',diag([1e-4 1e-4 1e-4]),'R_Vx',1e-4,'R_r',3.365172961808e-4,'R_Ay',1e-2,'jacobianStep',1e-6,'denomEps',1e-12,'lambda',zeros(4,1));P0=diag([.1 .1 .1]);init=false;xs=zeros(3,1);ps=P0;for k=1:n,if ~init||u(k,6)>.5,x0=[u(k,4);0;0];p0=P0;else,x0=xs;p0=ps;end;[xn,pn,info]=vy_dkekf_baseline_step(x0,p0,u(k,1),u(k,7:10).',u(k,4),u(k,3),u(k,2),u(k,5),.01,par,cfg);na=info.Ay.NIS;if ~info.Ay.updateApplied&&isnan(na),na=0;end;xr(k,:)=xn.';pr(:,:,k)=pn;dr(k,:)=[info.Vx.NIS info.r.NIS na double(info.Ay.updateApplied) info.Vx.innovation info.r.innovation info.Ay.innovation];xs=xn;ps=pn;init=true;end,end
