function report = analyze_vy_kkf_v2_1e_highyaw()
%ANALYZE_VY_KKF_V2_1E_HIGHYAW Analyze E runtime and one B3 replay.

root = fileparts(fileparts(mfilename('fullpath')));
resultFile = fullfile(root, 'results', 'vy_kkf_v2_1e_highyaw.mat');
csvFile = fullfile(root, 'results', 'vy_kkf_v2_1e_highyaw.csv');
plotDir = fullfile(root, 'results', 'plots', 'vy_kkf_v2_1e_highyaw');
assert(isfile(resultFile), 'V2.1-E runtime MAT does not exist.');
saved = load(resultFile, 'report');
assert(isfield(saved, 'report') && saved.report.simulationCompleted, ...
    'V2.1-E runtime did not complete.');
report = saved.report;

names = {'kkf_u_log1','kkf_x_log1','kkf_P_log1','kkf_diag_log1'};
counts = zeros(1,4);
for k = 1:4
    rec = report.raw.(names{k});
    counts(k) = rec.sampleCount;
    assert(rec.sampleCount > 0 && all(diff(rec.time) > 0), ...
        'Runtime log is empty or non-monotonic: %s', names{k});
end
t = report.raw.kkf_x_log1.time(:);
aligned = true;
for k = 1:4
    tk = report.raw.(names{k}).time(:);
    aligned = aligned && numel(tk) == numel(t) && ...
        max(abs(tk-t)) <= 10*eps(max(1,max(abs(t))));
end
assert(aligned, 'Four K-KF logs are not timestamp-aligned.');

u = sample_matrix(report.raw.kkf_u_log1.data, counts(1));
x = sample_matrix(report.raw.kkf_x_log1.data, counts(2));
P = covariance_samples(report.raw.kkf_P_log1.data, counts(3));
diagnostic = sample_matrix(report.raw.kkf_diag_log1.data, counts(4));
assert(size(u,2) == 4 && size(x,2) == 2 && size(diagnostic,2) == 5, ...
    'K-KF runtime log dimensions are invalid.');

vxRaw = scalar_record(report.raw.vx_true_offline);
vyRaw = scalar_record(report.raw.vy_true_offline);
assert(all(diff(vxRaw.time) > 0) && all(diff(vyRaw.time) > 0), ...
    'Offline truth timestamps are not monotonic.');
vxTrue = interp1(vxRaw.time, vxRaw.data, t, 'linear');
vyTrue = interp1(vyRaw.time, vyRaw.data, t, 'linear');

resetRec = report.raw.kkf_reset_trace_e;
resetData = sample_matrix(resetRec.data, resetRec.sampleCount);
resetHigh = resetData(:,1) > 0.5;
dt = diff(t);
report.timing = struct('sampleCount', numel(t), 'tStart', t(1), ...
    'tEnd', t(end), 'dtMin', min(dt), 'dtMedian', median(dt), ...
    'dtMax', max(dt), 'abnormalDtCount', ...
    sum(abs(dt-0.01) > 1e-12), 'strictlyIncreasing', all(dt > 0), ...
    'fourLogsAligned', aligned, 'logSampleCounts', counts);
report.reset = struct('sampleCount', resetRec.sampleCount, ...
    'highCount', sum(resetHigh), ...
    'highTimestamps', resetRec.time(resetHigh));

vxError = x(:,1) - vxTrue;
vyError = x(:,2) - vyTrue;
report.onlineMetrics = struct('Vx', error_metrics(vxError), ...
    'Vy', error_metrics(vyError));
report.onlineMetrics.Vy.FinalError = vyError(end);

p11 = squeeze(P(1,1,:));
p22 = squeeze(P(2,2,:));
asymmetry = zeros(numel(t),1);
minimumEigenvalue = inf;
for k = 1:numel(t)
    pk = P(:,:,k);
    asymmetry(k) = max(abs(pk-pk.'), [], 'all');
    minimumEigenvalue = min(minimumEigenvalue, ...
        min(eig(0.5*(pk+pk.'))));
end
report.sanity = struct('allXFinite', all(isfinite(x(:))), ...
    'allPFinite', all(isfinite(P(:))), ...
    'allDiagnosticFinite', all(isfinite(diagnostic(:))), ...
    'allTruthFinite', all(isfinite(vxTrue)) && all(isfinite(vyTrue)), ...
    'P11_Min', min(p11), 'P11_Max', max(p11), ...
    'P22_Min', min(p22), 'P22_Max', max(p22), ...
    'P22_Final', p22(end), 'maxPAsymmetry', max(asymmetry), ...
    'minimumPEigenvalue', minimumEigenvalue);

nis = diagnostic(:,1);
report.nis = struct('mean', mean(nis), 'median', median(nis), ...
    'percentile95', prctile(nis,95), 'maximum', max(nis), ...
    'fractionAboveReference', mean(nis > 3.8414588), ...
    'reference95', 3.8414588);

lowR = abs(u(:,3)) <= 0.01;
higherR = ~lowR;
assert(any(lowR) && any(higherR), ...
    'Both observability partitions are required.');
report.observability = struct('signal', 'online AVz_IMU', ...
    'threshold', 0.01, 'low', partition_metrics(vyError, lowR), ...
    'higher', partition_metrics(vyError, higherR));

k21Abs = abs(diagnostic(:,5));
rAbs = abs(u(:,3));
corrMatrix = corrcoef(rAbs, k21Abs);
report.k21 = struct('low', value_stats(k21Abs(lowR)), ...
    'higher', value_stats(k21Abs(higherR)), ...
    'allMaximum', max(k21Abs), ...
    'correlationAbsRAbsK21', corrMatrix(1,2));
if report.k21.low.mean > 1e-15
    report.k21.higherToLowMeanRatio = ...
        report.k21.higher.mean/report.k21.low.mean;
else
    report.k21.higherToLowMeanRatio = NaN;
end

% Hard-gated B0 replay using the frozen wrapper and online reset sequence.
[xB0, PB0, diagB0] = replay_case(u(:,1:3), u(:,4));
report.equivalence = struct('threshold', 1e-12, ...
    'maxAbsXDiff', max(abs(xB0(:)-x(:))), ...
    'maxAbsPDiff', max(abs(PB0(:)-P(:))), ...
    'maxAbsDiagDiff', max(abs(diagB0(:)-diagnostic(:))));
report.equivalence.passed = ...
    report.equivalence.maxAbsXDiff <= report.equivalence.threshold && ...
    report.equivalence.maxAbsPDiff <= report.equivalence.threshold && ...
    report.equivalence.maxAbsDiagDiff <= report.equivalence.threshold;
if ~report.equivalence.passed
    report.stopState = 'V2.1-E BLOCKED: BASELINE REPLAY NOT EQUIVALENT';
    save(resultFile, 'report', '-v7.3');
    error('VY_KKF:V2_1EReplayNotEquivalent', '%s', report.stopState);
end

% The only authorized de-biased replay is B3: remove Ay and AVz biases.
uB3 = u(:,1:3);
uB3(:,2) = uB3(:,2) - 0.02;
uB3(:,3) = uB3(:,3) - 0.005;
[xB3, PB3, diagB3] = replay_case(uB3, u(:,4));
vyErrorB3 = xB3(:,2) - vyTrue;
p22B3 = squeeze(PB3(2,2,:));
report.b3 = struct('definition', ...
    'Ay_test=Ay_IMU-0.02; r_test=AVz_IMU-0.005; Ax unchanged', ...
    'metrics', error_metrics(vyErrorB3), ...
    'FinalVyError', vyErrorB3(end), 'P22_Final', p22B3(end), ...
    'P22_Max', max(p22B3), ...
    'RMSE_ReductionPct', 100*(report.onlineMetrics.Vy.RMSE - ...
        sqrt(mean(vyErrorB3.^2)))/report.onlineMetrics.Vy.RMSE, ...
    'FinalDriftReductionPct', 100*(abs(vyError(end)) - ...
        abs(vyErrorB3(end)))/abs(vyError(end)), ...
    'x', xB3, 'P', PB3, 'diagnostic', diagB3, ...
    'vyError', vyErrorB3);

% C1 references are taken only from the two required, independently accepted
% C1/D status documents.
c1 = struct('steerAmplitude_rad', 0.02, ...
    'higherRFraction', 0.0530918176139913, ...
    'onlineVyRMSE', 0.797460298986494, ...
    'onlineFinalVyError', -1.36648988303603, ...
    'onlineP22Final', 1.65527382938442, ...
    'onlineP22Max', 1.65527382938442, ...
    'b3VyRMSE', 0.0161451899263298, ...
    'b3FinalVyError', 0.0176916407062626, ...
    'b3P22Final', 1.69121603961661, ...
    'k21ReferenceAvailable', false);
e = struct('steerAmplitude_rad', report.condition.steerAmplitude_rad, ...
    'higherRFraction', report.observability.higher.sampleFraction, ...
    'onlineVyRMSE', report.onlineMetrics.Vy.RMSE, ...
    'onlineFinalVyError', report.onlineMetrics.Vy.FinalError, ...
    'onlineP22Final', report.sanity.P22_Final, ...
    'onlineP22Max', report.sanity.P22_Max, ...
    'b3VyRMSE', report.b3.metrics.RMSE, ...
    'b3FinalVyError', report.b3.FinalVyError, ...
    'b3P22Final', report.b3.P22_Final, ...
    'meanAbsK21Low', report.k21.low.mean, ...
    'meanAbsK21Higher', report.k21.higher.mean, ...
    'corrAbsRAbsK21', report.k21.correlationAbsRAbsK21);
report.comparison = struct('referenceSource', ...
    'accepted C1 and D stage status documents', 'C1', c1, 'E', e, ...
    'higherRFractionMultiple', e.higherRFraction/c1.higherRFraction, ...
    'onlineP22FinalReductionPct', ...
        100*(c1.onlineP22Final-e.onlineP22Final)/c1.onlineP22Final, ...
    'b3RMSEChangePctVsC1', ...
        100*(e.b3VyRMSE-c1.b3VyRMSE)/c1.b3VyRMSE);

report.samples = struct('time', t, 'u', u, 'xOnline', x, ...
    'POnline', P, 'diagnosticOnline', diagnostic, ...
    'vxTrue', vxTrue, 'vyTrue', vyTrue, 'vxError', vxError, ...
    'vyError', vyError, 'lowRFlag', lowR, 'xB0', xB0, ...
    'PB0', PB0, 'diagB0', diagB0, 'xB3', xB3, 'PB3', PB3, ...
    'diagB3', diagB3, 'vyErrorB3', vyErrorB3, ...
    'resetTime', resetRec.time, 'resetData', resetData(:,1));

T = table(t, u(:,1), u(:,2), u(:,3), u(:,4), x(:,1), x(:,2), ...
    vxTrue, vyTrue, vxError, vyError, p11, p22, nis, diagnostic(:,5), ...
    k21Abs, lowR, xB0(:,1), xB0(:,2), xB3(:,2), vyErrorB3, p22B3, ...
    'VariableNames', {'time','Ax_IMU','Ay_IMU','AVz_IMU','Vx_meas', ...
    'Vx_online','Vy_online','Vx_true','Vy_true','Vx_error','Vy_error', ...
    'P11','P22','NIS','K21','abs_K21','low_r_flag','Vx_B0','Vy_B0', ...
    'Vy_B3','Vy_B3_error','P22_B3'});
writetable(T, csvFile);
report.csv = struct('path', csvFile, 'rowCount', height(T), ...
    'columnNames', {T.Properties.VariableNames}, ...
    'trueVyUse', 'offline validation only');

if ~isfolder(plotDir), mkdir(plotDir); end
report.plots = make_plots(plotDir, t, u(:,3), x(:,2), vyTrue, ...
    vyError, diagnostic(:,5), p22, p22B3, c1.onlineP22Final, xB3(:,2));

frozen = { ...
    fullfile(root, 'model', 'vx.slx'), ...
    fullfile(root, 'model', 'vx_ax_imu_prereq_v2_1.slx'), ...
    fullfile(root, 'model', 'vx_vy_kkf_v2_1.slx'), ...
    fullfile(root, 'model', 'vx_vy_dekf_v1_17.slx'), ...
    fullfile(root, 'matlab', 'vy_kinematic_kf_step.m'), ...
    fullfile(root, 'matlab', 'vy_kinematic_kf.m')};
expected = { ...
    '754a94d85bd50f89ae453c544903dea90b7f9d57d6e7706869f9f674fb0464eb', ...
    '226238301763460f4b609b0249d61b720c6510dd561923c5d066c33e5967f439', ...
    'b67a98a6080374304e2d3424f85589c913e6ec4db25bc9912cbfd2bc441c2712', ...
    '108f819dcd1b71fd6d795d7148cbf32fe1a888ae9878908e894a07626ed003ae', ...
    '3786646ee5163d231dd8964614a8875217dfa496eb593b455e4e029e26da2244', ...
    'f242cb75ba08d22cb1eed87731746cf80d54fd39c1899b45e9980a40576414d4'};
report.finalFrozenHashes = hash_files(frozen);
report.finalFrozenHashesMatch = true;
for k = 1:numel(frozen)
    report.finalFrozenHashesMatch = report.finalFrozenHashesMatch && ...
        strcmp(report.finalFrozenHashes(k).sha256, expected{k});
end
assert(report.finalFrozenHashesMatch && report.frozenHashesUnchanged, ...
    'Frozen hash evidence failed after E analysis.');
report.stopState = 'V2.1-E HIGHER-YAW VALIDATION COMPLETED';
save(resultFile, 'report', '-v7.3');

fprintf(['V2_1E_ANALYSIS_OK|N=%d|dt=%.17g|reset=%d|' ...
    'higherFrac=%.17g|K21ratio=%.17g|K21corr=%.17g|' ...
    'VyRMSE=%.17g|P22final=%.17g|B3RMSE=%.17g|' ...
    'xdiff=%.17g|Pdiff=%.17g|diagdiff=%.17g|plots=%d\n'], ...
    numel(t), report.timing.dtMedian, report.reset.highCount, ...
    report.observability.higher.sampleFraction, ...
    report.k21.higherToLowMeanRatio, ...
    report.k21.correlationAbsRAbsK21, report.onlineMetrics.Vy.RMSE, ...
    report.sanity.P22_Final, report.b3.metrics.RMSE, ...
    report.equivalence.maxAbsXDiff, report.equivalence.maxAbsPDiff, ...
    report.equivalence.maxAbsDiagDiff, numel(report.plots));
end

function [xLog, PLog, diagLog] = replay_case(u, z)
clear vy_kinematic_kf
n = size(u,1);
xLog = zeros(n,2); PLog = zeros(2,2,n); diagLog = zeros(n,5);
for k = 1:n
    [xk, Pk, dk] = vy_kinematic_kf(u(k,:).', z(k), double(k==1));
    xLog(k,:) = xk.'; PLog(:,:,k) = Pk; diagLog(k,:) = dk.';
end
clear vy_kinematic_kf
end

function m = error_metrics(e)
m = struct('RMSE', sqrt(mean(e.^2)), 'MAE', mean(abs(e)), ...
    'Bias', mean(e), 'MaxAbsError', max(abs(e)));
end

function m = partition_metrics(e, mask)
m = error_metrics(e(mask));
m.sampleCount = sum(mask); m.sampleFraction = mean(mask);
end

function s = value_stats(v)
s = struct('mean', mean(v), 'median', median(v), 'maximum', max(v));
end

function scalar = scalar_record(rec)
matrix = sample_matrix(rec.data, rec.sampleCount);
assert(size(matrix,2) == 1, 'Offline truth signal must be scalar.');
scalar = struct('time', rec.time(:), 'data', matrix(:,1));
end

function matrix = sample_matrix(data, sampleCount)
sz = size(data);
sampleDim = find(sz == sampleCount, 1, 'last');
assert(~isempty(sampleDim), 'Cannot identify sample dimension.');
order = [sampleDim, setdiff(1:ndims(data), sampleDim, 'stable')];
matrix = reshape(permute(data, order), sampleCount, []);
end

function P = covariance_samples(data, sampleCount)
sz = size(data);
sampleDim = find(sz == sampleCount, 1, 'last');
assert(~isempty(sampleDim), 'Cannot identify covariance sample dimension.');
other = setdiff(1:ndims(data), sampleDim, 'stable');
assert(prod(sz(other)) == 4, 'Covariance log is not 2x2 per sample.');
P = reshape(permute(data, [other sampleDim]), 2, 2, sampleCount);
end

function paths = make_plots(plotDir, t, r, vy, vyTrue, vyError, ...
    k21, p22, p22B3, c1P22Final, vyB3)
paths = cell(6,1);
paths{1} = fullfile(plotDir, '01_avz_threshold.png');
f = new_figure(); plot(t,abs(r),'LineWidth',1.05); hold on;
yline(0.01,'r--','LineWidth',1.2); grid on; xlabel('Time (s)');
ylabel('|AVz IMU| (rad/s)'); title('Higher-yaw AVz IMU excitation');
legend('|AVz IMU|','threshold 0.01','Location','best'); save_figure(f,paths{1});

paths{2} = fullfile(plotDir, '02_vy_online_vs_true.png');
f = new_figure(); plot(t,vy,'LineWidth',1.2); hold on;
plot(t,vyTrue,'k--','LineWidth',1.2); grid on; xlabel('Time (s)');
ylabel('Vy (m/s)'); title('Higher-yaw online Vy vs true Vy');
legend('online K-KF','true Vy offline only','Location','best');
save_figure(f,paths{2});

paths{3} = fullfile(plotDir, '03_vy_online_error.png');
f = new_figure(); plot(t,vyError,'LineWidth',1.15); grid on; yline(0,'k:');
xlabel('Time (s)'); ylabel('Vy error (m/s)');
title('Higher-yaw online Vy error'); save_figure(f,paths{3});

paths{4} = fullfile(plotDir, '04_k21_vs_avz.png');
f = new_figure(); tl = tiledlayout(f,2,1,'TileSpacing','compact');
nexttile(tl); plot(t,abs(r),'LineWidth',1); hold on;
yline(0.01,'r--','LineWidth',1.1); grid on; ylabel('|AVz IMU|');
nexttile(tl); plot(t,abs(k21),'LineWidth',1); grid on;
ylabel('|K21|'); xlabel('Time (s)');
title(tl,'Yaw excitation and Vx-to-Vy Kalman coupling');
save_figure(f,paths{4});

paths{5} = fullfile(plotDir, '05_p22_comparison.png');
f = new_figure(); plot(t,p22,'LineWidth',1.2); hold on;
plot(t,p22B3,'--','LineWidth',1.2); yline(c1P22Final,'k:', ...
    'LineWidth',1.2); grid on; xlabel('Time (s)'); ylabel('P22');
title('Higher-yaw P22 with accepted C1 final reference');
legend('E online B0','E offline B3','C1 final P22 reference', ...
    'Location','best'); save_figure(f,paths{5});

paths{6} = fullfile(plotDir, '06_vy_online_b3_true.png');
f = new_figure(); plot(t,vyTrue,'k--','LineWidth',1.3); hold on;
plot(t,vy,'LineWidth',1.15); plot(t,vyB3,'LineWidth',1.15); grid on;
xlabel('Time (s)'); ylabel('Vy (m/s)');
title('Higher-yaw online B0 and offline B3 (true Vy offline only)');
legend('true Vy offline','online B0','offline B3','Location','best');
save_figure(f,paths{6});
end

function f = new_figure()
f = figure('Visible','off','Color','w','Position',[100 100 1100 700]);
end

function save_figure(f, path)
exportgraphics(f, path, 'Resolution', 150); close(f);
end

function hashes = hash_files(files)
hashes = repmat(struct('path','','sha256',''), numel(files), 1);
for k = 1:numel(files)
    hashes(k).path = files{k}; hashes(k).sha256 = file_sha256(files{k});
end
end

function hashText = file_sha256(filePath)
digest = java.security.MessageDigest.getInstance('SHA-256');
stream = java.io.FileInputStream(java.io.File(filePath));
digestStream = java.security.DigestInputStream(stream, digest);
cleanup = onCleanup(@() digestStream.close());
while digestStream.read() ~= -1
end
bytes = typecast(digest.digest(), 'uint8');
hashText = lower(reshape(dec2hex(bytes, 2).', 1, []));
clear cleanup
end
