function report=analyze_vy_dkekf_v2_2d2_nominal_validation()
%ANALYZE_VY_DKEKF_V2_2D2_NOMINAL_VALIDATION Offline-only D2 analysis.
root=fileparts(fileparts(mfilename('fullpath')));
f=fullfile(root,'results','vy_dkekf_v2_2d2_nominal_validation.mat');
c2File=fullfile(root,'results','vy_dkekf_v2_2c2_preflight.mat');
g1File=fullfile(root,'results','vy_kkf_v2_1g1_nominal_002.mat');
S=load(f,'report');report=S.report;
assert(report.simulationCompleted&&report.simCalled&&report.carSimRun, ...
    'D2 simulation/CarSim completion evidence is missing.');
r=report.raw;

cmd=v(r.d1_steer_cmd_rad);deg=v(r.d1_steer_to_carsim_deg);
fl=v(r.d1_steer_fl_boundary_deg);fr=v(r.d1_steer_fr_boundary_deg);
rl=v(r.d1_steer_rl_boundary_deg);rr=v(r.d1_steer_rr_boundary_deg);
assert(isequal(numel(cmd),numel(deg),numel(fl),numel(fr),numel(rl),numel(rr)), ...
    'Steering evidence logs are not sample-aligned.');
t=double(r.dkekf_x_log1.time(:));n=numel(t);dt=diff(t);
outputLogsAligned=isequal(t,double(r.dkekf_P_log1.time(:)), ...
    double(r.dkekf_diag_log1.time(:)));
assert(outputLogsAligned,'DK-EKF x/P/diag logs do not share exact timestamps.');
[u,inputAlignment]=input_rows_at_hits(r.dkekf_u_log1.data,r.dkekf_u_log1.time,t,10);
assert(inputAlignment.allHitsResolved&&~inputAlignment.ambiguousDuplicate, ...
    'Runtime input log cannot be resolved exactly at every DK-EKF hit.');
x=sample_rows(r.dkekf_x_log1.data,n,3);
p=covariance_pages(r.dkekf_P_log1.data,n);
d=sample_rows(r.dkekf_diag_log1.data,n,7);

ix=abs(cmd)>1e-10;ratio=deg(ix)./cmd(ix);
a=struct();a.runtime=struct('simulationCompleted',report.simulationCompleted, ...
    'simCalled',report.simCalled,'carSimRun',report.carSimRun, ...
    'progDir',report.carSim.progDir,'dataDir',report.carSim.dataDir, ...
    'solverPath',report.carSim.actualSolverPath, ...
    'gDriveRequest',report.carSim.historicalGDriveRequestPresent);
a.steering=struct('sourceMaxAbs_rad',max(abs(cmd)), ...
    'convertedMaxAbs_deg',max(abs(deg)),'ratioMedian',median(ratio), ...
    'ratioMaxError',max(abs(ratio-180/pi)), ...
    'flMaxAbs_deg',max(abs(fl)),'frMaxAbs_deg',max(abs(fr)), ...
    'rlMaxAbs_deg',max(abs(rl)),'rrMaxAbs_deg',max(abs(rr)), ...
    'flConvertedMaxAbsDiff',max(abs(fl-deg)), ...
    'frConvertedMaxAbsDiff',max(abs(fr-deg)), ...
    'flFrMaxAbsDiff',max(abs(fl-fr)), ...
    'frequency_Hz',fitf(r.d1_steer_cmd_rad.time,cmd));
a.steering.frontCommandApplied=a.steering.flConvertedMaxAbsDiff<1e-12&& ...
    a.steering.frConvertedMaxAbsDiff<1e-12&&a.steering.flFrMaxAbsDiff<1e-12&& ...
    a.steering.flMaxAbs_deg>1e-8&&a.steering.frMaxAbs_deg>1e-8;
a.steering.rearZero=a.steering.rlMaxAbs_deg<1e-12&&a.steering.rrMaxAbs_deg<1e-12;
a.steering.pass=abs(a.steering.sourceMaxAbs_rad-.02)<1e-9&& ...
    abs(a.steering.convertedMaxAbs_deg-.02*180/pi)<1e-9&& ...
    a.steering.ratioMaxError<1e-10&&abs(a.steering.frequency_Hz-.4)<1e-5&& ...
    a.steering.frontCommandApplied&&a.steering.rearZero;

a.timing=struct('xSampleCount',r.dkekf_x_log1.sampleCount, ...
    'pSampleCount',r.dkekf_P_log1.sampleCount, ...
    'diagSampleCount',r.dkekf_diag_log1.sampleCount, ...
    'rawInputSampleCount',r.dkekf_u_log1.sampleCount, ...
    'tStart',t(1),'tEnd',t(end),'dtMin',min(dt),'dtMean',mean(dt), ...
    'dtMax',max(dt),'duplicateTimestampCount',nnz(dt<=0), ...
    'missingHitCount',sum(max(round(dt/.01)-1,0)), ...
    'outputLogsAligned',outputLogsAligned,'inputAlignment',inputAlignment);
a.timing.dkekf100Hz=all(abs(dt-.01)<1e-12)&& ...
    a.timing.duplicateTimestampCount==0&&a.timing.missingHitCount==0&& ...
    n==round((t(end)-t(1))/.01)+1&&abs(t(1))<1e-12&&abs(t(end)-16)<1e-12;

reset=u(:,6)>.5;doAy=u(:,5)>.5;applied=d(:,4)>.5;
a.reset=struct('highCount',nnz(reset),'timestamps',t(reset), ...
    'onceAtT0',nnz(reset)==1&&abs(t(reset))<1e-12, ...
    'initialStatePrior',[u(1,4);0;0],'initialCovariancePrior',diag([.1 .1 .1]), ...
    'runtimeFirstState',x(1,:).','runtimeFirstCovariance',p(:,:,1), ...
    'trueVyInitialization',false);
a.ayScheduler=struct('doAyUpdateCount',nnz(doAy), ...
    'ayUpdateAppliedCount',nnz(applied),'doAyUpdateTimestamps',t(doAy), ...
    'ayUpdateAppliedTimestamps',t(applied), ...
    'sequenceExact',isequal(doAy,applied));
a.ayScheduler.actual20Hz=a.ayScheduler.sequenceExact&&nnz(doAy)==321&& ...
    all(abs(diff(t(doAy))-.05)<1e-12)&&abs(t(find(doAy,1))-0)<1e-12&& ...
    abs(t(find(doAy,1,'last'))-16)<1e-12;

a.dimensions=struct('x',size(x,2),'P',size(p(:,:,1)),'diag',size(d,2));
a.numeric=struct('allXFinite',all(isfinite(x(:))),'allPFinite',all(isfinite(p(:))), ...
    'allDiagFinite',all(isfinite(d(:))));
a.numeric.dimensionsOK=a.dimensions.x==3&&isequal(a.dimensions.P,[3 3])&& ...
    a.dimensions.diag==7;
a.numeric.allFinite=a.numeric.allXFinite&&a.numeric.allPFinite&&a.numeric.allDiagFinite;
pd=zeros(n,3);minEig=inf;maxAsym=0;
for k=1:n
    pk=p(:,:,k);pd(k,:)=diag(pk).';
    maxAsym=max(maxAsym,max(abs(pk-pk.'),[],'all'));
    minEig=min(minEig,min(eig((pk+pk.')/2)));
end
a.covariance=struct('maxAsymmetry',maxAsym,'minimumEigenvalue',minEig, ...
    'P11',cov_stats(pd(:,1)),'P22',cov_stats(pd(:,2)),'P33',cov_stats(pd(:,3)));
a.covariance.valid=maxAsym<=1e-12&&minEig>=-1e-12;

[vxTrue,vxAlign]=truth_at(r.Vx_true_log,t,1);
[vyTrue,vyAlign]=truth_at(r.vy_true_log1,t,1);
[rDeg,rAlign]=truth_at(r.avz_log1,t,1);rTrue=rDeg*pi/180;
a.offlineTruth=struct('Vx',vxAlign,'Vy',vyAlign,'r',rAlign, ...
    'rSourceUnit','deg/s','rAnalysisUnit','rad/s','rConversion','pi/180', ...
    'noExtrapolation',true,'usedOnline',false);
evx=x(:,1)-vxTrue;evy=x(:,2)-vyTrue;er=x(:,3)-rTrue;
a.performance=struct('Vx',error_metrics(evx),'Vy',error_metrics(evy), ...
    'r',error_metrics(er),'VyHatRange',[min(x(:,2)) max(x(:,2))], ...
    'VyTrueRange',[min(vyTrue) max(vyTrue)]);

rMeas=u(:,3);rAbs=abs(rMeas);low=rAbs<=.01;higher=~low;
a.yaw=struct('meanAbs',mean(rAbs),'medianAbs',median(rAbs), ...
    'p95Abs',pct(rAbs,95),'maxAbs',max(rAbs), ...
    'lowCount',nnz(low),'lowFraction',mean(low), ...
    'higherCount',nnz(higher),'higherFraction',mean(higher), ...
    'threshold_radps',.01,'lifeSigGate',false);
a.vyPartitions=struct('lowR',partition_error(evy,low), ...
    'higherR',partition_error(evy,higher));

a.nis=struct('Vx',nis_stats(d(:,1)),'r',nis_stats(d(:,2)), ...
    'Ay',nis_stats(d(applied,3)));
a.nis.Ay.sampleCount=nnz(applied);
a.innovations=struct('Vx',innovation_stats(d(:,5)), ...
    'r',innovation_stats(d(:,6)), ...
    'Ay',innovation_stats(d(applied,7)));
a.innovations.Ay.sampleCount=nnz(applied);

[rx,rp,rd]=replay(u);
a.exactReplay=struct('maxAbsXDiff',max(abs(rx(:)-x(:))), ...
    'maxAbsPDiff',max(abs(rp(:)-p(:))), ...
    'maxAbsDiagDiff',max(abs(rd(:)-d(:))));
a.exactReplay.pass=all([a.exactReplay.maxAbsXDiff a.exactReplay.maxAbsPDiff ...
    a.exactReplay.maxAbsDiagDiff]<=1e-12);
a.oneHitSemantics=struct('pass',a.timing.dkekf100Hz&&a.exactReplay.pass&& ...
    inputAlignment.allHitsResolved&&~inputAlignment.timestampShiftApplied, ...
    'statement','ONE 100-HZ FUNCTION-CALL HIT = ONE COMMITTED DK-EKF STATE ADVANCE');

c2=load(c2File,'report');a.fairness=c2.report.static.fairness;
a.fairness.pass=~a.fairness.trueVyOnline&&a.fairness.trueVxMeasurementOnly&& ...
    a.fairness.axPredictionInput&&a.fairness.avzMeasurementOnly&& ...
    a.fairness.ayMeasurementOnly&&a.fairness.sharedStateAndP&& ...
    ~a.fairness.outputFusion&&~a.fairness.lifeSig&&~a.fairness.adaptiveFusion;
a.hashIntegrity=struct('validationModelUnchanged',report.validationModelHashUnchanged, ...
    'acceptedTargetUnchanged',report.acceptedTargetHashUnchanged, ...
    'allFrozenUnchanged',report.allFrozenHashesUnchanged, ...
    'validationModelHash',report.validationModelHashAfter, ...
    'acceptedTargetHash',report.acceptedTargetHashAfter);

a.gates=struct('runtimeValidity',report.simulationCompleted&&report.simCalled&& ...
    report.carSimRun&&~report.carSim.historicalGDriveRequestPresent&&a.steering.pass&& ...
    a.timing.dkekf100Hz&&a.reset.onceAtT0&&a.ayScheduler.actual20Hz, ...
    'numericalValidity',a.numeric.dimensionsOK&&a.numeric.allFinite&&a.covariance.valid, ...
    'truthMetricsValid',all([isfinite(struct2array(a.performance.Vx)) ...
    isfinite(struct2array(a.performance.Vy)) isfinite(struct2array(a.performance.r))]), ...
    'nisValid',all(isfinite([d(:,1);d(:,2);d(applied,3)])), ...
    'replayValidity',a.exactReplay.pass&&a.oneHitSemantics.pass, ...
    'fairnessValidity',a.fairness.pass,'hashIntegrity', ...
    report.validationModelHashUnchanged&&report.acceptedTargetHashUnchanged&& ...
    report.allFrozenHashesUnchanged);
a.pass=all(struct2array(a.gates));
if a.pass,a.kkfReference=kkf_comparison(g1File,a.performance.Vy,a.steering,report.nominal);else,a.kkfReference=struct('performed',false,'reason','D2 gates invalid');end
report.analysis=a;save(f,'report','-v7.3');
fprintf(['V2_2D2_ANALYSIS|pass=%d|steer=[%.15g %.15g %.15g]|front=[%.15g %.15g]|rear=[%.3g %.3g]|' ...
    'samples=%d|t=[%.15g %.15g]|dt=[%.15g %.15g %.15g]|reset=%d|Ay=%d/%d|' ...
    'P=[%.3g %.15g]|replay=[%.3g %.3g %.3g]|Vx=[%.15g %.15g %.15g %.15g %.15g]|' ...
    'Vy=[%.15g %.15g %.15g %.15g %.15g]|r=[%.15g %.15g %.15g %.15g %.15g]\n'], ...
    a.pass,a.steering.sourceMaxAbs_rad,a.steering.convertedMaxAbs_deg, ...
    a.steering.ratioMedian,a.steering.flMaxAbs_deg,a.steering.frMaxAbs_deg, ...
    a.steering.rlMaxAbs_deg,a.steering.rrMaxAbs_deg,n,t(1),t(end),min(dt),mean(dt),max(dt), ...
    a.reset.highCount,a.ayScheduler.doAyUpdateCount,a.ayScheduler.ayUpdateAppliedCount, ...
    a.covariance.maxAsymmetry,a.covariance.minimumEigenvalue, ...
    a.exactReplay.maxAbsXDiff,a.exactReplay.maxAbsPDiff,a.exactReplay.maxAbsDiagDiff, ...
    metrics_vec(a.performance.Vx),metrics_vec(a.performance.Vy),metrics_vec(a.performance.r));
fprintf('NIS|Vx=[%.15g %.15g %.15g %.15g %.15g]|r=[%.15g %.15g %.15g %.15g %.15g]|AyN=%d|Ay=[%.15g %.15g %.15g %.15g %.15g]\n', ...
    nis_vec(a.nis.Vx),nis_vec(a.nis.r),a.nis.Ay.sampleCount,nis_vec(a.nis.Ay));
fprintf('PDIAG|P11=[%.15g %.15g %.15g %.15g %.15g]|P22=[%.15g %.15g %.15g %.15g %.15g]|P33=[%.15g %.15g %.15g %.15g %.15g]\n', ...
    cov_vec(a.covariance.P11),cov_vec(a.covariance.P22),cov_vec(a.covariance.P33));
fprintf('YAW|mean=%.15g|median=%.15g|p95=%.15g|max=%.15g|low=%d/%.15g|higher=%d/%.15g\n', ...
    a.yaw.meanAbs,a.yaw.medianAbs,a.yaw.p95Abs,a.yaw.maxAbs, ...
    a.yaw.lowCount,a.yaw.lowFraction,a.yaw.higherCount,a.yaw.higherFraction);
end

function y=v(r),y=double(r.data(:));end
function a=sample_rows(data,n,w)
a=double(data);s=size(a);
if ismatrix(a)
    if isequal(s,[n w]),return;end
    if isequal(s,[w n]),a=a.';return;end
end
if numel(a)==n*w,a=reshape(a,w,n).';return;end
error('VY_DKEKF:LogShape','Cannot resolve %d-wide log with size %s.',w,mat2str(s));
end
function [hits,audit]=input_rows_at_hits(data,inputTime,hitTime,w)
inputTime=double(inputTime(:));a=sample_rows(data,numel(inputTime),w);
hits=zeros(numel(hitTime),w);matchCount=zeros(numel(hitTime),1);nearCount=zeros(numel(hitTime),1);
nearestDelta=zeros(numel(hitTime),1);tolerance=zeros(numel(hitTime),1);ambiguous=false;
for k=1:numel(hitTime)
    tol=32*eps(max(1,abs(hitTime(k))));tolerance(k)=tol;delta=abs(inputTime-hitTime(k));
    nearestDelta(k)=min(delta);ix=find(delta==nearestDelta(k));
    matchCount(k)=numel(ix);nearCount(k)=nnz(delta<=tol);
    if nearestDelta(k)>tol,continue;end
    c=a(ix,:);if size(c,1)>1&&any(max(abs(c-c(end,:)),[],2)>1e-12),ambiguous=true;end
    hits(k,:)=c(end,:);
end
audit=struct('rawInputSampleCount',numel(inputTime),'hitSampleCount',numel(hitTime), ...
    'matchCountPerHit',matchCount,'nearCoincidentCountPerHit',nearCount, ...
    'nearestTimeDelta',nearestDelta,'timeTolerance',tolerance, ...
    'exactTimestampHitCount',nnz(nearestDelta==0), ...
    'roundoffResolvedHitCount',nnz(nearestDelta>0&nearestDelta<=tolerance), ...
    'maxNearestTimeDelta',max(nearestDelta), ...
    'allHitsResolved',all(matchCount>=1)&&all(nearestDelta<=tolerance), ...
    'duplicateMatchCount',nnz(matchCount>1),'ambiguousDuplicate',ambiguous, ...
    'timestampShiftApplied',false,'machineRoundoffToleranceOnly',all(nearestDelta<=tolerance));
end
function p=covariance_pages(data,n)
p=double(data);s=size(p);
if ndims(p)==3&&isequal(s,[3 3 n]),return;end
if ndims(p)==3&&isequal(s,[n 3 3]),p=permute(p,[2 3 1]);return;end
if ismatrix(p)&&isequal(s,[n 9]),p=reshape(p.',3,3,n);return;end
if numel(p)==9*n,p=reshape(p,3,3,n);return;end
error('VY_DKEKF:LogShape','Cannot resolve covariance log size %s.',mat2str(s));
end
function [y,a]=truth_at(rec,t,w)
tr=double(rec.time(:));yr=sample_rows(rec.data,numel(tr),w);[tr,ia]=unique(tr,'stable');yr=yr(ia,:);
tol=64*eps(max(1,max(abs(t))));assert(t(1)>=tr(1)-tol&&t(end)<=tr(end)+tol, ...
    'Truth coverage does not contain every estimator timestamp; extrapolation forbidden.');
[tf,loc]=ismember(t,tr);
if all(tf),y=yr(loc,:);method='exact timestamp match';maxDelta=0;
else,y=interp1(tr,yr,t,'linear');assert(all(isfinite(y(:))),'Truth interpolation failed.');method='linear interpolation, no extrapolation';maxDelta=max(arrayfun(@(q)min(abs(tr-q)),t));end
a=struct('sourceSampleCount',numel(tr),'targetSampleCount',numel(t), ...
    'sourceStart',tr(1),'sourceEnd',tr(end),'method',method,'maxNearestTimeDelta',maxDelta);
end
function s=error_metrics(e)
s=struct('RMSE',sqrt(mean(e.^2)),'MAE',mean(abs(e)),'Bias',mean(e), ...
    'MaxAbsError',max(abs(e)),'FinalError',e(end));
end
function s=partition_error(e,m)
assert(any(m),'Empty diagnostic partition.');s=error_metrics(e(m));s.sampleCount=nnz(m);
end
function s=nis_stats(z)
assert(~isempty(z)&&all(isfinite(z)));s=struct('mean',mean(z),'median',median(z), ...
    'p95',pct(z,95),'max',max(z),'fractionLE_3_8414588',mean(z<=3.8414588));
end
function s=innovation_stats(z)
assert(~isempty(z)&&all(isfinite(z)));s=struct('mean',mean(z), ...
    'RMS',sqrt(mean(z.^2)),'maxAbs',max(abs(z)));
end
function s=cov_stats(z)
s=struct('initial',z(1),'final',z(end),'min',min(z),'max',max(z),'mean',mean(z));
end
function q=pct(z,p)
z=sort(z(:));x=1+(numel(z)-1)*p/100;i=floor(x);j=ceil(x);
if i==j,q=z(i);else,q=z(i)+(x-i)*(z(j)-z(i));end
end
function f=fitf(t,y),f=fminbnd(@(q)fiterr(q,t,y),.1,1);end
function e=fiterr(f,t,y),A=[sin(2*pi*f*t(:)) cos(2*pi*f*t(:))];e=norm(A*(A\y(:))-y(:))^2;end
function [xr,pr,dr]=replay(u)
n=size(u,1);xr=zeros(n,3);pr=zeros(3,3,n);dr=zeros(n,7);
par=struct('m',1860,'Iz',2687.1,'a',1.18,'b',1.77,'track',1.575,'Rw',.393, ...
    'k_f',.78181,'k_r',1.09186);
cfg=struct('Q_DK',diag([1e-4 1e-4 1e-4]),'R_Vx',1e-4, ...
    'R_r',3.365172961808e-4,'R_Ay',1e-2,'jacobianStep',1e-6, ...
    'denomEps',1e-12,'lambda',zeros(4,1));
P0=diag([.1 .1 .1]);init=false;xs=zeros(3,1);ps=P0;
for k=1:n
    if ~init||u(k,6)>.5,x0=[u(k,4);0;0];p0=P0;else,x0=xs;p0=ps;end
    [xn,pn,info]=vy_dkekf_baseline_step(x0,p0,u(k,1),u(k,7:10).', ...
        u(k,4),u(k,3),u(k,2),u(k,5),.01,par,cfg);
    na=info.Ay.NIS;if ~info.Ay.updateApplied&&isnan(na),na=0;end
    xr(k,:)=xn.';pr(:,:,k)=pn;
    dr(k,:)=[info.Vx.NIS info.r.NIS na double(info.Ay.updateApplied) ...
        info.Vx.innovation info.r.innovation info.Ay.innovation];
    xs=xn;ps=pn;init=true;
end
end
function c=kkf_comparison(f,dk,steer,nominal)
S=load(f,'report');k=S.report;assert(isfield(k,'analysis'),'G1-A analyzed evidence missing.');
km=k.analysis.performance.Vy;cond=k.condition;
c=struct('performed',true,'sourceFile',f,'kkf',km,'dkekf',dk, ...
    'differenceDKminusK',struct('RMSE',dk.RMSE-km.RMSE,'MAE',dk.MAE-km.MAE, ...
    'Bias',dk.Bias-km.Bias,'MaxAbsError',dk.MaxAbsError-km.MaxAbsError, ...
    'FinalError',dk.FinalError-km.FinalError));
c.sameCommandedCondition=cond.Vx_mps==nominal.Vx_mps&& ...
    cond.steerAmplitude_rad==nominal.steerAmplitude_rad&& ...
    cond.steerFrequency_Hz==nominal.steerFrequency_Hz&&k.stopTime_s==16;
c.genuineSteeringBoth=k.steeringGate.pass&&steer.pass;
c.applesToApples=c.sameCommandedCondition&&c.genuineSteeringBoth;
end
function x=metrics_vec(s),x=[s.RMSE s.MAE s.Bias s.MaxAbsError s.FinalError];end
function x=nis_vec(s),x=[s.mean s.median s.p95 s.max s.fractionLE_3_8414588];end
function x=cov_vec(s),x=[s.initial s.final s.min s.max s.mean];end
