function report=run_vy_dkekf_v2_2d1_steer_smoke()
%RUN_VY_DKEKF_V2_2D1_STEER_SMOKE The one authorized D1 2-second run.
root=fileparts(fileparts(mfilename('fullpath')));md=fullfile(root,'model');src=fullfile(md,'vx_vy_dkekf_v2_2.slx');dst=fullfile(md,'vx_vy_dkekf_v2_2d_nominal.slx');simFile=fullfile(md,'simfile.sim');outFile=fullfile(root,'results','vy_dkekf_v2_2d1_steer_smoke.mat');
report=struct('stage','V2.2-D1 nominal steering 2 s smoke','stopTime_s',2,'nominal',struct('Vx_mps',20,'steerAmplitude_rad',0.02,'steerFrequency_Hz',0.4),'simulationCompleted',false,'simCalled',false,'carSimRun',false,'runtimeError',struct('identifier','','message','','report',''),'raw',struct());
[frozenFiles,expectedHashes]=frozen_manifest(root);
report.frozenBefore=hash_files(frozenFiles);assert_expected(report.frozenBefore,expectedHashes);
report.frozenHashBefore=sha(src);report.validationModelHashBefore=sha(dst);assert(strcmp(report.validationModelHashBefore,'a17e7609d2248c832a80f773660941b68025e3a38cfc1f3938cbca2bd0165e5b'),'D1 validation model hash mismatch before runtime.');old=pwd;op=path;model='vx_vy_dkekf_v2_2d_nominal';clean=onCleanup(@()cleanup(model,old,op));console='';
try
 logVariables={'d1_steer_cmd_rad','d1_steer_to_carsim_deg','d1_steer_fl_boundary_deg','d1_steer_fr_boundary_deg','d1_steer_rl_boundary_deg','d1_steer_rr_boundary_deg','d1_avz_imu','d1_reset','dkekf_u_log1','dkekf_x_log1','dkekf_P_log1','dkekf_diag_log1'};report.build=struct('mode','existing-validation-model-no-builder','targetFile',dst,'targetHash',report.validationModelHashBefore,'logVariables',{logVariables});solverDir='D:\carsim\CarSim2021.0_Prog\Programs\solvers';solverSfDir=fullfile(solverDir,'Matlab84+');solverDll=fullfile(solverDir,'carsim_64.dll');solverLibrary=fullfile(solverSfDir,'Solver_SF.slx');assert(isfile(simFile)&&isfile(solverDll)&&isfile(solverLibrary),'Required CarSim runtime file is missing.');simText=fileread(simFile);report.carSim=struct('progDir',macro_value(simText,'PROGDIR'),'dataDir',macro_value(simText,'DATADIR'),'solverPath',solverDll,'actualSolverPath','','historicalGDriveRequestPresent',contains(lower(simText),'g:\carsim'));assert(strcmpi(report.carSim.progDir,'D:\carsim\CarSim2021.0_Prog\')&&strcmpi(report.carSim.dataDir,'D:\carsim\CarSim2021.0_Data\')&&~report.carSim.historicalGDriveRequestPresent,'CarSim runtime configuration is not the accepted D: environment.');addpath(md);addpath(solverDir);addpath(solverSfDir);cd(md);load_system('Solver_SF');load_system(dst);report.static=static_log_preflight(model,logVariables);assert(report.static.loggingOK,'Required D1 steering/DK-EKF logging is missing.');w=get_param(model,'ModelWorkspace');assignin(w,'test_speed',20);assignin(w,'test_steer_amplitude',0.02);assignin(w,'test_steer_frequency',0.4);assignin('base','test_speed',20);assignin('base','test_steer_amplitude',0.02);assignin('base','test_steer_frequency',0.4);
 report.simCalled=true;console=evalc("out=sim(model,'StopTime','2','ReturnWorkspaceOutputs','on','FastRestart','off');");fprintf('%s',console);report.carSim.actualSolverPath=solver_path_from_console(console);report.carSimRun=contains(console,'Termination at simulation time')&&strcmpi(report.carSim.actualSolverPath,solverDll);assert(report.carSimRun,'Authorized CarSim completion evidence missing.');for k=1:numel(report.build.logVariables),n=report.build.logVariables{k};report.raw.(n)=rec(out.get(n));end;report.simulationCompleted=true;
catch ME,report.runtimeError.identifier=ME.identifier;report.runtimeError.message=ME.message;report.runtimeError.report=getReport(ME,'extended','hyperlinks','off');end
report.consoleText=console;report.frozenHashAfter=sha(src);report.frozenHashUnchanged=strcmp(report.frozenHashBefore,report.frozenHashAfter);report.frozenAfter=hash_files(frozenFiles);report.allFrozenHashesUnchanged=hashes_match(report.frozenAfter,expectedHashes);if isfile(dst),report.newModelHash=sha(dst);else,report.newModelHash='';end;report.validationModelHashAfter=report.newModelHash;report.validationModelHashUnchanged=strcmp(report.validationModelHashBefore,report.validationModelHashAfter);cleanup(model,old,op);clear clean;save(outFile,'report','-v7.3');if ~report.simulationCompleted,error('VY_DKEKF:D1RuntimeFailed','D1 run failed; evidence saved to %s',outFile);end;assert(report.frozenHashUnchanged&&report.allFrozenHashesUnchanged&&report.validationModelHashUnchanged,'A frozen/validation model file changed.');end
function r=rec(t),assert(isa(t,'timeseries'),'Expected timeseries.');r=struct('time',double(t.Time(:)),'data',double(t.Data),'sampleCount',numel(t.Time),'dataSize',size(t.Data));end
function h=sha(f),d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(f));ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());while ds.read()~=-1,end;b=typecast(d.digest(),'uint8');h=lower(reshape(dec2hex(b,2).',1,[]));clear c,end
function cleanup(m,old,op),if bdIsLoaded(m),close_system(m,0);end;if bdIsLoaded('Solver_SF'),close_system('Solver_SF',0);end;cd(old);path(op);evalin('base','clear test_speed test_steer_amplitude test_steer_frequency');end
function [files,hashes]=frozen_manifest(root)
files={fullfile(root,'model','vx_vy_dkekf_v2_2.slx');fullfile(root,'model','vy_dkekf_baseline_simulink_sfun.m');fullfile(root,'model','vy_dkekf_baseline_step.m');fullfile(root,'model','vy_dkekf_baseline.m');fullfile(root,'model','vx_vy_dekf_v1_17.slx');fullfile(root,'model','vy_kinematic_kf_step.m');fullfile(root,'model','vy_kinematic_kf.m');fullfile(root,'model','vx_vy_kkf_v2_1.slx');fullfile(root,'model','vx_vy_kkf_v2_1g_steer.slx')};
hashes={'e768fb2ad33a6eeaabde2fb7c40be660b78f350a90c752327dc9b423f50f2e15';'12f0d82643d65aa5098ed20c0655234f3a2e7ef6d6f5e7dee5b80bc1a201bda1';'6475b9dbc93eb6e25c2bb9fad81ca11b2e08c26e7f2ae6a33c50e35b2790b457';'7e731d7df0bb2ca4455e3aa16e7513114e04472d38c62f1f453b631056306973';'108f819dcd1b71fd6d795d7148cbf32fe1a888ae9878908e894a07626ed003ae';'3786646ee5163d231dd8964614a8875217dfa496eb593b455e4e029e26da2244';'f242cb75ba08d22cb1eed87731746cf80d54fd39c1899b45e9980a40576414d4';'b67a98a6080374304e2d3424f85589c913e6ec4db25bc9912cbfd2bc441c2712';'59b25c5e350140ab0eafd8345d5a9145d6981b96481023537a3bd01a787f728e'};
end
function records=hash_files(files),records=repmat(struct('path','','sha256',''),numel(files),1);for k=1:numel(files),records(k)=struct('path',files{k},'sha256',sha(files{k}));end,end
function assert_expected(records,expected),assert(hashes_match(records,expected),'Frozen hash mismatch before D1 runtime.');end
function ok=hashes_match(records,expected),ok=numel(records)==numel(expected);for k=1:numel(records),ok=ok&&strcmp(records(k).sha256,expected{k});end,end
function audit=static_log_preflight(m,names),audit=struct('logVariables',{names},'logPaths',{{}},'loggingOK',true);audit.logPaths=cell(size(names));for k=1:numel(names),b=find_system(m,'SearchDepth',1,'BlockType','ToWorkspace','VariableName',names{k});audit.logPaths{k}=b;audit.loggingOK=audit.loggingOK&&numel(b)==1;end,end
function value=macro_value(text,key),token=regexp(text,['(?m)^' key '\s+([^\r\n]+)'],'tokens','once');assert(~isempty(token),'CarSim config entry missing: %s',key);value=strtrim(token{1});end
function pathText=solver_path_from_console(text),token=regexp(text,'Use vehicle solver:\s*([^\r\n]+)','tokens','once');if isempty(token),pathText='';else,pathText=strtrim(token{1});end,end
