function report = run_vy_fixed_fusion_v2_5g1b_recovery_diagnostic()
%RUN_VY_FIXED_FUSION_V2_5G1B_RECOVERY_DIAGNOSTIC One 0.20-s control runtime.
% This is infrastructure-only evidence. It is not calibration or holdout data.

root=fileparts(fileparts(mfilename('fullpath')));
md=fullfile(root,'model');
target=fullfile(md,'vx_vy_fixed_fusion_v2_5.slx');
simFile=fullfile(md,'simfile.sim');
resultFile=fullfile(root,'results','vy_fixed_fusion_v2_5g1b_recovery_diagnostic.mat');
model='vx_vy_fixed_fusion_v2_5';
targetExpected='801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE';
assert(~isfile(resultFile),'V25G1B:NoRetry', ...
    'Diagnostic result already exists; a second runtime is prohibited.');

report=struct();
report.stage='V2.5-G1B controlled CarSim runtime recovery diagnostic';
report.role='RUNTIME_RECOVERY_DIAGNOSTIC';
report.calibrationEligible=false; report.holdoutEligible=false;
report.controlReference='V2.5-D known-good 0.20-s configuration';
report.stopTimeRequested_s=0.20;
report.commandedSteerAmplitude_rad=0.02;
report.commandedSteerFrequency_Hz=0.40;
report.speedScope='EXISTING_VERIFIED_APPROX_20_MPS_CLASS';
expectedFreshPrefdir='C:\Users\21180\AppData\Roaming\MathWorks\MATLAB\R2024a';
r2CleanPrefdir='D:\SystemMigration\Temp\V25G1B_R2_CLEAN_PREFDIR';
forensicBackupPrefdir=['C:\Users\21180\AppData\Roaming\MathWorks\MATLAB\' ...
    'R2024a_V25G1B_BAD_BACKUP_20260828T150506Z'];
activePrefdir=prefdir;
prefdirEnvironment=getenv('MATLAB_PREFDIR');
report.matlabPrefdir=struct('environmentValue',prefdirEnvironment, ...
    'activeValue',activePrefdir,'expectedFreshValue',expectedFreshPrefdir, ...
    'environmentUnset',isempty(prefdirEnvironment), ...
    'activeExact',strcmpi(activePrefdir,expectedFreshPrefdir), ...
    'notR2Clean',~strcmpi(activePrefdir,r2CleanPrefdir), ...
    'notForensicBackup',~strcmpi(activePrefdir,forensicBackupPrefdir), ...
    'policy','UNSET / inherited R4-regenerated default PREFDIR');
report.matlabStartup=struct('version',version,'startupGateReached',true);
assert(report.matlabPrefdir.environmentUnset&&report.matlabPrefdir.activeExact&& ...
    report.matlabPrefdir.notR2Clean&&report.matlabPrefdir.notForensicBackup, ...
    'V25G1B:Prefdir','Active MATLAB PREFDIR does not match R4 fresh default policy.');
report.simCalled=false; report.runtimeAuthorizationConsumed=false;
report.simulationCompleted=false; report.carSimRun=false;
report.runtimeError=struct('identifier','','message','','report','');
report.raw=struct(); report.consoleText='';

[frozenFiles,expectedHashes]=frozen_manifest(root);
report.frozenBefore=hash_files(frozenFiles);
assert(hashes_match(report.frozenBefore,expectedHashes),'V25G1B:Frozen', ...
    'Frozen hash mismatch before diagnostic runtime.');
report.targetHashBefore=sha256(target);
assert(strcmpi(report.targetHashBefore,targetExpected),'V25G1B:Frozen', ...
    'Fixed-fusion target hash mismatch before diagnostic runtime.');

referenceMat=fullfile(root,'results','vy_fixed_fusion_v2_5d_preflight.mat');
assert(isfile(referenceMat),'V25G1B:Reference','V2.5-D reference MAT is missing.');
report.referenceMat=struct('path',referenceMat,'sha256',sha256(referenceMat));
assert(strcmpi(report.referenceMat.sha256, ...
    '63F233D9B0B444EDCA7C332F522AF9A588EB3A9C6F0E5FD9718CA5BEA09184F8'), ...
    'V25G1B:Reference','V2.5-D reference MAT hash differs from forensic record.');

oldPwd=pwd;oldPath=path;
cleanupObj=onCleanup(@()cleanup(model,oldPwd,oldPath));
console='';
try
    solverDir='D:\carsim\CarSim2021.0_Prog\Programs\solvers';
    solverSfDir=fullfile(solverDir,'Matlab84+');
    solverDll=fullfile(solverDir,'carsim_64.dll');
    solverMex=fullfile(solverSfDir,'vs_sf.mexw64');
    solverLibrary=fullfile(solverSfDir,'Solver_SF.slx');
    assert(isfile(simFile)&&isfile(solverDll)&&isfile(solverMex)&&isfile(solverLibrary), ...
        'V25G1B:CarSim','Required D: CarSim runtime file is missing.');
    simText=fileread(simFile);
    report.carSim=struct('pwd','','activeSimfile',simFile, ...
        'simfileHash',sha256(simFile),'progDir',macro_value(simText,'PROGDIR'), ...
        'dataDir',macro_value(simText,'DATADIR'),'solverExpected',solverDll, ...
        'solverActual','','mexExpected',solverMex,'mexActual','', ...
        'gRequestBefore',contains(lower(simText),'g:\carsim'),'gRequestConsole',false);
    assert(strcmpi(report.carSim.simfileHash, ...
        'A50912CE50F59B216A4CF939228E63A0F27B9818C52A2ABE493345C53FA7A2EA')&& ...
        strcmpi(report.carSim.progDir,'D:\carsim\CarSim2021.0_Prog\')&& ...
        strcmpi(report.carSim.dataDir,'D:\carsim\CarSim2021.0_Data\')&& ...
        ~report.carSim.gRequestBefore,'V25G1B:CarSim', ...
        'Model simfile is not the accepted D: configuration.');

    addpath(md);addpath(solverDir);addpath(solverSfDir);
    report.cache=struct();
    report.cache.before=Simulink.fileGenControl('getConfig');
    report.cache.referenceCacheFolder=fullfile(tempdir,'vy_fixed_fusion_v2_5d_cache');
    report.cache.referenceCodeGenFolder=fullfile(tempdir,'vy_fixed_fusion_v2_5d_codegen');
    report.cache.referenceCacheExisted=isfolder(report.cache.referenceCacheFolder);
    report.cache.referenceCodeGenExisted=isfolder(report.cache.referenceCodeGenFolder);
    Simulink.fileGenControl('set','CacheFolder',report.cache.referenceCacheFolder, ...
        'CodeGenFolder',report.cache.referenceCodeGenFolder,'createDir',true);
    report.cache.active=Simulink.fileGenControl('getConfig');

    cd(md);
    report.carSim.pwd=pwd;
    report.carSim.activeSimfile=fullfile(pwd,'simfile.sim');
    report.carSim.mexActual=which('vs_sf');
    assert(strcmpi(report.carSim.pwd,md)&& ...
        strcmpi(report.carSim.activeSimfile,simFile)&& ...
        strcmpi(report.carSim.mexActual,solverMex),'V25G1B:Environment', ...
        'Immediate pre-load cwd/simfile/MEX gate failed.');

    load_system('Solver_SF');load_system(target);
    report.static=static_preflight(model);
    assert(report.static.pass,'V25G1B:Static', ...
        'Known-good V2.5-D target preflight failed before sim().');
    report.weights=report.static.weights;report.fParameters=report.static.fParameters;

    w=get_param(model,'ModelWorkspace');
    assignin(w,'test_speed',20);assignin(w,'test_steer_amplitude',0.02);
    assignin(w,'test_steer_frequency',0.4);assignin(w,'vy_v17_mode_code',20);
    assignin('base','test_speed',20);assignin('base','test_steer_amplitude',0.02);
    assignin('base','test_steer_frequency',0.4);assignin('base','vy_v17_mode_code',20);
    clear vy_dynamic_ekf_v1_17 vy_kinematic_kf

    logVariables={'steer_cmd_rad','steer_to_carsim_deg', ...
        'steer_fl_carsim_deg','steer_fr_carsim_deg','steer_rl_carsim_deg', ...
        'steer_rr_carsim_deg','reset_g0','avz_imu_g0','kkf_u_log1', ...
        'kkf_x_log1','kkf_P_log1','kkf_diag_log1','dekf_x_log', ...
        'dekf_P_log','dekf_diag_log','parallel_input_log','fusion_vy_d_log', ...
        'fusion_vy_k_log','fusion_vy_f_log','fusion_f_P_log', ...
        'fusion_f_diag_log','fusion_vy_fw_log'};
    assert(all(cellfun(@(n)numel(find_system(model,'SearchDepth',1, ...
        'BlockType','ToWorkspace','VariableName',n))==1,logVariables)), ...
        'V25G1B:Logging','A required V2.5-D control log boundary is missing.');

    % Hard gate immediately adjacent to the sole sim() call.
    report.immediatePreSim=struct('pwd',pwd,'activeSimfile',fullfile(pwd,'simfile.sim'), ...
        'simfileHash',sha256(fullfile(pwd,'simfile.sim')),'progDir',report.carSim.progDir, ...
        'dataDir',report.carSim.dataDir,'solverExpected',solverDll, ...
        'mexActual',which('vs_sf'),'matlabPrefdirEnvironment',getenv('MATLAB_PREFDIR'), ...
        'activePrefdir',prefdir,'expectedFreshPrefdir',expectedFreshPrefdir, ...
        'stopTime','0.20','amplitude',0.02,'frequency',0.40);
    assert(strcmpi(report.immediatePreSim.pwd,md)&& ...
        strcmpi(report.immediatePreSim.activeSimfile,simFile)&& ...
        strcmpi(report.immediatePreSim.simfileHash,report.carSim.simfileHash)&& ...
        strcmpi(report.immediatePreSim.mexActual,solverMex)&& ...
        isempty(report.immediatePreSim.matlabPrefdirEnvironment)&& ...
        strcmpi(report.immediatePreSim.activePrefdir,expectedFreshPrefdir), ...
        'V25G1B:ImmediatePreSim', ...
        'Immediate pre-sim environment differs from the known-good policy.');
    fprintf(['V25G1B_PRE_SIM|role=%s|pwd=%s|simfile=%s|simfileHash=%s|' ...
        'PROGDIR=%s|DATADIR=%s|solver=%s|mex=%s|prefdirEnv=%s|activePrefdir=%s|' ...
        'StopTime=0.20|A=0.02|f=0.40\n'],report.role, ...
        report.immediatePreSim.pwd,report.immediatePreSim.activeSimfile, ...
        report.immediatePreSim.simfileHash,report.immediatePreSim.progDir, ...
        report.immediatePreSim.dataDir,solverDll,report.immediatePreSim.mexActual, ...
        prefdir_label(report.immediatePreSim.matlabPrefdirEnvironment), ...
        report.immediatePreSim.activePrefdir);

    report.simCalled=true;report.runtimeAuthorizationConsumed=true;
    console=evalc("out=sim(model,'StopTime','0.20',"+ ...
        "'ReturnWorkspaceOutputs','on','FastRestart','off');");
    fprintf('%s',console);report.consoleText=console;
    report.carSim.solverActual=solver_path_from_console(console);
    report.carSim.gRequestConsole=contains(lower(console),'g:\carsim');
    report.carSimRun=contains(console,'Termination at simulation time')&& ...
        strcmpi(report.carSim.solverActual,solverDll)&&~report.carSim.gRequestConsole;
    assert(report.carSimRun,'V25G1B:CarSim','CarSim completion evidence is missing.');
    for k=1:numel(logVariables)
        name=logVariables{k};report.raw.(name)=record_timeseries(out.get(name));
    end
    report.stopTimeActual_s=max([report.raw.fusion_vy_d_log.time(end), ...
        report.raw.fusion_vy_k_log.time(end),report.raw.fusion_vy_f_log.time(end), ...
        report.raw.fusion_vy_fw_log.time(end)]);
    report.simulationCompleted=true;
catch ME
    report.consoleText=console;
    report.runtimeError.identifier=ME.identifier;
    report.runtimeError.message=ME.message;
    report.runtimeError.report=getReport(ME,'extended','hyperlinks','off');
end

cleanup(model,oldPwd,oldPath);clear cleanupObj
report.targetHashAfter=sha256(target);
report.targetHashUnchanged=strcmpi(report.targetHashBefore,report.targetHashAfter);
report.frozenAfter=hash_files(frozenFiles);
report.allFrozenHashesUnchanged=hashes_match(report.frozenAfter,expectedHashes);
save(resultFile,'report','-v7.3');
if ~report.simulationCompleted
    error('V25G1B:RuntimeFailed','G1B diagnostic failed; evidence saved to %s',resultFile);
end
assert(report.targetHashUnchanged&&report.allFrozenHashesUnchanged, ...
    'V25G1B:Integrity','A frozen file changed during the diagnostic.');
fprintf(['V25G1B_RUNTIME_OK|role=%s|simCalled=%d|completed=%d|carSim=%d|' ...
    'stop=%.17g|solver=%s|gRequest=%d|targetUnchanged=%d\n'], ...
    report.role,report.simCalled,report.simulationCompleted,report.carSimRun, ...
    report.stopTimeActual_s,report.carSim.solverActual, ...
    report.carSim.gRequestBefore||report.carSim.gRequestConsole,report.targetHashUnchanged);
end

function audit=static_preflight(m)
fusion=[m '/Fixed Weight D K F Fusion'];fSub=[m '/F-Track 100Hz'];
fp=get_param(fusion,'PortHandles');fsp=get_param(fSub,'PortHandles');
params=parse_expr_list(get_param(fusion,'Parameters'));
fParams=parse_expr_list(get_param([fSub '/F-Track Stateful Boundary'],'Parameters'));
audit=struct();audit.weights=struct('values',params,'alpha_D',params(1), ...
    'alpha_K',params(2),'alpha_F',params(3),'classification','TEST-ONLY / UNSELECTED');
audit.fParameters=struct('Ts',fParams(1),'Vy_F0',fParams(2),'P0_F',fParams(3),'Q_F',fParams(4));
audit.fusionSources=arrayfun(@source_of_port,fp.Inport,'UniformOutput',false);
audit.fusionSourcesExact=isequal(audit.fusionSources(:), ...
    {[m '/Fusion D State Select Vy'];[m '/Fusion K State Select Vy'];fSub});
audit.fValidSource=source_of_port(fsp.Inport(6));
audit.fValidZero=strcmp(audit.fValidSource,[m '/F Feedback Valid Disabled'])&& ...
    str2double(get_param(audit.fValidSource,'Value'))==0;
audit.schedulers={source_of_trigger([m '/Parallel D-EKF 100Hz']), ...
    source_of_trigger([m '/K-KF 100Hz']),source_of_trigger(fSub)};
audit.schedulersIndependent=numel(unique(audit.schedulers))==3;
audit.schedulers100Hz=all(cellfun(@scheduler100,audit.schedulers));
cmd=[m '/G0 Steer Cmd Rad'];gain=[m '/Gain22'];sw=[m '/Manual Switch1'];
audit.steering=struct('amplitude',get_param(cmd,'Amplitude'), ...
    'frequency',get_param(cmd,'Frequency'),'gain',get_param(gain,'Gain'), ...
    'manualSwitchSetting',get_param(sw,'CurrentSetting'));
audit.pass=isequal(params,[1/3 1/3 1/3])&&fParams(1)==0.01&& ...
    fParams(3)==0.5&&fParams(4)==0.0025&&audit.fusionSourcesExact&& ...
    audit.fValidZero&&audit.schedulersIndependent&&audit.schedulers100Hz&& ...
    strcmp(audit.steering.amplitude,'test_steer_amplitude')&& ...
    strcmp(audit.steering.frequency,'2*pi*test_steer_frequency')&& ...
    strcmp(strtrim(audit.steering.gain),'180/pi')&& ...
    strcmp(audit.steering.manualSwitchSetting,'0');
end
function x=parse_expr_list(s)
p=strsplit(s,',');x=zeros(1,numel(p));for k=1:numel(p),x(k)=str2num(p{k});end %#ok<ST2NM>
end
function tf=scheduler100(p)
tf=strcmp(get_param(p,'MaskType'),'Function-Call Generator')&& ...
    abs(str2double(get_param(p,'sample_time'))-0.01)<1e-15;
end
function src=source_of_port(p)
l=get_param(p,'Line');assert(l>0,'Unconnected input.');src=getfullname(get_param(l,'SrcBlockHandle'));
end
function src=source_of_trigger(b)
p=get_param(b,'PortHandles');src=source_of_port(p.Trigger(1));
end
function r=record_timeseries(ts)
assert(isa(ts,'timeseries'),'Expected timeseries, got %s.',class(ts));
r=struct('time',double(ts.Time(:)),'data',double(ts.Data), ...
    'sampleCount',numel(ts.Time),'dataSize',size(ts.Data));
end
function value=macro_value(text,key)
token=regexp(text,['(?m)^' key '\s+([^\r\n]+)'],'tokens','once');
assert(~isempty(token),'CarSim entry missing: %s',key);value=strtrim(token{1});
end
function p=solver_path_from_console(text)
token=regexp(text,'Use vehicle solver:\s*([^\r\n]+)','tokens','once');
if isempty(token),p='';else,p=strtrim(token{1});end
end
function s=prefdir_label(v)
if isempty(v),s='<UNSET>';else,s=v;end
end
function cleanup(m,oldPwd,oldPath)
if bdIsLoaded(m),close_system(m,0);end
if bdIsLoaded('Solver_SF'),close_system('Solver_SF',0);end
cd(oldPwd);path(oldPath);
evalin('base','clear test_speed test_steer_amplitude test_steer_frequency vy_v17_mode_code');
end
function [files,hashes]=frozen_manifest(root)
files={fullfile(root,'model','vx_vy_fixed_fusion_v2_5.slx'); ...
 fullfile(root,'model','vy_fixed_weight_fusion_simulink_sfun.m'); ...
 fullfile(root,'model','vy_fixed_weight_fusion_step.m'); ...
 fullfile(root,'model','vx_vy_parallel_dk_v2_3.slx'); ...
 fullfile(root,'model','vx_vy_dekf_v1_17.slx');fullfile(root,'model','vy_dynamic_ekf_v1_17.m'); ...
 fullfile(root,'model','vy_dynamic_ekf_step_v17.m');fullfile(root,'model','vy_dynamic_ekf_step_v13.m'); ...
 fullfile(root,'model','vx_vy_kkf_v2_1.slx');fullfile(root,'model','vx_vy_kkf_v2_1g_steer.slx'); ...
 fullfile(root,'model','vy_kinematic_kf_step.m');fullfile(root,'model','vy_kinematic_kf.m'); ...
 fullfile(root,'model','vx_vy_dkekf_v2_2.slx');fullfile(root,'model','vy_dkekf_baseline_step.m'); ...
 fullfile(root,'model','vy_dkekf_baseline.m');fullfile(root,'model','vy_dkekf_baseline_simulink_sfun.m'); ...
 fullfile(root,'model','vy_feedback_propagation_step.m'); ...
 fullfile(root,'model','vy_feedback_propagation_simulink_sfun.m'); ...
 fullfile(root,'model','vx_vy_feedback_track_v2_4.slx')};
hashes={'801FC3650B80416B13346200D296F654A25E36BD01AABBFD3CCC983D086258EE'; ...
 'B7185A2E26B2874D792266D6CBAEC26A8DED6FDFBDFC862ACC394DE01F94F30A'; ...
 '4DE407D651FD3366357BFFF181FDB8474273E769982A18EFB96426FC05CC254C'; ...
 '98461DB290723A5CCDF62398CE5063DE0C9B6C7586334D479B159A771EB128C0'; ...
 '108F819DCD1B71FD6D795D7148CBF32FE1A888AE9878908E894A07626ED003AE'; ...
 '5550D0389FC4D1DCF7F65B0E00B4C51A949F2B9ADD33C2D78D1122A31291A1A0'; ...
 '4010F6A4BD669AC048297C2F416F0B8826F729F4552D73445703184F052C4A4F'; ...
 '498A446E13E654387E3D36BF4694A336E75B2100E765DAC0414A01367531CDE4'; ...
 'B67A98A6080374304E2D3424F85589C913E6EC4DB25BC9912CBFD2BC441C2712'; ...
 '59B25C5E350140AB0EAFD8345D5A9145D6981B96481023537A3BD01A787F728E'; ...
 '3786646EE5163D231DD8964614A8875217DFA496EB593B455E4E029E26DA2244'; ...
 'F242CB75BA08D22CB1EED87731746CF80D54FD39C1899B45E9980A40576414D4'; ...
 'E768FB2AD33A6EEAABDE2FB7C40BE660B78F350A90C752327DC9B423F50F2E15'; ...
 '6475B9DBC93EB6E25C2BB9FAD81CA11B2E08C26E7F2AE6A33C50E35B2790B457'; ...
 '7E731D7DF0BB2CA4455E3AA16E7513114E04472D38C62F1F453B631056306973'; ...
 '12F0D82643D65AA5098ED20C0655234F3A2E7EF6D6F5E7DEE5B80BC1A201BDA1'; ...
 '80C21D2CDC74F23C964DC50EAC48F2C026AD27027B160BB851B491E301D0E5FF'; ...
 '2FF7E488CC60DD729EC4948066714A95DAC15BBDB08BA45004EF6A7C8E1234B0'; ...
 '951A0D6E454F9C4C8ECD90EB4AD0372270F7D5EDCC15203B68D877C2ED27BF84'};
end
function records=hash_files(files)
records=repmat(struct('path','','sha256',''),numel(files),1);
for k=1:numel(files),records(k)=struct('path',files{k},'sha256',sha256(files{k}));end
end
function ok=hashes_match(records,expected)
ok=numel(records)==numel(expected);
for k=1:numel(records),ok=ok&&strcmpi(records(k).sha256,expected{k});end
end
function h=sha256(file)
d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));
ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());while ds.read()~=-1,end
b=typecast(d.digest(),'uint8');h=upper(reshape(dec2hex(b,2).',1,[]));clear c
end
