function report = run_vy_dkekf_v2_2c2_preflight()
%RUN_VY_DKEKF_V2_2C2_PREFLIGHT Run the one authorized 0.20 s runtime.

root=fileparts(fileparts(mfilename('fullpath')));
modelDir=fullfile(root,'model');
modelFile=fullfile(modelDir,'vx_vy_dkekf_v2_2.slx');
resultFile=fullfile(root,'results','vy_dkekf_v2_2c2_preflight.mat');
simFile=fullfile(modelDir,'simfile.sim');
solverDir='D:\carsim\CarSim2021.0_Prog\Programs\solvers';
solverSfDir=fullfile(solverDir,'Matlab84+');
solverDll=fullfile(solverDir,'carsim_64.dll');
solverLibrary=fullfile(solverSfDir,'Solver_SF.slx');
modelName='vx_vy_dkekf_v2_2';

[frozen,expected]=frozen_manifest(root);
report=struct('stage','V2.2-C2 DK-EKF 0.20-S Runtime Preflight', ...
    'stopTime_s',0.20,'simulationCompleted',false,'simCalled',false, ...
    'carSimRun',false,'runtimeError',struct('identifier','', ...
    'message','','report',''),'raw',struct());
report.frozenBefore=hash_files(frozen);
assert_expected(report.frozenBefore,expected);
report.targetBefore=file_record(modelFile);
report.simfileBefore=file_record(simFile);
assert(strcmp(report.targetBefore.sha256, ...
    'e768fb2ad33a6eeaabde2fb7c40be660b78f350a90c752327dc9b423f50f2e15'), ...
    'Accepted formal target hash mismatch before runtime.');

assert(isfile(simFile),'Required model/simfile.sim is missing.');
assert(isfile(solverDll),'Authorized D:\\carsim solver DLL is missing.');
assert(isfile(solverLibrary),'Authorized D:\\carsim Solver_SF is missing.');
simText=fileread(simFile);
report.carSim=struct('progDir',macro_value(simText,'PROGDIR'), ...
    'dataDir',macro_value(simText,'DATADIR'),'solverPath',solverDll, ...
    'solverExists',isfile(solverDll),'simFile',simFile, ...
    'workingDirectory',modelDir, ...
    'historicalGDriveRequestPresent',contains(lower(simText),'g:\carsim'), ...
    'actualSolverPath','','actualHistoricalGDriveRequest',false);
assert(strcmpi(report.carSim.progDir,'D:\carsim\CarSim2021.0_Prog\'), ...
    'Runtime simfile PROGDIR is not the authorized D:\\carsim path.');
assert(strcmpi(report.carSim.dataDir,'D:\carsim\CarSim2021.0_Data\'), ...
    'Runtime simfile DATADIR is not the authorized D:\\carsim path.');
assert(~report.carSim.historicalGDriveRequestPresent, ...
    'Runtime simfile still requests G:\\carsim; runtime was not started.');

oldPath=path;oldFolder=pwd;
cleanup=onCleanup(@()cleanup_runtime(modelName,oldFolder,oldPath));
consoleText='';
try
    addpath(modelDir);addpath(solverDir);addpath(solverSfDir);cd(modelDir);
    Simulink.fileGenControl('set','CacheFolder', ...
        fullfile(tempdir,'vy_dkekf_v2_2c2_cache'),'CodeGenFolder', ...
        fullfile(tempdir,'vy_dkekf_v2_2c2_codegen'),'createDir',true);
    load_system('Solver_SF');load_system(modelFile);

    report.static=static_runtime_preflight(modelName,root);
    assert(report.static.requiredLogsOK&&report.static.uLogReplayInputsOK, ...
        'Existing target logs do not contain all replay-required inputs.');
    assert(report.static.boundaryOK&&report.static.c1Accepted, ...
        'Accepted C1 boundary/evidence is not intact.');

    wks=get_param(modelName,'ModelWorkspace');
    assignin(wks,'test_speed',20);assignin('base','test_speed',20);
    assignin(wks,'test_steer_amplitude',0.02);
    assignin(wks,'test_steer_frequency',0.4);
    assignin('base','test_steer_amplitude',0.02);
    assignin('base','test_steer_frequency',0.4);

    report.simCalled=true;
    consoleText=evalc([ ...
        'out=sim(modelName,''StopTime'',''0.20'',' ...
        '''ReturnWorkspaceOutputs'',''on'',''FastRestart'',''off'');']);
    fprintf('%s',consoleText);
    report.carSim.actualSolverPath=solver_path_from_console(consoleText);
    report.carSim.actualHistoricalGDriveRequest=contains(lower(consoleText), ...
        'g:\carsim');
    assert(~report.carSim.actualHistoricalGDriveRequest, ...
        'Runtime requested the prohibited historical G:\\carsim solver.');
    report.carSimRun=contains(consoleText,'Use vehicle solver:')&& ...
        contains(consoleText,'Termination at simulation time')&& ...
        strcmpi(report.carSim.actualSolverPath,solverDll);
    assert(report.carSimRun, ...
        'Authorized D:\\carsim completion evidence was not found.');

    names={'dkekf_u_log1','dkekf_x_log1','dkekf_P_log1','dkekf_diag_log1'};
    raw=struct();
    for k=1:numel(names)
        raw.(names{k})=timeseries_record(output_timeseries(out,names{k}));
    end
    report.raw=raw;
    report.simulationCompleted=true;
catch ME
    report.runtimeError.identifier=ME.identifier;
    report.runtimeError.message=ME.message;
    report.runtimeError.report=getReport(ME,'extended','hyperlinks','off');
end

report.consoleText=consoleText;
report.warnings=struct( ...
    'applicationService',contains(lower(consoleText),'applicationservice'), ...
    'nonfatal',report.simulationCompleted&& ...
        contains(lower(consoleText),'applicationservice'));
cleanup_runtime(modelName,oldFolder,oldPath);clear cleanup

report.frozenAfter=hash_files(frozen);
report.frozenHashesUnchanged=records_equal(report.frozenBefore,report.frozenAfter)&& ...
    records_match(report.frozenAfter,expected);
report.targetAfter=file_record(modelFile);
report.targetUnchanged=record_equal(report.targetBefore,report.targetAfter)&& ...
    strcmp(report.targetAfter.sha256, ...
    'e768fb2ad33a6eeaabde2fb7c40be660b78f350a90c752327dc9b423f50f2e15');
report.simfileAfter=file_record(simFile);
report.simfileUnchanged=record_equal(report.simfileBefore,report.simfileAfter);
save(resultFile,'report','-v7.3');

if ~report.simulationCompleted
    fprintf(2,'V2_2C2_RUNTIME_ERROR|simCalled=%d|carSimRun=%d|%s|%s\n', ...
        report.simCalled,report.carSimRun,report.runtimeError.identifier, ...
        report.runtimeError.message);
    error('VY_DKEKF:V2_2C2RuntimeFailed', ...
        'C2 runtime failed; evidence saved to %s.',resultFile);
end
assert(report.frozenHashesUnchanged,'A frozen/reference file changed.');
assert(report.targetUnchanged,'Formal target changed during runtime.');
assert(report.simfileUnchanged,'CarSim simfile changed during runtime.');
fprintf(['V2_2C2_RUNTIME_OK|stop=0.20|samples=%d/%d/%d/%d|' ...
    'simCalled=%d|carSimRun=%d|solver=%s|hash=%s\n'], ...
    report.raw.dkekf_u_log1.sampleCount, ...
    report.raw.dkekf_x_log1.sampleCount, ...
    report.raw.dkekf_P_log1.sampleCount, ...
    report.raw.dkekf_diag_log1.sampleCount,report.simCalled, ...
    report.carSimRun,report.carSim.actualSolverPath, ...
    report.targetAfter.sha256);
end

function audit=static_runtime_preflight(m,root)
sub=[m '/DK-EKF Baseline'];boundary=[sub '/DK-EKF Numeric Boundary'];
audit=struct();
audit.boundaryPath=boundary;
audit.boundaryOK=strcmp(get_param(boundary,'BlockType'),'M-S-Function')&& ...
    strcmp(get_param(boundary,'FunctionName'), ...
    'vy_dkekf_baseline_simulink_sfun');
logBlocks={[m '/DK-EKF u Log'],[m '/DK-EKF x Log'], ...
    [m '/DK-EKF P Log'],[m '/DK-EKF diag Log']};
expected={'dkekf_u_log1','dkekf_x_log1','dkekf_P_log1','dkekf_diag_log1'};
audit.logVariables=cellfun(@(b)get_param(b,'VariableName'),logBlocks, ...
    'UniformOutput',false);
audit.requiredLogsOK=isequal(audit.logVariables,expected);
mux=[m '/DK-EKF Input Log Mux'];ports=get_param(mux,'PortHandles');
audit.uLogWidth=str2double(get_param(mux,'Inputs'));
audit.uLogSources=cell(10,1);
for k=1:10,audit.uLogSources{k}=source_of_port(ports.Inport(k));end
expectedSources={[m '/Ax IMU Sensor 100Hz'];[m '/ay传感器']; ...
    [m '/AVz传感器'];[m '/DK-EKF Vx RT 100Hz']; ...
    [m '/DK-EKF Ay 20Hz Pulse'];[m '/DK-EKF Reset First Call']; ...
    [m '/DK-EKF Steering Demux'];[m '/DK-EKF Steering Demux']; ...
    [m '/DK-EKF Steering Demux'];[m '/DK-EKF Steering Demux']};
audit.uLogReplayInputsOK=audit.uLogWidth==10&& ...
    isequal(audit.uLogSources,expectedSources);
c1=load(fullfile(root,'results','vy_dkekf_v2_2c1_integration.mat'),'report');
audit.c1Accepted=isfield(c1,'report')&&c1.report.passed&& ...
    c1.report.gateCount==31&&c1.report.gatesTrue==31;
g=c1.report.gates;
audit.fairness=struct('trueVyOnline',~g.trueVyOnlineAbsent, ...
    'trueVxMeasurementOnly',g.trueVxMeasurementConnected&&g.noTrueVxBypass, ...
    'axPredictionInput',g.axConnected,'avzMeasurementOnly',g.avzConnected, ...
    'ayMeasurementOnly',g.ayConnected,'sharedStateAndP',true, ...
    'outputFusion',~g.noOutputFusion,'lifeSig',~g.noLifeSig, ...
    'adaptiveFusion',~g.noAdaptiveFusion);
end

function rec=timeseries_record(ts)
assert(isa(ts,'timeseries'),'Expected a timeseries runtime log.');
rec=struct('time',double(ts.Time(:)),'data',double(ts.Data), ...
    'sampleCount',numel(ts.Time),'dataSize',size(ts.Data), ...
    'dataClass',class(ts.Data));
end
function ts=output_timeseries(out,name)
try,ts=out.get(name);catch ME,error('VY_DKEKF:MissingRuntimeLog', ...
        'Simulation output is missing %s: %s',name,ME.message);end
assert(isa(ts,'timeseries'),'%s is not a timeseries.',name);
end
function source=source_of_port(port)
line=get_param(port,'Line');assert(line>0,'Required log input is unconnected.');
source=getfullname(get_param(line,'SrcBlockHandle'));
end
function value=macro_value(text,key)
token=regexp(text,['(?m)^' key '\s+([^\r\n]+)'],'tokens','once');
assert(~isempty(token),'CarSim config entry missing: %s',key);value=strtrim(token{1});
end
function pathText=solver_path_from_console(text)
token=regexp(text,'Use vehicle solver:\s*([^\r\n]+)','tokens','once');
if isempty(token),pathText='';else,pathText=strtrim(token{1});end
end
function cleanup_runtime(m,folder,oldPath)
if bdIsLoaded(m),close_system(m,0);end
if bdIsLoaded('Solver_SF'),close_system('Solver_SF',0);end
cd(folder);path(oldPath);
evalin('base',['clear test_speed test_steer_amplitude ' ...
    'test_steer_frequency']);
end
function [files,hashes]=frozen_manifest(root)
files={fullfile(root,'model','vx_vy_dkekf_v2_2.slx'); ...
    fullfile(root,'model','vy_dkekf_baseline_simulink_sfun.m'); ...
    fullfile(root,'model','vy_dkekf_baseline_step.m'); ...
    fullfile(root,'model','vy_dkekf_baseline.m'); ...
    fullfile(root,'model','vx_vy_dekf_v1_17.slx'); ...
    fullfile(root,'model','vy_kinematic_kf_step.m'); ...
    fullfile(root,'model','vy_kinematic_kf.m'); ...
    fullfile(root,'model','vx_vy_kkf_v2_1.slx'); ...
    fullfile(root,'model','vx_vy_kkf_v2_1g_steer.slx')};
hashes={'e768fb2ad33a6eeaabde2fb7c40be660b78f350a90c752327dc9b423f50f2e15'; ...
    '12f0d82643d65aa5098ed20c0655234f3a2e7ef6d6f5e7dee5b80bc1a201bda1'; ...
    '6475b9dbc93eb6e25c2bb9fad81ca11b2e08c26e7f2ae6a33c50e35b2790b457'; ...
    '7e731d7df0bb2ca4455e3aa16e7513114e04472d38c62f1f453b631056306973'; ...
    '108f819dcd1b71fd6d795d7148cbf32fe1a888ae9878908e894a07626ed003ae'; ...
    '3786646ee5163d231dd8964614a8875217dfa496eb593b455e4e029e26da2244'; ...
    'f242cb75ba08d22cb1eed87731746cf80d54fd39c1899b45e9980a40576414d4'; ...
    'b67a98a6080374304e2d3424f85589c913e6ec4db25bc9912cbfd2bc441c2712'; ...
    '59b25c5e350140ab0eafd8345d5a9145d6981b96481023537a3bd01a787f728e'};
end
function r=hash_files(files)
r=repmat(struct('path','','bytes',0,'modifiedDatenum',0,'sha256',''),numel(files),1);
for k=1:numel(files),r(k)=file_record(files{k});end
end
function r=file_record(pathText)
d=dir(pathText);assert(numel(d)==1,'Required file missing: %s',pathText);
r=struct('path',pathText,'bytes',d.bytes,'modifiedDatenum',d.datenum, ...
    'sha256',file_sha256(pathText));
end
function assert_expected(records,expected)
for k=1:numel(records),assert(strcmp(records(k).sha256,expected{k}), ...
        'Frozen hash mismatch: %s',records(k).path);end
end
function ok=records_match(records,expected)
ok=numel(records)==numel(expected);
for k=1:numel(records),ok=ok&&strcmp(records(k).sha256,expected{k});end
end
function ok=records_equal(a,b)
ok=numel(a)==numel(b);
for k=1:numel(a),ok=ok&&record_equal(a(k),b(k));end
end
function ok=record_equal(a,b)
ok=a.bytes==b.bytes&&a.modifiedDatenum==b.modifiedDatenum&& ...
    strcmp(a.sha256,b.sha256);
end
function hash=file_sha256(pathText)
d=java.security.MessageDigest.getInstance('SHA-256');
s=java.io.FileInputStream(java.io.File(pathText));
ds=java.security.DigestInputStream(s,d);c=onCleanup(@()ds.close());
while ds.read()~=-1,end
b=typecast(d.digest(),'uint8');hash=lower(reshape(dec2hex(b,2).',1,[]));clear c
end
