function tests = test_stage2_wss_candidate_and_window
%TEST_STAGE2_WSS_CANDIDATE_AND_WINDOW
% Unit tests for Stage-2 WSS candidate/window logic.
%
% Covers:
%   TEST 3 - single FL anomaly localization
%   TEST 4 - independent anomaly localization for all four wheels
%   TEST 7 - single-wheel NaN isolation
%
% MATLAB execution state: READY TO RUN
% VALIDATION state: PENDING MATLAB VALIDATION
%
% Run:
%   r = runtests('tests/test_stage2_wss_candidate_and_window.m');
%   table(r)

tests = functiontests(localfunctions);

end


%% ========================================================================
% TEST 3
% ========================================================================

function test_three_wheel_valid_one_wheel_anomaly_FL(testCase)
% TEST 3:
% Three-wheel-valid condition with one FL anomaly.
%
% Expected:
%   - window ready
%   - residual valid for all wheels
%   - FL residual large
%   - FR/RL/RR residual approximately zero

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;


%% Reset internal window

window_delta_velocity_indicator( ...
    0, ...
    0, ...
    0, ...
    zeros(4,1), ...
    true(4,1), ...
    1, ...
    p);


%% Fill window using constant four-wheel trajectory.

for k = 1:(N + 1)

    vxWheel = ...
        ones(4,1);

    [~, ~, ~, ~, ~, ~] = ...
        window_delta_velocity_indicator( ...
            0, ...
            0, ...
            0, ...
            vxWheel, ...
            true(4,1), ...
            0, ...
            p);

end


%% Inject one-shot FL anomaly during crossover.

vxWheel = ...
    ones(4,1);

vxWheel(1) = vxWheel(1) + 0.7;

[eSlip, DeltaVWheel, DeltaVImu, ...
    windowReady, slipReady, residualValid] = ...
    window_delta_velocity_indicator( ...
        0, ...
        0, ...
        0, ...
        vxWheel, ...
        true(4,1), ...
        0, ...
        p);


%% Basic finite/shape checks

testCase.verifySize(eSlip, [4,1]);

testCase.verifySize(DeltaVWheel, [4,1]);

testCase.verifyTrue(isscalar(DeltaVImu));

testCase.verifySize(residualValid, [4,1]);


%% Window status

testCase.verifyTrue( ...
    logical(windowReady), ...
    'TEST3: windowReady should be true');

testCase.verifyTrue( ...
    logical(slipReady), ...
    'TEST3: slipReady should be true');


%% Residual validity

testCase.verifyTrue( ...
    logical(residualValid(1)), ...
    'TEST3: FL residual should be valid');

testCase.verifyTrue( ...
    all(logical(residualValid(2:4))), ...
    'TEST3: FR/RL/RR residuals should remain valid');


%% FL anomaly should dominate

testCase.verifyGreaterThan( ...
    abs(eSlip(1)), ...
    0.6, ...
    'TEST3: FL eSlip should increase significantly');

testCase.verifyTrue( ...
    all(abs(eSlip(2:4)) < tol), ...
    'TEST3: unaffected wheel residuals should remain near zero');

end


%% ========================================================================
% TEST 4
% ========================================================================

function test_each_wheel_anomaly_independently(testCase)
% TEST 4:
% Inject the same anomaly independently into FL, FR, RL, RR.
%
% Verifies fixed wheel order:
%   1 = FL
%   2 = FR
%   3 = RL
%   4 = RR

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;


for idx = 1:4

    %% ---------------------------------------------------------------
    % Reset before testing each wheel
    % ----------------------------------------------------------------

    window_delta_velocity_indicator( ...
        0, ...
        0, ...
        0, ...
        ones(4,1), ...
        true(4,1), ...
        1, ...
        p);


    %% ---------------------------------------------------------------
    % Fill normal window
    % ----------------------------------------------------------------

    for k = 1:(N + 1)

        vxWheel = ...
            ones(4,1);

        [~, ~, ~, windowReady] = ...
            window_delta_velocity_indicator( ...
                0, ...
                0, ...
                0, ...
                vxWheel, ...
                true(4,1), ...
                0, ...
                p);

    end


    %% Normal window should already be mature

    testCase.verifyTrue( ...
        logical(windowReady), ...
        ['TEST4: window should be ready before anomaly, wheel ', ...
         num2str(idx)]);


    %% ---------------------------------------------------------------
    % Inject anomaly into current wheel
    % ----------------------------------------------------------------

    vxWheel = ...
        ones(4,1);

    vxWheel(idx) = ...
        vxWheel(idx) + 0.4;

    [eSlip, DeltaVWheel, DeltaVImu, ...
        windowReady, slipReady, residualValid] = ...
        window_delta_velocity_indicator( ...
            0, ...
            0, ...
            0, ...
            vxWheel, ...
            true(4,1), ...
            0, ...
            p);


    %% ---------------------------------------------------------------
    % Window status
    % ----------------------------------------------------------------

    testCase.verifyTrue( ...
        logical(windowReady), ...
        ['TEST4: windowReady should be true for wheel ', ...
         num2str(idx)]);

    testCase.verifyTrue( ...
        logical(slipReady), ...
        ['TEST4: slipReady should be true for wheel ', ...
         num2str(idx)]);


    %% ---------------------------------------------------------------
    % Residual validity
    % ----------------------------------------------------------------

    testCase.verifyTrue( ...
        logical(residualValid(idx)), ...
        ['TEST4: anomalous wheel residual should remain valid, wheel ', ...
         num2str(idx)]);

    otherIdx = setdiff(1:4, idx);

    testCase.verifyTrue( ...
        all(logical(residualValid(otherIdx))), ...
        ['TEST4: unaffected wheel residuals should remain valid, ', ...
         'anomaly wheel ', num2str(idx)]);


    %% ---------------------------------------------------------------
    % Target wheel residual
    % ----------------------------------------------------------------

    testCase.verifyGreaterThan( ...
        abs(eSlip(idx)), ...
        0.3, ...
        ['TEST4: target wheel residual should increase, wheel ', ...
         num2str(idx)]);


    %% ---------------------------------------------------------------
    % Other wheels remain approximately zero
    % ----------------------------------------------------------------

    testCase.verifyTrue( ...
        all(abs(eSlip(otherIdx)) < tol), ...
        ['TEST4: unaffected wheel residuals should remain near zero, ', ...
         'anomaly wheel ', num2str(idx)]);


    %% ---------------------------------------------------------------
    % Explicit fixed-order check
    % ----------------------------------------------------------------

    [~, maxIdx] = max(abs(eSlip));

    testCase.verifyEqual( ...
        maxIdx, ...
        idx, ...
        ['TEST4: wheel ordering/localization mismatch for wheel ', ...
         num2str(idx)]);


    %% ---------------------------------------------------------------
    % Extra finite checks
    % ----------------------------------------------------------------

    testCase.verifyTrue( ...
        all(isfinite(DeltaVWheel)), ...
        ['TEST4: DeltaVWheel should remain finite for wheel ', ...
         num2str(idx)]);

    testCase.verifyTrue( ...
        isfinite(DeltaVImu), ...
        ['TEST4: DeltaVImu should remain finite for wheel ', ...
         num2str(idx)]);

end

end


%% ========================================================================
% TEST 7
% ========================================================================

function test_single_wheel_nan_does_not_pollute_others(testCase)
% TEST 7:
% Single-wheel NaN should invalidate only that wheel.
%
% Inject NaN into RL = index 3.
%
% Expected:
%   - residualValid(3) = false
%   - eSlip(3) = NaN
%   - DeltaVWheel(3) = NaN
%   - other wheels remain finite
%   - windowReady/slipReady remain true

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;


%% Reset

window_delta_velocity_indicator( ...
    0, ...
    0, ...
    0, ...
    ones(4,1), ...
    true(4,1), ...
    1, ...
    p);


%% Fill healthy window

for k = 1:(N + 1)

    vxWheel = ...
        ones(4,1) * ...
        (k - 1) * Ts;

    [~, ~, ~, ~, ~, ~] = ...
        window_delta_velocity_indicator( ...
            0, ...
            0, ...
            0, ...
            vxWheel, ...
            true(4,1), ...
            0, ...
            p);

end


%% Inject NaN into RL wheel

vxWheel = ...
    ones(4,1) * ...
    (N + 1) * Ts;

vxWheel(3) = NaN;

[eSlip, DeltaVWheel, DeltaVImu, ...
    windowReady, slipReady, residualValid] = ...
    window_delta_velocity_indicator( ...
        0, ...
        0, ...
        0, ...
        vxWheel, ...
        true(4,1), ...
        0, ...
        p);


%% RL residual must be invalid

testCase.verifyFalse( ...
    logical(residualValid(3)), ...
    'TEST7: RL residualValid should be false');


%% RL outputs should be NaN

testCase.verifyTrue( ...
    isnan(DeltaVWheel(3)), ...
    'TEST7: RL DeltaVWheel should be NaN');

testCase.verifyTrue( ...
    isnan(eSlip(3)), ...
    'TEST7: RL eSlip should be NaN');


%% Other wheels should not be polluted

goodIdx = [1, 2, 4];

testCase.verifyTrue( ...
    all(logical(residualValid(goodIdx))), ...
    'TEST7: unaffected wheels should remain residual-valid');

testCase.verifyTrue( ...
    all(isfinite(DeltaVWheel(goodIdx))), ...
    'TEST7: unaffected DeltaVWheel values should remain finite');

testCase.verifyTrue( ...
    all(isfinite(eSlip(goodIdx))), ...
    'TEST7: unaffected eSlip values should remain finite');


%% Global window remains available

testCase.verifyTrue( ...
    logical(windowReady), ...
    'TEST7: windowReady should remain true');

testCase.verifyTrue( ...
    logical(slipReady), ...
    'TEST7: slipReady should remain true');


%% IMU delta should remain finite

testCase.verifyTrue( ...
    isfinite(DeltaVImu), ...
    'TEST7: DeltaVImu should remain finite');

end
