function tests = test_stage2_imu_track_and_fifo
%TEST_STAGE2_IMU_TRACK_AND_FIFO
% Unit tests for Stage-2 IMU integration and FIFO/window semantics.
%
% Covers:
%   TEST 1 - constant speed, Ax = 0
%   TEST 2 - constant Ax = 1 and linear wheel speed
%   TEST 3 - trapezoidal integration vs Euler integration
%   TEST 4 - Nwindow / Nwindow+1 boundary semantics
%   TEST 5 - startup window readiness
%   TEST 6 - reset during operation
%   TEST 7 - IMU NaN isolation
%   TEST 8 - yaw-rate independence when vyPrior = 0
%   TEST 9 - explicit 0.5 s window-span audit
%
% VALIDATION state: PENDING MATLAB VALIDATION
%
% Run:
%   r = runtests('tests/test_stage2_imu_track_and_fifo.m');
%   table(r)

tests = functiontests(localfunctions);

end


%% ========================================================================
% Setup
% ========================================================================

function setupOnce(testCase)
% Make the test independently runnable from the tests folder.

testDir = fileparts(mfilename('fullpath'));
matlabDir = fullfile(testDir, '..', 'matlab');

testCase.verifyTrue( ...
    isfolder(matlabDir), ...
    'Cannot find ../matlab source folder.');

testCase.applyFixture( ...
    matlab.unittest.fixtures.PathFixture(matlabDir));

end


%% ========================================================================
% TEST 1
% ========================================================================

function test_constant_speed_zero_ax(testCase)
% TEST 1:
% Constant wheel speed with Ax = 0.
%
% Expected:
%   DeltaVWheel = 0
%   DeltaVImu   = 0
%   eSlip       = 0

p = estimator_default_params();

N = p.Nwindow;
tol = 1e-10;

vxZero = ones(4,1);
validGeom = true(4,1);


%% Run N+2 samples so formal residual is available after reset sample

for k = 1:(N + 2)

    vxWheel = vxZero * 10;

    [eSlip, dVWheel, dVImu, ...
        windowReady, slipReady, residualValid] = ...
        window_delta_velocity_indicator( ...
            0, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

end


%% Window status

testCase.verifyTrue( ...
    logical(windowReady), ...
    'TEST1: windowReady should be true.');

testCase.verifyTrue( ...
    logical(slipReady), ...
    'TEST1: slipReady should be true.');

testCase.verifyTrue( ...
    all(logical(residualValid)), ...
    'TEST1: all four residuals should be valid.');


%% Delta velocities

testCase.verifyTrue( ...
    all(abs(dVWheel) < tol), ...
    'TEST1: DeltaVWheel should be zero.');

testCase.verifyLessThan( ...
    abs(dVImu), ...
    tol, ...
    'TEST1: DeltaVImu should be zero.');


%% Slip residual

testCase.verifyTrue( ...
    all(abs(eSlip) < tol), ...
    'TEST1: eSlip should be zero.');

end


%% ========================================================================
% TEST 2
% ========================================================================

function test_constant_ax_linear_velocity(testCase)
% TEST 2:
% Constant Ax = 1 m/s^2 and wheel velocity increasing linearly.
%
% Nwindow * Ts_est should represent a 0.5 s interval.
% Expected:
%   DeltaVWheel = 0.5 m/s
%   DeltaVImu   = 0.5 m/s
%   eSlip       = 0

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;

vxZero = ones(4,1);
validGeom = true(4,1);

expectedDeltaV = N * Ts;


%% Explicit Stage-2 window-duration contract

testCase.verifyEqual( ...
    expectedDeltaV, ...
    0.5, ...
    'AbsTol', tol, ...
    'TEST2: Nwindow*Ts_est should equal 0.5 s.');


%% Run

for k = 1:(N + 2)

    base = (k - 1) * Ts;

    vxWheel = vxZero * base;

    [eSlip, dVWheel, dVImu, ...
        windowReady, slipReady, residualValid] = ...
        window_delta_velocity_indicator( ...
            1, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

end


%% Status

testCase.verifyTrue(windowReady);

testCase.verifyTrue(slipReady);

testCase.verifyTrue(all(residualValid));


%% Wheel delta velocity

testCase.verifyEqual( ...
    dVWheel, ...
    expectedDeltaV * ones(4,1), ...
    'AbsTol', tol, ...
    'TEST2: wheel delta velocity should equal 0.5 m/s.');


%% IMU delta velocity

testCase.verifyEqual( ...
    dVImu, ...
    expectedDeltaV, ...
    'AbsTol', tol, ...
    'TEST2: IMU delta velocity should equal 0.5 m/s.');


%% Residual

testCase.verifyEqual( ...
    eSlip, ...
    zeros(4,1), ...
    'AbsTol', tol, ...
    'TEST2: eSlip should remain zero.');

end


%% ========================================================================
% TEST 3
% ========================================================================

function test_trapezoidal_integration(testCase)
% TEST 3:
% Explicitly distinguish trapezoidal integration from Euler integration.
%
% The last two non-zero acceleration transitions are:
%
%   0 -> 1
%   1 -> 3
%
% Trapezoidal contribution:
%
%   0.5*Ts*(0+1) + 0.5*Ts*(1+3)

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;

vxZero = ones(4,1);
validGeom = true(4,1);


%% First N samples

%% Explicit reset call
% Reset only clears persistent FIFO/state.
% It is NOT counted as the first valid window sample.

window_delta_velocity_indicator( ...
    0, ...
    0, ...
    0, ...
    zeros(4,1), ...
    validGeom, ...
    1, ...
    p);


%% First N VALID samples

for k = 1:N

    vxWheel = ...
        vxZero * ...
        (k - 1) * Ts;

    ax = 0;

    % At the Nth valid sample:
    % acceleration changes 0 -> 1.
    if k == N
        ax = 1;
    end

    window_delta_velocity_indicator( ...
        ax, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        0, ...          % IMPORTANT: reset already done above
        p);

end


%% N+1 sample: acceleration jumps from 1 to 3

vxWheel = ...
    vxZero * ...
    N * Ts;

[eTrap, dVWheelTrap, dVImuTrap, ...
    windowReadyTrap, slipReadyTrap, residualValidTrap] = ...
    window_delta_velocity_indicator( ...
        3, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        0, ...
        p);


%% Expected integration values

dvImuTrapExpected = ...
    0.5 * Ts * (0 + 1) + ...
    0.5 * Ts * (1 + 3);

dvImuEulerCurrentExpected = ...
    Ts * (1 + 3);

dvImuEulerPreviousExpected = ...
    Ts * 1;


%% Status checks

testCase.verifyTrue( ...
    windowReadyTrap, ...
    'TEST3: window should be ready.');

testCase.verifyTrue( ...
    slipReadyTrap, ...
    'TEST3: slip calculation should be ready.');

testCase.verifyTrue( ...
    all(residualValidTrap), ...
    'TEST3: all residuals should be valid.');


%% Finite outputs

testCase.verifyTrue( ...
    all(isfinite(eTrap)), ...
    'TEST3: eSlip should be finite.');

testCase.verifyTrue( ...
    all(isfinite(dVWheelTrap)), ...
    'TEST3: DeltaVWheel should be finite.');


%% Must equal trapezoidal result

testCase.verifyEqual( ...
    dVImuTrap, ...
    dvImuTrapExpected, ...
    'AbsTol', tol, ...
    'TEST3: IMU integration should use trapezoidal integration.');


%% Must NOT equal current-sample Euler integration

testCase.verifyGreaterThan( ...
    abs(dVImuTrap - dvImuEulerCurrentExpected), ...
    5e-3, ...
    'TEST3: result unexpectedly matches current-sample Euler integration.');


%% Must NOT equal previous-sample Euler integration

testCase.verifyGreaterThan( ...
    abs(dVImuTrap - dvImuEulerPreviousExpected), ...
    1e-3, ...
    'TEST3: result unexpectedly matches previous-sample Euler integration.');

end


%% ========================================================================
% TEST 4
% ========================================================================

function test_window_boundary_N_and_Nplus1(testCase)
% TEST 4:
%
% Formal Stage-2 boundary:
%
%   Calls 1 ... N-1:
%       windowReady  = false
%       slipReady    = false
%
%   Call N:
%       windowReady  = true
%       slipReady    = true
%       residualValid = false
%
%   Call N+1:
%       formal DeltaV/eSlip become valid

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;

vxZero = ones(4,1);
validGeom = true(4,1);


%% Calls 1 ... N
%% Explicit reset call
% Reset clears persistent FIFO state and is NOT counted
% as the first valid window sample.

window_delta_velocity_indicator( ...
    1, ...
    0, ...
    0, ...
    zeros(4,1), ...
    validGeom, ...
    1, ...
    p);
for k = 1:N

    vxWheel = ...
        vxZero * ...
        (k - 1) * Ts;

    [eStartup, dVWheelStartup, dVImuStartup, ...
        windowReadyStartup, slipReadyStartup, ...
        residualValidStartup] = ...
        window_delta_velocity_indicator( ...
            1, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            0, ...
            p);


    if k < N

        testCase.verifyFalse( ...
            windowReadyStartup, ...
            ['TEST4: windowReady should be false at call ', ...
             num2str(k)]);

        testCase.verifyFalse( ...
            slipReadyStartup, ...
            ['TEST4: slipReady should be false at call ', ...
             num2str(k)]);

        testCase.verifyFalse( ...
            any(residualValidStartup), ...
            'TEST4: residuals must be invalid during startup.');

        testCase.verifyTrue( ...
            isnan(dVImuStartup), ...
            'TEST4: DeltaVImu should be NaN during startup.');

        testCase.verifyTrue( ...
            all(isnan(dVWheelStartup)), ...
            'TEST4: DeltaVWheel should be NaN during startup.');

    else

        %% Nth call

        testCase.verifyTrue( ...
            windowReadyStartup, ...
            'TEST4: windowReady should become true at call N.');

        testCase.verifyTrue( ...
            slipReadyStartup, ...
            'TEST4: slipReady should become true at call N.');

        testCase.verifyFalse( ...
            any(residualValidStartup), ...
            'TEST4: formal residual should not yet be valid at call N.');

        testCase.verifyTrue( ...
            isnan(dVImuStartup), ...
            'TEST4: DeltaVImu should still be NaN at call N.');

        testCase.verifyTrue( ...
            all(isnan(dVWheelStartup)), ...
            'TEST4: DeltaVWheel should still be NaN at call N.');

        testCase.verifyTrue( ...
            all(isnan(eStartup)), ...
            'TEST4: eSlip should still be NaN at call N.');

    end

end


%% N+1 call

vxWheel = ...
    vxZero * ...
    N * Ts;

[eStartup, dVWheelStartup, dVImuStartup, ...
    windowReadyStartup, slipReadyStartup, ...
    residualValidStartup] = ...
    window_delta_velocity_indicator( ...
        1, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        0, ...
        p);


%% Formal residual now valid

testCase.verifyTrue(windowReadyStartup);

testCase.verifyTrue(slipReadyStartup);

testCase.verifyTrue(all(residualValidStartup));

testCase.verifyTrue(isfinite(dVImuStartup));

testCase.verifyTrue(all(isfinite(dVWheelStartup)));

testCase.verifyTrue(all(isfinite(eStartup)));


%% 0.5-s accumulated increment

expectedDeltaV = N * Ts;

testCase.verifyEqual( ...
    dVImuStartup, ...
    expectedDeltaV, ...
    'AbsTol', tol);

testCase.verifyEqual( ...
    dVWheelStartup, ...
    expectedDeltaV * ones(4,1), ...
    'AbsTol', tol);

end


%% ========================================================================
% TEST 5
% ========================================================================

function test_window_startup_readiness(testCase)
% TEST 5:
% Simpler independent test of windowReady transition.

p = estimator_default_params();

N = p.Nwindow;

vxWheel = ones(4,1);
validGeom = true(4,1);


%% First N+1 calls with a reset sample at k==1.

for k = 1:(N + 1)

    [~, ~, ~, windowReady] = ...
        window_delta_velocity_indicator( ...
            0, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

    if k < N + 1

        testCase.verifyFalse( ...
            windowReady, ...
            ['TEST5: window should not be ready at call ', ...
             num2str(k)]);

    else

        testCase.verifyTrue( ...
            windowReady, ...
            'TEST5: window should become ready at call N+1.');

    end

end

end


%% ========================================================================
% TEST 6
% ========================================================================

function test_reset_during_operation(testCase)
% TEST 6:
% A reset during mature operation must clear FIFO/window state.
%
% This version intentionally follows the same N/N+1 semantics as TEST 4.

p = estimator_default_params();

N = p.Nwindow;

vxWheel = ones(4,1) * 10;
validGeom = true(4,1);


%% ------------------------------------------------------------------------
% First mature the estimator
% -------------------------------------------------------------------------

for k = 1:(N + 1)

    [~, ~, ~, windowReady] = ...
        window_delta_velocity_indicator( ...
            0.5, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

end

testCase.verifyTrue( ...
    windowReady, ...
    'TEST6: pre-reset window should already be mature.');


%% ------------------------------------------------------------------------
% Force reset in the middle of operation
% -------------------------------------------------------------------------

[eReset, dVWheelReset, dVImuReset, ...
    windowReadyReset, slipReadyReset, residualValidReset] = ...
    window_delta_velocity_indicator( ...
        0.5, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        1, ...
        p);


%% Immediately after reset, window must no longer be mature

testCase.verifyFalse( ...
    windowReadyReset, ...
    'TEST6: reset must clear windowReady.');

testCase.verifyFalse( ...
    slipReadyReset, ...
    'TEST6: reset must clear slipReady.');

testCase.verifyFalse( ...
    any(residualValidReset), ...
    'TEST6: reset must invalidate formal residuals.');

testCase.verifyTrue( ...
    isnan(dVImuReset), ...
    'TEST6: DeltaVImu should be unavailable immediately after reset.');

testCase.verifyTrue( ...
    all(isnan(dVWheelReset)), ...
    'TEST6: DeltaVWheel should be unavailable immediately after reset.');

testCase.verifyTrue( ...
    all(isnan(eReset)), ...
    'TEST6: eSlip should be unavailable immediately after reset.');


%% ------------------------------------------------------------------------
% The reset sample is sample 1 of the new FIFO.
% Add samples 2 ... N+1.
% -------------------------------------------------------------------------

for k = 2:(N + 1)

    [eSlip, dVWheel, dVImu, ...
        windowReady, slipReady, residualValid] = ...
        window_delta_velocity_indicator( ...
            0.5, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            0, ...
            p);

end


%% Nth post-reset sample: window ready, formal residual not yet available

testCase.verifyTrue( ...
    windowReady, ...
    'TEST6: window should mature again at post-reset call N.');

testCase.verifyTrue( ...
    slipReady, ...
    'TEST6: slipReady should mature again.');

testCase.verifyFalse( ...
    any(residualValid), ...
    'TEST6: residual should still be invalid at call N.');

testCase.verifyTrue( ...
    isnan(dVImu), ...
    'TEST6: DeltaVImu should still be NaN at call N.');

testCase.verifyTrue( ...
    all(isnan(dVWheel)), ...
    'TEST6: DeltaVWheel should still be NaN at call N.');

testCase.verifyTrue( ...
    all(isnan(eSlip)), ...
    'TEST6: eSlip should still be NaN at call N.');


%% ------------------------------------------------------------------------
% N+1 post-reset sample
% -------------------------------------------------------------------------

[eSlip, dVWheel, dVImu, ...
    windowReady, slipReady, residualValid] = ...
    window_delta_velocity_indicator( ...
        0.5, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        0, ...
        p);


%% Formal calculation restored

testCase.verifyTrue(windowReady);

testCase.verifyTrue(slipReady);

testCase.verifyTrue(all(residualValid));

testCase.verifyTrue(all(isfinite(dVWheel)));

testCase.verifyTrue(isfinite(dVImu));

testCase.verifyTrue(all(isfinite(eSlip)));

end


%% ========================================================================
% TEST 7
% ========================================================================

function test_imu_nan_invalidates_imu_life(testCase)
% TEST 7:
% NaN Ax must invalidate the IMU track.
%
% It must NOT generate a fake finite DeltaVImu residual.

p = estimator_default_params();

N = p.Nwindow;

vxWheel = ones(4,1);
validGeom = true(4,1);


%% First sample / reset

[~, ~, ~, ~, ~, ~, imuLife] = ...
    window_delta_velocity_indicator( ...
        1, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        1, ...
        p);

testCase.verifyFalse( ...
    imuLife, ...
    'TEST7: reset call should clear IMU life state.');


%% Continue with healthy IMU samples (N+1 non-reset samples)

for k = 2:(N + 2)

    [~, ~, ~, ~, ~, ~, imuLife] = ...
        window_delta_velocity_indicator( ...
            1, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            0, ...
            p);

    testCase.verifyTrue( ...
        imuLife, ...
        ['TEST7: imuLife unexpectedly false at healthy call ', ...
         num2str(k)]);

end


%% Inject Ax = NaN

[eNaN, dVWheelNaN, dVImuNaN, ...
    windowReadyNaN, slipReadyNaN, ...
    residualValidNaN, imuLifeNaN] = ...
    window_delta_velocity_indicator( ...
        NaN, ...
        0, ...
        0, ...
        vxWheel, ...
        validGeom, ...
        0, ...
        p);


%% IMU track must become invalid

testCase.verifyFalse( ...
    imuLifeNaN, ...
    'TEST7: Ax=NaN must set imuLife=false.');


%% No fake IMU residual

testCase.verifyTrue( ...
    isnan(dVImuNaN), ...
    'TEST7: DeltaVImu must be NaN when IMU data are invalid.');


%% Formal residual cannot be trusted with invalid IMU track

testCase.verifyTrue( ...
    all(isnan(eNaN)) || ...
    all(~residualValidNaN), ...
    ['TEST7: invalid IMU must not produce ', ...
     'fake valid eSlip residuals.']);


%% Wheel path itself should not be contaminated by Ax NaN

testCase.verifyTrue( ...
    all(isfinite(dVWheelNaN)) || ...
    all(isnan(dVWheelNaN)), ...
    ['TEST7: wheel-side output should have ', ...
     'consistent finite/NaN semantics.']);


%% Keep explicit scalar status checks

testCase.verifyTrue(isscalar(windowReadyNaN));

testCase.verifyTrue(isscalar(slipReadyNaN));

end


%% ========================================================================
% TEST 8
% ========================================================================

function test_yaw_rate_does_not_change_imu_correction_when_vy_zero(testCase)
% TEST 8:
% With vyPrior = 0, changing yawRate should not change the
% Stage-2 IMU longitudinal correction tested here.
%
% Run A:
%   yawRate = 0
%
% Run B:
%   yawRate = 0.5
%
% Everything else is identical.

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;

vxZero = ones(4,1);
validGeom = true(4,1);


%% ------------------------------------------------------------------------
% Run A: yawRate = 0
% -------------------------------------------------------------------------

for k = 1:(N + 2)

    vxWheel = ...
        vxZero * ...
        (k - 1) * Ts;

    [eYaw1, dVYaw1, dVImuYaw1, ...
        windowReady1, slipReady1, residualValid1] = ...
        window_delta_velocity_indicator( ...
            1.2, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

end


%% ------------------------------------------------------------------------
% Run B: yawRate = 0.5
% -------------------------------------------------------------------------

for k = 1:(N + 2)

    vxWheel = ...
        vxZero * ...
        (k - 1) * Ts;

    [eYaw2, dVYaw2, dVImuYaw2, ...
        windowReady2, slipReady2, residualValid2] = ...
        window_delta_velocity_indicator( ...
            1.2, ...
            0.5, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

end


%% Both runs mature

testCase.verifyTrue(windowReady1);

testCase.verifyTrue(windowReady2);

testCase.verifyTrue(slipReady1);

testCase.verifyTrue(slipReady2);

testCase.verifyTrue(all(residualValid1));

testCase.verifyTrue(all(residualValid2));


%% Wheel delta velocity unchanged

testCase.verifyEqual( ...
    dVYaw1, ...
    dVYaw2, ...
    'AbsTol', tol, ...
    'TEST8: yawRate should not change DeltaVWheel.');


%% IMU delta velocity unchanged

testCase.verifyEqual( ...
    dVImuYaw1, ...
    dVImuYaw2, ...
    'AbsTol', tol, ...
    ['TEST8: yawRate should not change DeltaVImu ', ...
     'when vyPrior=0.']);


%% Slip residual unchanged

testCase.verifyEqual( ...
    eYaw1, ...
    eYaw2, ...
    'AbsTol', tol, ...
    ['TEST8: yawRate should not change eSlip ', ...
     'for this vyPrior=0 case.']);

end


%% ========================================================================
% TEST 9
% ========================================================================

function test_explicit_half_second_window_span(testCase)
% TEST 9:
% Explicit Stage-2 0.5-s index/window audit.
%
% Ax = 1 m/s^2
% wheel velocity increases exactly at 1 m/s^2
%
% Therefore over 0.5 s:
%
%   DeltaVImu   = 0.5 m/s
%   DeltaVWheel = 0.5 m/s
%   eSlip       = 0

p = estimator_default_params();

N = p.Nwindow;
Ts = p.Ts_est;
tol = 1e-10;

vxZero = ones(4,1);
validGeom = true(4,1);

expectedSpan = N * Ts;


%% Explicit parameter audit

testCase.verifyEqual( ...
    expectedSpan, ...
    0.5, ...
    'AbsTol', tol, ...
    ['TEST9: Stage-2 window should represent ', ...
     'exactly 0.5 s.']);


%% Run N+2 samples with reset on first sample

for k = 1:(N + 2)

    vxWheel = ...
        vxZero * ...
        ((k - 1) * Ts);

    [eSlip, dVWheel, dVImu, ...
        windowReady, slipReady, residualValid] = ...
        window_delta_velocity_indicator( ...
            1, ...
            0, ...
            0, ...
            vxWheel, ...
            validGeom, ...
            (k == 1), ...
            p);

end


%% Status

testCase.verifyTrue(windowReady);

testCase.verifyTrue(slipReady);

testCase.verifyTrue(all(residualValid));


%% IMU 0.5 m/s increment

testCase.verifyEqual( ...
    dVImu, ...
    0.5, ...
    'AbsTol', tol, ...
    'TEST9: DeltaVImu should equal 0.5 m/s.');


%% Four wheel 0.5 m/s increments

testCase.verifyEqual( ...
    dVWheel, ...
    0.5 * ones(4,1), ...
    'AbsTol', tol, ...
    'TEST9: each DeltaVWheel should equal 0.5 m/s.');


%% No discrepancy between WSS and IMU tracks

testCase.verifyEqual( ...
    eSlip, ...
    zeros(4,1), ...
    'AbsTol', tol, ...
    'TEST9: eSlip should remain zero.');

end
