function report = test_vy_dynamic_ekf_step_v15_debug_equivalence()
%TEST_VY_DYNAMIC_EKF_STEP_V15_DEBUG_EQUIVALENCE Gate for V1.5 simulation.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repoRoot, 'matlab'));
rng(1501, 'twister');

par = struct('m', 1860, 'Iz', 2687.1, 'a', 1.18, 'b', 1.77, ...
    'track', 1.575, 'Rw', 0.393);
Rcases = {[1e-2, 1e-2], [1e-2, 3.365172961808e-4], ...
    [6.851296026457e-4, 1.132438906288e-5]};

maxDifference = struct('x_new', 0, 'P_new', 0, ...
    'innovation', 0, 'NIS', 0, 'S', 0, 'K', 0);
testCount = 0;
for rIndex = 1:numel(Rcases)
    for sample = 1:40
        x = [0.15 * randn; 0.12 * randn];
        A = randn(2);
        P = 1e-4 * eye(2) + 0.08 * (A * A');
        u = [15 + 10 * rand; 0.03 * randn(4, 1)];
        z = [1.5 * randn; 0.15 * randn];
        cfg = struct('dt', 0.01, 'Q', diag([1e-4, 1e-3]), ...
            'R', diag(Rcases{rIndex}), 'denomEps', 1e-12, ...
            'lambda', zeros(4, 1));

        [xFormal, pFormal, infoFormal] = ...
            vy_dynamic_ekf_step(x, P, u, z, par, cfg);
        [xDebug, pDebug, infoDebug] = ...
            vy_dynamic_ekf_step_v15_debug(x, P, u, z, par, cfg);

        maxDifference.x_new = max(maxDifference.x_new, ...
            max(abs(xFormal - xDebug), [], 'all'));
        maxDifference.P_new = max(maxDifference.P_new, ...
            max(abs(pFormal - pDebug), [], 'all'));
        maxDifference.innovation = max(maxDifference.innovation, ...
            max(abs(infoFormal.innovation - infoDebug.innovation), [], 'all'));
        maxDifference.NIS = max(maxDifference.NIS, ...
            abs(infoFormal.NIS - infoDebug.NIS));
        maxDifference.S = max(maxDifference.S, ...
            max(abs(infoFormal.S - infoDebug.S), [], 'all'));
        maxDifference.K = max(maxDifference.K, ...
            max(abs(infoFormal.K - infoDebug.K), [], 'all'));
        testCount = testCount + 1;
    end
end

tolerance = 1e-12;
fields = fieldnames(maxDifference);
for k = 1:numel(fields)
    assert(maxDifference.(fields{k}) <= tolerance, ...
        'Formal/debug mismatch for %s: %.17g > %.17g.', ...
        fields{k}, maxDifference.(fields{k}), tolerance);
end

report = struct('passed', true, 'tolerance', tolerance, ...
    'testCount', testCount, 'maxDifference', maxDifference);
fprintf(['V1_5_EQUIVALENCE_PASS|tests=%d|tol=%.3g|x=%.3g|P=%.3g|', ...
    'innovation=%.3g|NIS=%.3g|S=%.3g|K=%.3g\n'], ...
    testCount, tolerance, maxDifference.x_new, maxDifference.P_new, ...
    maxDifference.innovation, maxDifference.NIS, maxDifference.S, ...
    maxDifference.K);
end
