function report = test_vy_dkekf_baseline_wrapper()
%TEST_VY_DKEKF_BASELINE_WRAPPER Persistent/reset behavior tests.

[par, cfg, Ts, P0] = baseline_configuration();
tol = 1e-12;
tests = 0;
Ax = 0.25;
steer = [0.02;0.02;0;0];
zVx = 20;
zr = 0.08;
zAy = 0.45;
doAy = true;
x0 = [zVx;0;0];

[xExpected, PExpected, infoExpected] = vy_dkekf_baseline_step( ...
    x0, P0, Ax, steer, zVx, zr, zAy, doAy, Ts, par, cfg);
clear vy_dkekf_baseline
[x1, P1, info1] = vy_dkekf_baseline( ...
    Ax, steer, zVx, zr, zAy, doAy, 1);
assert(max(abs(x1-xExpected)) <= tol && ...
    max(abs(P1(:)-PExpected(:))) <= tol, ...
    'Wrapper reset mapping differs from core reference.');
tests = tests + 1;

assert(isequal(info1.H_Vx,[1 0 0]) && ...
    isequal(info1.H_r,[0 0 1]) && info1.Ay.updateApplied, ...
    'Wrapper diagnostics/update forwarding mismatch.');
tests = tests + 1;

[x2, P2] = vy_dkekf_baseline(Ax, steer, zVx, zr, zAy, false, 0);
assert(all(isfinite([x2;P2(:)])) && ...
    max(abs(P2(:)-P1(:))) > 1e-12, ...
    'Persistent state/covariance did not advance.');
tests = tests + 1;

[xReset, PReset, infoReset] = vy_dkekf_baseline( ...
    Ax, steer, zVx, zr, zAy, doAy, 1);
assert(isequal(xReset,x1) && isequal(PReset,P1) && ...
    isequal(infoReset.F,info1.F), ...
    'Explicit reset is not exactly repeatable.');
tests = tests + 1;

clear vy_dkekf_baseline
[xFresh, PFresh] = vy_dkekf_baseline( ...
    Ax, steer, zVx, zr, zAy, doAy, 0);
assert(isequal(xFresh,x1) && isequal(PFresh,P1), ...
    'Fresh persistent initialization differs from explicit reset.');
tests = tests + 1;

wrapperPath = which('vy_dkekf_baseline');
wrapperText = lower(fileread(wrapperPath));
assert(nargin('vy_dkekf_baseline') == 7 && ...
    ~contains(wrapperText,'vy_true'), ...
    'Wrapper interface permits lateral truth leakage.');
tests = tests + 1;

assert(contains(wrapperText,'xstate = [z_vx; 0; 0]') && ...
    contains(wrapperText,'p0 = diag([0.1, 0.1, 0.1])'), ...
    'Wrapper reset must use measured Vx and zero Vy/r with mapped P0.');
tests = tests + 1;

report = struct('passed',true,'tests',tests, ...
    'resetStateMaxError',max(abs(xReset-x1)), ...
    'resetCovarianceMaxError',max(abs(PReset(:)-P1(:))), ...
    'stateDimension',numel(x1),'covarianceSize',size(P1), ...
    'resetUsesTrueVy',false);
fprintf(['DK_EKF_WRAPPER_TEST_OK|tests=%d|resetXErr=%.17g|' ...
    'resetPErr=%.17g\n'], tests, report.resetStateMaxError, ...
    report.resetCovarianceMaxError);
end

function [par, cfg, Ts, P0] = baseline_configuration()
par = struct('m',1860,'Iz',2687.1,'a',1.18,'b',1.77, ...
    'track',1.575,'Rw',0.393,'k_f',0.78181,'k_r',1.09186);
Ts = 0.01;
cfg = struct('Q_DK',diag([1e-4,1e-4,1e-4]), ...
    'R_Vx',1e-4,'R_r',3.365172961808e-4,'R_Ay',1e-2, ...
    'jacobianStep',1e-6,'denomEps',1e-12,'lambda',zeros(4,1));
P0 = diag([0.1,0.1,0.1]);
end
