function [simIn,cfg] = configure_vx_cs40_formal_v4c()
%CONFIGURE_VX_CS40_FORMAL_V4C Load and verify the frozen V4B A1 case.
% This function never invokes calibration, edits a model, or changes excitation.

root=fileparts(fileparts(mfilename('fullpath')));
v4bRoot=fullfile(root,'results','vx_formal_validation','v4b_cs40_drive_calibration');
freezeFile=fullfile(v4bRoot,'frozen_physical_excitation.json');
caseFile=fullfile(v4bRoot,'configured','A1','case_configuration.json');
assert(isfile(freezeFile)&&isfile(caseFile),'VX:V4C:MissingV4BFreeze');
freeze=jsondecode(fileread(freezeFile));base=jsondecode(fileread(caseFile));
expectedTime=[0;3;6;9;11.5;16];expectedSpeed=[40;40;70;70;40;40];
assert(strcmp(freeze.verdict,'VX_CS40_V4B_PHYSICAL_EXCITATION_FREEZE_PASS'), ...
    'VX:V4C:FreezeVerdict');
assert(strcmp(freeze.selectedCandidate,'A1'),'VX:V4C:Candidate');
assert(same_vector(freeze.speedTime_s,expectedTime)&&same_vector(freeze.speed_kmh,expectedSpeed), ...
    'VX:V4C:FreezeProfile');
assert(abs(freeze.initialSpeed_kmh-40)<=1e-12&&abs(freeze.muRoadConstant-0.30)<=1e-12, ...
    'VX:V4C:FreezeRoadState');
assert(freeze.driveGatePass&&freeze.brakeGatePass&&~freeze.formalEstimatorValidationRun, ...
    'VX:V4C:FreezeGate');
assert(strcmp(base.candidateId,'A1')&&same_vector(base.speedTime_s,expectedTime)&& ...
    same_vector(base.speed_kmh,expectedSpeed),'VX:V4C:BaseConfiguration');
assert(abs(base.initialSpeedValue-40)<=1e-12&&abs(base.muRoadConstant-0.30)<=1e-12&& ...
    abs(base.steeringRad)<=1e-12&&strcmp(base.referenceUnit,'km/h'), ...
    'VX:V4C:BasePhysicalConfiguration');

source=struct('model',fullfile(root,'model','vx.slx'), ...
    'estimator',fullfile(root,'model','longitudinal_velocity_estimator.m'), ...
    'parameter',fullfile(root,'model','estimator_default_params.m'), ...
    'wrapper',fullfile(root,'model','longitudinal_velocity_estimator_simulink.m'));
names=fieldnames(source);
for k=1:numel(names)
    assert(strcmp(sha256_file(source.(names{k})),freeze.sourceHashes.(names{k})), ...
        'VX:V4C:SourceHash','Frozen %s hash changed.',names{k});
end
assert(strcmp(sha256_file(base.generatedModel),freeze.generatedModelHash)&& ...
    strcmp(sha256_file(base.generatedModel),base.generatedModelHash), ...
    'VX:V4C:GeneratedModelHash');
assert(strcmp(sha256_file(base.runAll),freeze.controlHashes.runAll)&& ...
    strcmp(sha256_file(base.simfile),freeze.controlHashes.simfile)&& ...
    strcmp(sha256_file(base.controlManifestFile),freeze.controlHashes.manifest), ...
    'VX:V4C:ControlHash');
manifest=jsondecode(fileread(base.controlManifestFile));
assert(strcmp(manifest.sourceCparSha256,freeze.controlHashes.sourceCpar), ...
    'VX:V4C:SourceCparLineage');
runText=fileread(base.runAll);
assert(abs(token_number(runText,'SV_VXS')-40)<=0.1&& ...
    abs(token_number(runText,'MU_ROAD_CONSTANT')-0.30)<=1e-12&& ...
    abs(token_number(runText,'TSTOP')-16)<=1e-12,'VX:V4C:ActiveControlTokens');

[~,modelName]=fileparts(base.generatedModel);
simIn=Simulink.SimulationInput(modelName);
simIn=simIn.setModelParameter('StopTime','16','ReturnWorkspaceOutputs','on');
cfg=struct('stage','VX-V4C-CS40-FORMAL','caseId','VX-CS40','formalRuntime',true, ...
    'freezeFile',freezeFile,'freezeFileSha256',sha256_file(freezeFile), ...
    'v4bCaseConfigurationFile',caseFile,'v4bCaseConfigurationSha256',sha256_file(caseFile), ...
    'selectedCandidate','A1','speedTime_s',expectedTime,'speed_kmh',expectedSpeed, ...
    'referenceUnit','km/h','referenceWasDividedBy3p6',false,'initialSpeedToken','SV_VXS', ...
    'initialSpeed_kmh',40,'muRoadConstant',0.30,'steeringRad',0,'stopTime_s',16, ...
    'generatedModel',base.generatedModel,'generatedModelHash',freeze.generatedModelHash, ...
    'runtimeWorkingDirectory',base.runtimeWorkingDirectory,'runAll',base.runAll, ...
    'simfile',base.simfile,'controlManifestFile',base.controlManifestFile, ...
    'controlHashes',freeze.controlHashes,'sourceFiles',source,'sourceHashes',freeze.sourceHashes, ...
    'calibrationPhysicalEvidenceFile',freeze.physicalEvidenceFile, ...
    'calibrationPhysicalEvidenceSha256',freeze.physicalEvidenceSha256, ...
    'calibrationEvidenceUsedForEstimatorPerformance',false);
end

function yes=same_vector(actual,expected)
yes=isequal(double(actual(:)),double(expected(:)));
end
function value=token_number(text,name)
token=regexp(text,['(?m)^' regexptranslate('escape',name) '[ \t]+([-+0-9.eE]+)[ \t]*(?=\r?$)'],'tokens','once');
assert(~isempty(token),'VX:V4C:MissingToken','Missing token %s.',name);value=str2double(token{1});
assert(isfinite(value),'VX:V4C:InvalidToken','Invalid token %s.',name);
end
function hash=sha256_file(file)
d=java.security.MessageDigest.getInstance('SHA-256');s=java.io.FileInputStream(java.io.File(file));
q=java.security.DigestInputStream(s,d);c=onCleanup(@()q.close());while q.read()~=-1,end
hash=upper(reshape(dec2hex(typecast(d.digest(),'uint8'),2).',1,[]));clear c
end
